unit UMAJ1_2_3_26;

interface

implementation

uses JvUIB, Updates;

procedure MAJ1_2_3_26(Query: TJvUIBScript);
begin
  with Query do begin
    Script.Clear;

    Script.Add('ALTER PROCEDURE ACHATALBUMS_BY_EDITEUR (');
    Script.Add('    id_editeur char(38),');
    Script.Add('    filtre varchar(125))');
    Script.Add('returns (');
    Script.Add('    id_album char(38),');
    Script.Add('    titrealbum varchar(150),');
    Script.Add('    tome smallint,');
    Script.Add('    tomedebut smallint,');
    Script.Add('    tomefin smallint,');
    Script.Add('    horsserie smallint,');
    Script.Add('    integrale smallint,');
    Script.Add('    moisparution smallint,');
    Script.Add('    anneeparution smallint,');
    Script.Add('    id_serie char(38),');
    Script.Add('    titreserie varchar(150),');
    Script.Add('    achat smallint,');
    Script.Add('    complet integer)');
    Script.Add('as');
    Script.Add('declare variable swhere varchar(133);');
    Script.Add('BEGIN');
    Script.Add('  swhere = '''';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = ''and '' || filtre || '' '';');
    Script.Add('  FOR execute statement');
    Script.Add('     ''SELECT a.ID_ALBUM,');
    Script.Add('             a.TITREALBUM,');
    Script.Add('             a.TOME,');
    Script.Add('             a.TOMEDEBUT,');
    Script.Add('             a.TOMEFIN,');
    Script.Add('             a.HORSSERIE,');
    Script.Add('             a.INTEGRALE,');
    Script.Add('             a.MOISPARUTION,');
    Script.Add('             a.ANNEEPARUTION,');
    Script.Add('             a.ID_SERIE,');
    Script.Add('             s.TITRESERIE,');
    Script.Add('             a.ACHAT,');
    Script.Add('             a.COMPLET');
    Script.Add('      from albums a LEFT JOIN series s on a.id_serie = s.ID_SERIE');
    Script.Add('      WHERE coalesce(s.id_editeur, -1) = '''''' || :id_editeur || '''''' '' || swhere ||');
    Script.Add('      ''ORDER BY COALESCE(UPPERTITREALBUM, UPPERTITRESERIE), UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST''');
    Script.Add('      INTO :ID_ALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :MOISPARUTION,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :ACHAT,');
    Script.Add('           :COMPLET');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE ALBUMS_BY_ANNEE (');
    Script.Add('    annee integer,');
    Script.Add('    filtre varchar(125))');
    Script.Add('returns (');
    Script.Add('    id_album char(38),');
    Script.Add('    titrealbum varchar(150),');
    Script.Add('    tome smallint,');
    Script.Add('    tomedebut smallint,');
    Script.Add('    tomefin smallint,');
    Script.Add('    horsserie smallint,');
    Script.Add('    integrale smallint,');
    Script.Add('    moisparution smallint,');
    Script.Add('    anneeparution smallint,');
    Script.Add('    id_serie char(38),');
    Script.Add('    titreserie varchar(150),');
    Script.Add('    achat smallint,');
    Script.Add('    complet integer)');
    Script.Add('as');
    Script.Add('declare variable swhere varchar(200);');
    Script.Add('BEGIN');
    Script.Add('  if (:Annee = -1) then sWhere = ''ANNEEPARUTION is null '';');
    Script.Add('                   else sWhere = ''ANNEEPARUTION = '' || :ANNEE || '' '';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = swhere || ''and '' || filtre || '' '';');
    Script.Add('  for execute statement');
    Script.Add('      ''SELECT ID_ALBUM,');
    Script.Add('             TITREALBUM,');
    Script.Add('             TOME,');
    Script.Add('             TOMEDEBUT,');
    Script.Add('             TOMEFIN,');
    Script.Add('             HORSSERIE,');
    Script.Add('             INTEGRALE,');
    Script.Add('             MOISPARUTION,');
    Script.Add('             ANNEEPARUTION,');
    Script.Add('             ID_SERIE,');
    Script.Add('             TITRESERIE,');
    Script.Add('             ACHAT,');
    Script.Add('             COMPLET');
    Script.Add('        FROM vw_liste_albums');
    Script.Add('        WHERE '' || :sWHERE ||');
    Script.Add('        ''ORDER BY COALESCE(UPPERTITREALBUM, UPPERTITRESERIE), UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST''');
    Script.Add('        INTO :ID_ALBUM,');
    Script.Add('             :TITREALBUM,');
    Script.Add('             :TOME,');
    Script.Add('             :TOMEDEBUT,');
    Script.Add('             :TOMEFIN,');
    Script.Add('             :HORSSERIE,');
    Script.Add('             :INTEGRALE,');
    Script.Add('             :MOISPARUTION,');
    Script.Add('             :ANNEEPARUTION,');
    Script.Add('             :ID_SERIE,');
    Script.Add('             :TITRESERIE,');
    Script.Add('             :ACHAT,');
    Script.Add('             :COMPLET');
    Script.Add('      DO');
    Script.Add('      BEGIN');
    Script.Add('        SUSPEND;');
    Script.Add('      END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE ALBUMS_BY_COLLECTION (');
    Script.Add('    id_collection char(38),');
    Script.Add('    filtre varchar(125))');
    Script.Add('returns (');
    Script.Add('    id_album char(38),');
    Script.Add('    titrealbum varchar(150),');
    Script.Add('    tome smallint,');
    Script.Add('    tomedebut smallint,');
    Script.Add('    tomefin smallint,');
    Script.Add('    horsserie smallint,');
    Script.Add('    integrale smallint,');
    Script.Add('    moisparution smallint,');
    Script.Add('    anneeparution smallint,');
    Script.Add('    id_serie char(38),');
    Script.Add('    titreserie varchar(150),');
    Script.Add('    achat smallint,');
    Script.Add('    complet integer)');
    Script.Add('as');
    Script.Add('declare variable swhere varchar(200);');
    Script.Add('BEGIN');
    Script.Add('  if (:ID_COLLECTION = CAST('''' AS CHAR(38))) then sWhere = ''e.ID_COLLECTION is null '';');
    Script.Add('                           else sWhere = ''e.ID_COLLECTION = '''''' || :ID_COLLECTION || '''''' '';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = swhere || ''and '' || filtre || '' '';');
    Script.Add('  for execute statement');
    Script.Add('      ''SELECT a.ID_ALBUM,');
    Script.Add('             a.TITREALBUM,');
    Script.Add('             a.TOME,');
    Script.Add('             a.TOMEDEBUT,');
    Script.Add('             a.TOMEFIN,');
    Script.Add('             a.HORSSERIE,');
    Script.Add('             a.INTEGRALE,');
    Script.Add('             a.MOISPARUTION,');
    Script.Add('             a.ANNEEPARUTION,');
    Script.Add('             a.ID_SERIE,');
    Script.Add('             s.TITRESERIE,');
    Script.Add('             a.ACHAT,');
    Script.Add('             a.COMPLET');
    Script.Add('      from albums a left join editions e on a.ID_ALBUM = e.id_album');
    Script.Add('                    left join series s on a.id_serie = s.ID_SERIE');
    Script.Add('      WHERE '' || :sWHERE ||');
    Script.Add('     ''ORDER BY COALESCE(UPPERTITREALBUM, UPPERTITRESERIE), UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST''');
    Script.Add('      INTO :ID_ALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :MOISPARUTION,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :ACHAT,');
    Script.Add('           :COMPLET');
    Script.Add('      DO');
    Script.Add('      BEGIN');
    Script.Add('        SUSPEND;');
    Script.Add('      END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE ALBUMS_BY_EDITEUR (');
    Script.Add('    id_editeur char(38),');
    Script.Add('    filtre varchar(125))');
    Script.Add('returns (');
    Script.Add('    id_album char(38),');
    Script.Add('    titrealbum varchar(150),');
    Script.Add('    tome smallint,');
    Script.Add('    tomedebut smallint,');
    Script.Add('    tomefin smallint,');
    Script.Add('    horsserie smallint,');
    Script.Add('    integrale smallint,');
    Script.Add('    moisparution smallint,');
    Script.Add('    anneeparution smallint,');
    Script.Add('    id_serie char(38),');
    Script.Add('    titreserie varchar(150),');
    Script.Add('    achat smallint,');
    Script.Add('    complet integer)');
    Script.Add('as');
    Script.Add('declare variable swhere varchar(133);');
    Script.Add('BEGIN');
    Script.Add('  swhere = '''';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = ''and '' || filtre || '' '';');
    Script.Add('  FOR execute statement');
    Script.Add('     ''SELECT a.ID_ALBUM,');
    Script.Add('             a.TITREALBUM,');
    Script.Add('             a.TOME,');
    Script.Add('             a.TOMEDEBUT,');
    Script.Add('             a.TOMEFIN,');
    Script.Add('             a.HORSSERIE,');
    Script.Add('             a.INTEGRALE,');
    Script.Add('             a.MOISPARUTION,');
    Script.Add('             a.ANNEEPARUTION,');
    Script.Add('             a.ID_SERIE,');
    Script.Add('             s.TITRESERIE,');
    Script.Add('             a.ACHAT,');
    Script.Add('             a.COMPLET');
    Script.Add('      from albums a LEFT join editions e on a.ID_ALBUM = e.id_album');
    Script.Add('                    LEFT join series s on a.id_serie = s.ID_SERIE');
    Script.Add('      WHERE coalesce(e.id_editeur, -1) = '''''' || :id_editeur || '''''' '' || swhere ||');
    Script.Add('      ''ORDER BY COALESCE(UPPERTITREALBUM, UPPERTITRESERIE), UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST''');
    Script.Add('      INTO :ID_ALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :MOISPARUTION,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :ACHAT,');
    Script.Add('           :COMPLET');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE ALBUMS_BY_GENRE (');
    Script.Add('    id_genre char(38),');
    Script.Add('    filtre varchar(125))');
    Script.Add('returns (');
    Script.Add('    id_album char(38),');
    Script.Add('    titrealbum varchar(150),');
    Script.Add('    tome smallint,');
    Script.Add('    tomedebut smallint,');
    Script.Add('    tomefin smallint,');
    Script.Add('    horsserie smallint,');
    Script.Add('    integrale smallint,');
    Script.Add('    moisparution smallint,');
    Script.Add('    anneeparution smallint,');
    Script.Add('    id_serie char(38),');
    Script.Add('    titreserie varchar(150),');
    Script.Add('    achat smallint,');
    Script.Add('    complet integer)');
    Script.Add('as');
    Script.Add('declare variable swhere varchar(200);');
    Script.Add('BEGIN');
    Script.Add('  if (:ID_Genre = CAST('''' AS CHAR(38))) then sWhere = ''ID_Genre is null '';');
    Script.Add('                      else sWhere = ''ID_genre = '''''' || :ID_genre || '''''' '';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = swhere || ''and '' || filtre || '' '';');
    Script.Add('  for execute statement');
    Script.Add('      ''SELECT ID_ALBUM,');
    Script.Add('             TITREALBUM,');
    Script.Add('             TOME,');
    Script.Add('             TOMEDEBUT,');
    Script.Add('             TOMEFIN,');
    Script.Add('             HORSSERIE,');
    Script.Add('             INTEGRALE,');
    Script.Add('             MOISPARUTION,');
    Script.Add('             ANNEEPARUTION,');
    Script.Add('             a.ID_SERIE,');
    Script.Add('             TITRESERIE,');
    Script.Add('             ACHAT,');
    Script.Add('             COMPLET');
    Script.Add('       FROM VW_LISTE_ALBUMS a LEFT JOIN GENRESERIES gs ON gs.id_serie = a.id_serie');
    Script.Add('                              LEFT JOIN GENRES g ON gs.id_genre = g.ID_GENRE');
    Script.Add('       WHERE '' || :sWHERE ||');
    Script.Add('      ''ORDER BY coalesce(UPPERTITREALBUM, UPPERTITRESERIE), UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST''');
    Script.Add('       INTO :ID_ALBUM,');
    Script.Add('            :TITREALBUM,');
    Script.Add('            :TOME,');
    Script.Add('            :TOMEDEBUT,');
    Script.Add('            :TOMEFIN,');
    Script.Add('            :HORSSERIE,');
    Script.Add('            :INTEGRALE,');
    Script.Add('            :MOISPARUTION,');
    Script.Add('            :ANNEEPARUTION,');
    Script.Add('            :ID_SERIE,');
    Script.Add('            :TITRESERIE,');
    Script.Add('            :ACHAT,');
    Script.Add('            :COMPLET');
    Script.Add('      DO');
    Script.Add('      BEGIN');
    Script.Add('        SUSPEND;');
    Script.Add('      END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE ALBUMS_BY_INITIALE (');
    Script.Add('    initiale char(1),');
    Script.Add('    filtre varchar(125))');
    Script.Add('returns (');
    Script.Add('    id_album char(38),');
    Script.Add('    titrealbum varchar(150),');
    Script.Add('    tome smallint,');
    Script.Add('    tomedebut smallint,');
    Script.Add('    tomefin smallint,');
    Script.Add('    horsserie smallint,');
    Script.Add('    integrale smallint,');
    Script.Add('    moisparution smallint,');
    Script.Add('    anneeparution smallint,');
    Script.Add('    id_serie char(38),');
    Script.Add('    titreserie varchar(150),');
    Script.Add('    achat smallint,');
    Script.Add('    complet integer)');
    Script.Add('as');
    Script.Add('declare variable swhere varchar(133);');
    Script.Add('BEGIN');
    Script.Add('  swhere = '''';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = '' and '' || filtre || '' '';');
    Script.Add('  FOR execute statement');
    Script.Add('     ''SELECT a.ID_ALBUM,');
    Script.Add('             a.TITREALBUM,');
    Script.Add('             a.TOME,');
    Script.Add('             a.TOMEDEBUT,');
    Script.Add('             a.TOMEFIN,');
    Script.Add('             a.HORSSERIE,');
    Script.Add('             a.INTEGRALE,');
    Script.Add('             a.MOISPARUTION,');
    Script.Add('             a.ANNEEPARUTION,');
    Script.Add('             a.ID_SERIE,');
    Script.Add('             s.TITRESERIE,');
    Script.Add('             a.ACHAT,');
    Script.Add('             a.COMPLET');
    Script.Add('      FROM ALBUMS a LEFT JOIN SERIES s ON s.ID_SERIE = a.id_serie');
    Script.Add('      WHERE coalesce(a.initialetitrealbum, s.initialetitreserie) = '''''' ||: INITIALE || '''''' '' || swhere ||');
    Script.Add('      ''ORDER BY coalesce(UPPERTITREALBUM, UPPERTITRESERIE), UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST ''');
    Script.Add('      INTO :ID_ALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :MOISPARUTION,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :ACHAT,');
    Script.Add('           :COMPLET');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_AUTEUR (');
    Script.Add('    id_auteur char(38),');
    Script.Add('    filtre varchar(125))');
    Script.Add('returns (');
    Script.Add('    id_album char(38),');
    Script.Add('    titrealbum varchar(150),');
    Script.Add('    tome smallint,');
    Script.Add('    tomedebut smallint,');
    Script.Add('    tomefin smallint,');
    Script.Add('    horsserie smallint,');
    Script.Add('    integrale smallint,');
    Script.Add('    moisparution smallint,');
    Script.Add('    anneeparution smallint,');
    Script.Add('    id_serie char(38),');
    Script.Add('    titreserie varchar(150),');
    Script.Add('    metier smallint,');
    Script.Add('    achat smallint,');
    Script.Add('    complet integer)');
    Script.Add('as');
    Script.Add('declare variable swhere varchar(200);');
    Script.Add('BEGIN');
    Script.Add('  swhere = '''';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = ''and '' || filtre || '' '';');
    Script.Add('  FOR execute statement');
    Script.Add('     ''SELECT A.ID_ALBUM,');
    Script.Add('             A.TITREALBUM,');
    Script.Add('             A.TOME,');
    Script.Add('             A.TOMEDEBUT,');
    Script.Add('             A.TOMEFIN,');
    Script.Add('             A.HORSSERIE,');
    Script.Add('             A.INTEGRALE,');
    Script.Add('             A.MOISPARUTION,');
    Script.Add('             A.ANNEEPARUTION,');
    Script.Add('             A.ID_SERIE,');
    Script.Add('             A.TITRESERIE,');
    Script.Add('             AU.metier,');
    Script.Add('             A.ACHAT,');
    Script.Add('             A.COMPLET');
    Script.Add('      FROM vw_liste_albums A INNER JOIN auteurs au on a.ID_album = au.ID_album');
    Script.Add('      WHERE au.ID_personne = '''''' || :id_auteur || '''''' '' || swhere ||');
    Script.Add('      ''ORDER BY UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST, coalesce(UPPERTITREALBUM, UPPERTITRESERIE), METIER''');
    Script.Add('      INTO :ID_ALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :MOISPARUTION,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :METIER,');
    Script.Add('           :ACHAT,');
    Script.Add('           :COMPLET');
    Script.Add('      DO');
    Script.Add('      BEGIN');
    Script.Add('        SUSPEND;');
    Script.Add('      END');
    Script.Add('end;');

    ExecuteScript;
  end;
end;

initialization
  RegisterFBUpdate('1.2.3.26', @MAJ1_2_3_26);

end.

