unit UMAJ0_0_3_19;

interface

implementation

uses UIB, Updates;

procedure MAJ0_0_3_19(Query: TUIBScript);
begin
  Query.Script.Clear;

  Query.Script.Add('ALTER TABLE EDITIONS ALTER ISBN TYPE CHAR(13);');

  Query.Script.Add('ALTER PROCEDURE PREVISIONS_SORTIES (');
  Query.Script.Add('    INTEGRAL SMALLINT,');
  Query.Script.Add('    IN_REFSERIE INTEGER)');
  Query.Script.Add('RETURNS (');
  Query.Script.Add('    REFSERIE INTEGER,');
  Query.Script.Add('    TITRESERIE VARCHAR(150),');
  Query.Script.Add('    UPPERTITRESERIE VARCHAR(150),');
  Query.Script.Add('    TOME INTEGER,');
  Query.Script.Add('    ANNEEPARUTION INTEGER,');
  Query.Script.Add('    REFEDITEUR INTEGER,');
  Query.Script.Add('    NOMEDITEUR VARCHAR(50),');
  Query.Script.Add('    REFCOLLECTION INTEGER,');
  Query.Script.Add('    NOMCOLLECTION VARCHAR(50))');
  Query.Script.Add('AS');
  Query.Script.Add('DECLARE VARIABLE CURRENTREFSERIE INTEGER;');
  Query.Script.Add('DECLARE VARIABLE OLDREFSERIE INTEGER;');
  Query.Script.Add('DECLARE VARIABLE CURRENTTOME INTEGER;');
  Query.Script.Add('DECLARE VARIABLE MAXTOME INTEGER;');
  Query.Script.Add('DECLARE VARIABLE MAXTOME2 INTEGER;');
  Query.Script.Add('DECLARE VARIABLE SOMMEPONDEREE INTEGER;');
  Query.Script.Add('DECLARE VARIABLE COMPTEALBUM INTEGER;');
  Query.Script.Add('DECLARE VARIABLE CURRENTANNEE INTEGER;');
  Query.Script.Add('DECLARE VARIABLE MAXANNEE INTEGER;');
  Query.Script.Add('DECLARE VARIABLE TOMEPRECEDENT INTEGER;');
  Query.Script.Add('DECLARE VARIABLE ANNEEPRECEDENTE INTEGER;');
  Query.Script.Add('begin');
  Query.Script.Add('  oldrefserie = -1;');
  Query.Script.Add('  tomeprecedent = -1;');
  Query.Script.Add('  anneeprecedente = -1;');
  Query.Script.Add('  for select TOME, ANNEEPARUTION, s.RefSerie from');
  Query.Script.Add('        albums a inner join series s on s.refserie = a.refserie');
  Query.Script.Add('        where (s.terminee is null or s.terminee <> 1)');
  Query.Script.Add('        and a.horsserie = 0 and a.integrale = 0 and a.anneeparution is not null');
  Query.Script.Add('        and (:in_refserie is null or s.refserie = :in_refserie)');
  Query.Script.Add('        order by s.refserie, TOME');
  Query.Script.Add('        into');
  Query.Script.Add('          :CURRENTTOME,');
  Query.Script.Add('          :CURRENTANNEE,');
  Query.Script.Add('          :CURRENTREFSERIE');
  Query.Script.Add('  do begin');
  Query.Script.Add('    if (currentrefserie <> oldrefserie) then begin');
  Query.Script.Add('');
  Query.Script.Add('      if (oldrefserie <> -1 and comptealbum > 0) then begin');
  Query.Script.Add('        select MAX(TOME) + 1, MAX(ANNEEPARUTION) from albums');
  Query.Script.Add('        where horsserie = 0 and integrale = 0 and refserie = :oldrefserie');
  Query.Script.Add('        into');
  Query.Script.Add('          :TOME,');
  Query.Script.Add('          :MAXANNEE;');
  Query.Script.Add('');
  Query.Script.Add('        if (INTEGRAL = 1) then begin');
  Query.Script.Add('          select max(tomefin) + 1 from albums');
  Query.Script.Add('          where integrale = 1 and refserie = :oldrefserie');
  Query.Script.Add('          into');
  Query.Script.Add('            :MAXTOME2;');
  Query.Script.Add('');
  Query.Script.Add('          if (maxtome2 > tome) then tome = maxtome2;');
  Query.Script.Add('        end');
  Query.Script.Add('');
  Query.Script.Add('        select s.RefSerie, s.TitreSerie, s.UpperTitreSerie, e.RefEditeur, e.NomEditeur, c.RefCollection, c.NomCollection from');
  Query.Script.Add('          series s left join editeurs e on e.refediteur = s.refediteur');
  Query.Script.Add('                   left join collections c on c.refcollection = s.refcollection');
  Query.Script.Add('        where s.RefSerie = :oldrefserie');
  Query.Script.Add('        into');
  Query.Script.Add('          :REFSERIE,');
  Query.Script.Add('          :TITRESERIE,');
  Query.Script.Add('          :UPPERTITRESERIE,');
  Query.Script.Add('          :REFEDITEUR,');
  Query.Script.Add('          :NOMEDITEUR,');
  Query.Script.Add('          :REFCOLLECTION,');
  Query.Script.Add('          :NOMCOLLECTION;');
  Query.Script.Add('');
  Query.Script.Add('        ANNEEPARUTION = maxannee + ((tome - maxtome) * (sommeponderee / comptealbum));');
  Query.Script.Add('        suspend;');
  Query.Script.Add('      end');
  Query.Script.Add('');
  Query.Script.Add('      oldrefserie = currentrefserie;');
  Query.Script.Add('      sommeponderee = 0;');
  Query.Script.Add('      comptealbum = 0;');
  Query.Script.Add('      tomeprecedent = -1;');
  Query.Script.Add('      anneeprecedente = -1;');
  Query.Script.Add('    end');
  Query.Script.Add('    if (tomeprecedent <> -1) then begin');
  Query.Script.Add('      /* non pondéré: sommeponderee = sommeponderee + ((CURRENTANNEE - ANNEEPRECEDENTE) / (CURRENTTOME - TOMEPRECEDENT)); */');
  Query.Script.Add('      sommeponderee = sommeponderee + ((CURRENTANNEE - ANNEEPRECEDENTE) / (CURRENTTOME - TOMEPRECEDENT)) * CURRENTTOME;');
  Query.Script.Add('      /* non pondéré: comptealbum = comptealbum + 1;*/');
  Query.Script.Add('      comptealbum = comptealbum + CURRENTTOME;');
  Query.Script.Add('    end');
  Query.Script.Add('    tomeprecedent = CURRENTTOME;');
  Query.Script.Add('    anneeprecedente = CURRENTANNEE;');
  Query.Script.Add('    maxtome = CURRENTTOME;');
  Query.Script.Add('  end');
  Query.Script.Add('');
  Query.Script.Add('  if (oldrefserie <> -1 and comptealbum > 0) then begin');
  Query.Script.Add('    select MAX(TOME) + 1, MAX(ANNEEPARUTION) from albums');
  Query.Script.Add('    where horsserie = 0 and integrale = 0 and refserie = :oldrefserie');
  Query.Script.Add('    into');
  Query.Script.Add('      :TOME,');
  Query.Script.Add('      :MAXANNEE;');
  Query.Script.Add('');
  Query.Script.Add('    if (INTEGRAL = 1) then begin');
  Query.Script.Add('      select max(tomefin) + 1 from albums');
  Query.Script.Add('      where integrale = 1 and refserie = :oldrefserie');
  Query.Script.Add('      into');
  Query.Script.Add('        :MAXTOME2;');
  Query.Script.Add('');
  Query.Script.Add('      if (maxtome2 > tome) then tome = maxtome2;');
  Query.Script.Add('    end');
  Query.Script.Add('');
  Query.Script.Add('    select s.RefSerie, s.TitreSerie, s.UpperTitreSerie, e.RefEditeur, e.NomEditeur, c.RefCollection, c.NomCollection from');
  Query.Script.Add('      series s left join editeurs e on e.refediteur = s.refediteur');
  Query.Script.Add('               left join collections c on c.refcollection = s.refcollection');
  Query.Script.Add('    where s.RefSerie = :oldrefserie');
  Query.Script.Add('    into');
  Query.Script.Add('      :REFSERIE,');
  Query.Script.Add('      :TITRESERIE,');
  Query.Script.Add('      :UPPERTITRESERIE,');
  Query.Script.Add('      :REFEDITEUR,');
  Query.Script.Add('      :NOMEDITEUR,');
  Query.Script.Add('      :REFCOLLECTION,');
  Query.Script.Add('      :NOMCOLLECTION;');
  Query.Script.Add('');
  Query.Script.Add('    ANNEEPARUTION = maxannee + ((tome - maxtome) * (sommeponderee / comptealbum));');
  Query.Script.Add('    suspend;');
  Query.Script.Add('  end');
  Query.Script.Add('end;');

  Query.Script.Add('ALTER PROCEDURE ALBUMS_MANQUANTS (');
  Query.Script.Add('    INTEGRALE INTEGER,');
  Query.Script.Add('    IN_REFSERIE Integer)');
  Query.Script.Add('RETURNS (');
  Query.Script.Add('    REFSERIE Integer,');
  Query.Script.Add('    COUNTSERIE Integer,');
  Query.Script.Add('    TITRESERIE VARCHAR(150),');
  Query.Script.Add('    UPPERTITRESERIE VARCHAR(150),');
  Query.Script.Add('    TOME Integer,');
  Query.Script.Add('    REFEDITEUR Integer,');
  Query.Script.Add('    NOMEDITEUR VARCHAR(50),');
  Query.Script.Add('    REFCOLLECTION Integer,');
  Query.Script.Add('    NOMCOLLECTION VARCHAR(50))');
  Query.Script.Add('AS');
  Query.Script.Add('DECLARE VARIABLE MAXSERIE INTEGER;');
  Query.Script.Add('DECLARE VARIABLE CURRENTTOME Integer;');
  Query.Script.Add('DECLARE VARIABLE OWNEDTOME Integer;');
  Query.Script.Add('begin');
  Query.Script.Add('  if (integrale is Null) then integrale = 1;');
  Query.Script.Add('  for select');
  Query.Script.Add('        A.REFSERIE,');
  Query.Script.Add('        max(TOME),');
  Query.Script.Add('        count(distinct TOME),');
  Query.Script.Add('        S.REFEDITEUR,');
  Query.Script.Add('        NOMEDITEUR,');
  Query.Script.Add('        S.REFCOLLECTION,');
  Query.Script.Add('        NOMCOLLECTION');
  Query.Script.Add('      from liste_tomes(:integrale) A inner join SERIES S on A.REFSERIE = S.REFSERIE');
  Query.Script.Add('                                     left join EDITEURS E on S.REFEDITEUR = E.REFEDITEUR');
  Query.Script.Add('                                     left join COLLECTIONS C on S.REFCOLLECTION = C.REFCOLLECTION');
  Query.Script.Add('      where S.COMPLETE = 0');
  Query.Script.Add('        and (:in_refserie is null or s.refserie = :in_refserie)');
  Query.Script.Add('      group by A.REFSERIE, UPPERTITRESERIE, UPPERNOMEDITEUR, UPPERNOMCOLLECTION,');
  Query.Script.Add('               S.REFEDITEUR, NOMEDITEUR, S.REFCOLLECTION, NOMCOLLECTION');
  Query.Script.Add('      order by UPPERTITRESERIE, UPPERNOMEDITEUR, UPPERNOMCOLLECTION');
  Query.Script.Add('      into');
  Query.Script.Add('        :REFSERIE,');
  Query.Script.Add('        :MAXSERIE,');
  Query.Script.Add('        :COUNTSERIE,');
  Query.Script.Add('        :REFEDITEUR,');
  Query.Script.Add('        :NOMEDITEUR,');
  Query.Script.Add('        :REFCOLLECTION,');
  Query.Script.Add('        :NOMCOLLECTION');
  Query.Script.Add('  do begin');
  Query.Script.Add('    if (COUNTSERIE <> MAXSERIE) then begin');
  Query.Script.Add('      CURRENTTOME = 0;');
  Query.Script.Add('      for select distinct');
  Query.Script.Add('            UPPERTITRESERIE,');
  Query.Script.Add('            TITRESERIE,');
  Query.Script.Add('            TOME');
  Query.Script.Add('          from liste_tomes(:integrale) A inner join SERIES S on A.REFSERIE = S.REFSERIE and S.REFSERIE = :REFSERIE');
  Query.Script.Add('          order by TOME');
  Query.Script.Add('          into');
  Query.Script.Add('            :UPPERTITRESERIE,');
  Query.Script.Add('            :TITRESERIE,');
  Query.Script.Add('            :OWNEDTOME');
  Query.Script.Add('      do begin');
  Query.Script.Add('        CURRENTTOME = CURRENTTOME + 1;');
  Query.Script.Add('        while ((CURRENTTOME <> OWNEDTOME) and (CURRENTTOME < MAXSERIE)) do begin');
  Query.Script.Add('          TOME = CURRENTTOME;');
  Query.Script.Add('          suspend;');
  Query.Script.Add('          CURRENTTOME = CURRENTTOME + 1;');
  Query.Script.Add('        end');
  Query.Script.Add('      end');
  Query.Script.Add('    end');
  Query.Script.Add('  end');
  Query.Script.Add('end;');

  Query.ExecuteScript;
end;

initialization

RegisterFBUpdate('0.0.3.19', @MAJ0_0_3_19);

end.
