unit UMAJ1_2_3_25;

interface

implementation

uses JvUIB, Updates;

procedure MAJ1_2_3_25(Query: TJvUIBScript);
begin
  with Query do begin
    Script.Clear;

    Script.Add('ALTER PROCEDURE PROC_EMPRUNTS');
    Script.Add('RETURNS (');
    Script.Add('    ID_EDITION CHAR(38),');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(150),');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(150),');
    Script.Add('    PRETE SMALLINT,');
    Script.Add('    ID_EMPRUNTEUR CHAR(38),');
    Script.Add('    NOMEMPRUNTEUR VARCHAR(150),');
    Script.Add('    PRETEMPRUNT SMALLINT,');
    Script.Add('    DATEEMPRUNT TIMESTAMP)');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  EXIT;');
    Script.Add('END;');

    Script.Add('DROP VIEW VW_LISTE_GENRES_ALBUMS;');
    Script.Add('DROP VIEW VW_LISTE_EDITEURS_ALBUMS;');
    Script.Add('DROP VIEW VW_LISTE_EDITEURS_ACHATALBUMS;');
    Script.Add('DROP VIEW VW_LISTE_COLLECTIONS_ALBUMS;');
    Script.Add('DROP VIEW VW_EMPRUNTS;');
    Script.Add('DROP VIEW VW_LISTE_ALBUMS;');

    Script.Add('CREATE VIEW VW_LISTE_ALBUMS(');
    Script.Add('    ID_ALBUM,');
    Script.Add('    TITREALBUM,');
    Script.Add('    TOME,');
    Script.Add('    TOMEDEBUT,');
    Script.Add('    TOMEFIN,');
    Script.Add('    HORSSERIE,');
    Script.Add('    INTEGRALE,');
    Script.Add('    MOISPARUTION,');
    Script.Add('    ANNEEPARUTION,');
    Script.Add('    ID_SERIE,');
    Script.Add('    TITRESERIE,');
    Script.Add('    UPPERTITREALBUM,');
    Script.Add('    UPPERTITRESERIE,');
    Script.Add('    ACHAT,');
    Script.Add('    COMPLET,');
    Script.Add('    initialetitrealbum,');
    Script.Add('    initialetitreserie)');
    Script.Add('AS');
    Script.Add('select a.ID_ALBUM,');
    Script.Add('       a.TITREALBUM,');
    Script.Add('       a.TOME,');
    Script.Add('       a.TOMEDEBUT,');
    Script.Add('       a.TOMEFIN,');
    Script.Add('       a.HORSSERIE,');
    Script.Add('       a.INTEGRALE,');
    Script.Add('       a.MOISPARUTION,');
    Script.Add('       a.ANNEEPARUTION,');
    Script.Add('       a.ID_SERIE,');
    Script.Add('       s.TITRESERIE,');
    Script.Add('       a.UPPERTITREALBUM,');
    Script.Add('       s.UPPERTITRESERIE,');
    Script.Add('       a.ACHAT,');
    Script.Add('       a.COMPLET,');
    Script.Add('       COALESCE(a.INITIALETITREALBUM, s.INITIALETITRESERIE),');
    Script.Add('       s.INITIALETITRESERIE');
    Script.Add('FROM ALBUMS a LEFT JOIN SERIES s ON s.ID_SERIE = a.id_serie;');

    Script.Add('CREATE VIEW VW_EMPRUNTS(');
    Script.Add('    ID_STATUT,');
    Script.Add('    ID_EDITION,');
    Script.Add('    ID_ALBUM,');
    Script.Add('    TITREALBUM,');
    Script.Add('    UPPERTITREALBUM,');
    Script.Add('    ID_SERIE,');
    Script.Add('    TOME,');
    Script.Add('    INTEGRALE,');
    Script.Add('    TOMEDEBUT,');
    Script.Add('    TOMEFIN,');
    Script.Add('    HORSSERIE,');
    Script.Add('    TITRESERIE,');
    Script.Add('    ID_EDITEUR,');
    Script.Add('    NOMEDITEUR,');
    Script.Add('    ID_COLLECTION,');
    Script.Add('    NOMCOLLECTION,');
    Script.Add('    PRETE,');
    Script.Add('    ANNEEEDITION,');
    Script.Add('    ISBN,');
    Script.Add('    ID_EMPRUNTEUR,');
    Script.Add('    NOMEMPRUNTEUR,');
    Script.Add('    PRETEMPRUNT,');
    Script.Add('    DATEEMPRUNT)');
    Script.Add('AS');
    Script.Add('SELECT S.id_statut,');
    Script.Add('       Ed.ID_EDITION,');
    Script.Add('       A.ID_ALBUM,');
    Script.Add('       A.titrealbum,');
    Script.Add('       A.uppertitrealbum,');
    Script.Add('       A.id_serie,');
    Script.Add('       A.Tome,');
    Script.Add('       A.Integrale,');
    Script.Add('       A.TomeDebut,');
    Script.Add('       A.TomeFin,');
    Script.Add('       A.HorsSerie,');
    Script.Add('       A.titreserie,');
    Script.Add('       E.ID_EDITEUR,');
    Script.Add('       E.NomEditeur,');
    Script.Add('       C.ID_COLLECTION,');
    Script.Add('       C.NomCollection,');
    Script.Add('       Ed.prete,');
    Script.Add('       Ed.AnneeEdition,');
    Script.Add('       Ed.ISBN,');
    Script.Add('       Em.ID_EMPRUNTEUR,');
    Script.Add('       Em.NomEmprunteur,');
    Script.Add('       S.PretEmprunt,');
    Script.Add('       S.DateEmprunt');
    Script.Add('FROM VW_LISTE_ALBUMS A');
    Script.Add('  INNER JOIN EDITIONS Ed ON A.ID_ALBUM = Ed.id_album');
    Script.Add('  INNER JOIN EDITEURS e ON e.ID_EDITEUR = ed.id_editeur');
    Script.Add('  LEFT JOIN COLLECTIONS C ON C.ID_COLLECTION = ed.id_collection');
    Script.Add('  INNER JOIN STATUT S ON Ed.ID_EDITION = S.id_edition');
    Script.Add('  INNER JOIN EMPRUNTEURS Em ON Em.ID_EMPRUNTEUR = S.id_emprunteur;');

    Script.Add('CREATE VIEW VW_LISTE_COLLECTIONS_ALBUMS(');
    Script.Add('    ID_ALBUM,');
    Script.Add('    TITREALBUM,');
    Script.Add('    TOME,');
    Script.Add('    TOMEDEBUT,');
    Script.Add('    TOMEFIN,');
    Script.Add('    HORSSERIE,');
    Script.Add('    INTEGRALE,');
    Script.Add('    MOISPARUTION,');
    Script.Add('    ANNEEPARUTION,');
    Script.Add('    ID_SERIE,');
    Script.Add('    TITRESERIE,');
    Script.Add('    UPPERTITREALBUM,');
    Script.Add('    ID_COLLECTION,');
    Script.Add('    NOMCOLLECTION,');
    Script.Add('    UPPERNOMCOLLECTION,');
    Script.Add('    UPPERTITRESERIE,');
    Script.Add('    ACHAT,');
    Script.Add('    COMPLET)');
    Script.Add('AS');
    Script.Add('select a.ID_ALBUM,');
    Script.Add('       a.TITREALBUM,');
    Script.Add('       a.TOME,');
    Script.Add('       a.TOMEDEBUT,');
    Script.Add('       a.TOMEFIN,');
    Script.Add('       a.HORSSERIE,');
    Script.Add('       a.INTEGRALE,');
    Script.Add('       a.MOISPARUTION,');
    Script.Add('       a.ANNEEPARUTION,');
    Script.Add('       a.ID_SERIE,');
    Script.Add('       a.TITRESERIE,');
    Script.Add('       a.UPPERTITREALBUM,');
    Script.Add('       c.ID_COLLECTION,');
    Script.Add('       c.NOMCOLLECTION,');
    Script.Add('       c.UPPERNOMCOLLECTION,');
    Script.Add('       a.UPPERTITRESERIE,');
    Script.Add('       a.ACHAT,');
    Script.Add('       a.COMPLET');
    Script.Add('FROM VW_LISTE_ALBUMS a LEFT JOIN EDITIONS e ON e.id_album = a.id_album');
    Script.Add('                       LEFT JOIN COLLECTIONS c ON e.id_collection = c.ID_COLLECTION;');

    Script.Add('CREATE VIEW VW_LISTE_EDITEURS_ACHATALBUMS(');
    Script.Add('    ID_ALBUM,');
    Script.Add('    TITREALBUM,');
    Script.Add('    TOME,');
    Script.Add('    TOMEDEBUT,');
    Script.Add('    TOMEFIN,');
    Script.Add('    HORSSERIE,');
    Script.Add('    INTEGRALE,');
    Script.Add('    MOISPARUTION,');
    Script.Add('    ANNEEPARUTION,');
    Script.Add('    ID_SERIE,');
    Script.Add('    TITRESERIE,');
    Script.Add('    UPPERTITREALBUM,');
    Script.Add('    ID_EDITEUR,');
    Script.Add('    NOMEDITEUR,');
    Script.Add('    UPPERNOMEDITEUR,');
    Script.Add('    UPPERTITRESERIE,');
    Script.Add('    ACHAT,');
    Script.Add('    COMPLET)');
    Script.Add('AS');
    Script.Add('select a.ID_ALBUM,');
    Script.Add('       a.TITREALBUM,');
    Script.Add('       a.TOME,');
    Script.Add('       a.TOMEDEBUT,');
    Script.Add('       a.TOMEFIN,');
    Script.Add('       a.HORSSERIE,');
    Script.Add('       a.INTEGRALE,');
    Script.Add('       a.MOISPARUTION,');
    Script.Add('       a.ANNEEPARUTION,');
    Script.Add('       a.ID_SERIE,');
    Script.Add('       a.TITRESERIE,');
    Script.Add('       a.UPPERTITREALBUM,');
    Script.Add('       e.ID_EDITEUR,');
    Script.Add('       e.NOMEDITEUR,');
    Script.Add('       e.UPPERNOMEDITEUR,');
    Script.Add('       a.UPPERTITRESERIE,');
    Script.Add('       a.ACHAT,');
    Script.Add('       a.COMPLET');
    Script.Add('FROM VW_LISTE_ALBUMS a LEFT JOIN SERIES s ON s.id_serie = a.id_serie');
    Script.Add('                       LEFT JOIN EDITEURS e ON e.ID_EDITEUR = s.id_editeur;');

    Script.Add('CREATE VIEW VW_LISTE_EDITEURS_ALBUMS(');
    Script.Add('    ID_ALBUM,');
    Script.Add('    TITREALBUM,');
    Script.Add('    TOME,');
    Script.Add('    TOMEDEBUT,');
    Script.Add('    TOMEFIN,');
    Script.Add('    HORSSERIE,');
    Script.Add('    INTEGRALE,');
    Script.Add('    MOISPARUTION,');
    Script.Add('    ANNEEPARUTION,');
    Script.Add('    ID_SERIE,');
    Script.Add('    TITRESERIE,');
    Script.Add('    UPPERTITREALBUM,');
    Script.Add('    ID_EDITEUR,');
    Script.Add('    NOMEDITEUR,');
    Script.Add('    UPPERNOMEDITEUR,');
    Script.Add('    UPPERTITRESERIE,');
    Script.Add('    ACHAT,');
    Script.Add('    COMPLET)');
    Script.Add('AS');
    Script.Add('select a.ID_ALBUM,');
    Script.Add('       a.TITREALBUM,');
    Script.Add('       a.TOME,');
    Script.Add('       a.TOMEDEBUT,');
    Script.Add('       a.TOMEFIN,');
    Script.Add('       a.HORSSERIE,');
    Script.Add('       a.INTEGRALE,');
    Script.Add('       a.MOISPARUTION,');
    Script.Add('       a.ANNEEPARUTION,');
    Script.Add('       a.ID_SERIE,');
    Script.Add('       a.TITRESERIE,');
    Script.Add('       a.UPPERTITREALBUM,');
    Script.Add('       e.ID_EDITEUR,');
    Script.Add('       e.NOMEDITEUR,');
    Script.Add('       e.UPPERNOMEDITEUR,');
    Script.Add('       a.UPPERTITRESERIE,');
    Script.Add('       a.ACHAT,');
    Script.Add('       a.COMPLET');
    Script.Add('FROM VW_LISTE_ALBUMS a LEFT JOIN EDITIONS ed ON ed.id_album = a.id_album');
    Script.Add('                       LEFT JOIN EDITEURS e ON e.ID_EDITEUR = ed.id_editeur;');

    Script.Add('CREATE VIEW VW_LISTE_GENRES_ALBUMS(');
    Script.Add('    ID_ALBUM,');
    Script.Add('    TITREALBUM,');
    Script.Add('    TOME,');
    Script.Add('    TOMEDEBUT,');
    Script.Add('    TOMEFIN,');
    Script.Add('    HORSSERIE,');
    Script.Add('    INTEGRALE,');
    Script.Add('    MOISPARUTION,');
    Script.Add('    ANNEEPARUTION,');
    Script.Add('    ID_SERIE,');
    Script.Add('    TITRESERIE,');
    Script.Add('    UPPERTITREALBUM,');
    Script.Add('    ID_GENRE,');
    Script.Add('    GENRE,');
    Script.Add('    UPPERGENRE,');
    Script.Add('    UPPERTITRESERIE,');
    Script.Add('    ACHAT,');
    Script.Add('    COMPLET)');
    Script.Add('AS');
    Script.Add('select a.ID_ALBUM,');
    Script.Add('       a.TITREALBUM,');
    Script.Add('       a.TOME,');
    Script.Add('       a.TOMEDEBUT,');
    Script.Add('       a.TOMEFIN,');
    Script.Add('       a.HORSSERIE,');
    Script.Add('       a.INTEGRALE,');
    Script.Add('       a.MOISPARUTION,');
    Script.Add('       a.ANNEEPARUTION,');
    Script.Add('       a.ID_SERIE,');
    Script.Add('       a.TITRESERIE,');
    Script.Add('       a.UPPERTITREALBUM,');
    Script.Add('       g.ID_GENRE,');
    Script.Add('       g.GENRE,');
    Script.Add('       g.UPPERGENRE,');
    Script.Add('       a.UPPERTITRESERIE,');
    Script.Add('       a.ACHAT,');
    Script.Add('       a.COMPLET');
    Script.Add('FROM VW_LISTE_ALBUMS a LEFT JOIN GENRESERIES gs ON gs.id_serie = a.id_serie');
    Script.Add('                       LEFT JOIN GENRES g ON gs.id_genre = g.ID_GENRE;');

    Script.Add('ALTER PROCEDURE PROC_EMPRUNTS');
    Script.Add('RETURNS (');
    Script.Add('    ID_EDITION CHAR(38),');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(150),');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(150),');
    Script.Add('    PRETE SMALLINT,');
    Script.Add('    ID_EMPRUNTEUR CHAR(38),');
    Script.Add('    NOMEMPRUNTEUR VARCHAR(150),');
    Script.Add('    PRETEMPRUNT SMALLINT,');
    Script.Add('    DATEEMPRUNT TIMESTAMP)');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  FOR SELECT Ed.ID_EDITION,');
    Script.Add('             A.ID_ALBUM,');
    Script.Add('             A.titrealbum,');
    Script.Add('             A.id_serie,');
    Script.Add('             A.titreserie,');
    Script.Add('             Ed.prete,');
    Script.Add('             E.ID_EMPRUNTEUR,');
    Script.Add('             E.NomEmprunteur,');
    Script.Add('             S.PretEmprunt,');
    Script.Add('             S.DateEmprunt');
    Script.Add('      FROM VW_LISTE_ALBUMS A');
    Script.Add('        INNER JOIN EDITIONS Ed ON A.ID_ALBUM = Ed.id_album');
    Script.Add('        INNER JOIN STATUT S ON Ed.ID_EDITION = S.id_edition');
    Script.Add('        INNER JOIN EMPRUNTEURS E ON E.ID_EMPRUNTEUR = S.id_emprunteur');
    Script.Add('      ORDER BY S.DateEmprunt DESC');
    Script.Add('      INTO :ID_EDITION,');
    Script.Add('           :ID_ALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :PRETE,');
    Script.Add('           :ID_Emprunteur,');
    Script.Add('           :NomEmprunteur,');
    Script.Add('           :PretEmprunt,');
    Script.Add('           :DateEmprunt');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_INITIALE (');
    Script.Add('    initiale char(1),');
    Script.Add('    filtre varchar(125))');
    Script.Add('returns (');
    Script.Add('    id_album char(38),');
    Script.Add('    titrealbum varchar(150),');
    Script.Add('    tome smallint,');
    Script.Add('    tomedebut smallint,');
    Script.Add('    tomefin smallint,');
    Script.Add('    horsserie smallint,');
    Script.Add('    integrale smallint,');
    Script.Add('    moisparution smallint,');
    Script.Add('    anneeparution smallint,');
    Script.Add('    id_serie char(38),');
    Script.Add('    titreserie varchar(150),');
    Script.Add('    achat smallint,');
    Script.Add('    complet integer)');
    Script.Add('as');
    Script.Add('declare variable swhere varchar(133);');
    Script.Add('BEGIN');
    Script.Add('  swhere = '''';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = '' and '' || filtre || '' '';');
    Script.Add('  FOR execute statement');
    Script.Add('     ''SELECT a.ID_ALBUM,');
    Script.Add('             a.TITREALBUM,');
    Script.Add('             a.TOME,');
    Script.Add('             a.TOMEDEBUT,');
    Script.Add('             a.TOMEFIN,');
    Script.Add('             a.HORSSERIE,');
    Script.Add('             a.INTEGRALE,');
    Script.Add('             a.MOISPARUTION,');
    Script.Add('             a.ANNEEPARUTION,');
    Script.Add('             a.ID_SERIE,');
    Script.Add('             s.TITRESERIE,');
    Script.Add('             a.ACHAT,');
    Script.Add('             a.COMPLET');
    Script.Add('      FROM ALBUMS a LEFT JOIN SERIES s ON s.ID_SERIE = a.id_serie');
    Script.Add('      WHERE coalesce(a.initialetitrealbum, s.initialetitreserie) = '''''' ||: INITIALE || '''''' '' || swhere ||');
    Script.Add('      ''ORDER BY coalesce(UPPERTITREALBUM, UPPERTITRESERIE), HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST ''');
    Script.Add('      INTO :ID_ALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :MOISPARUTION,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :ACHAT,');
    Script.Add('           :COMPLET');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('end;');

    ExecuteScript;
  end;
end;

initialization
  RegisterUpdate('1.2.3.25', @MAJ1_2_3_25);

end.

