unit UMAJ1_2_3_3;

interface

implementation

uses JvUIB, Updates;

procedure PrepareProcedures(Query: TJvUIBScript);
begin
  with Query do begin
    Script.Clear;

    Script.Add('ALTER PROCEDURE ALBUMS_BY_ANNEE (');
    Script.Add('    ANNEE INTEGER,');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(200);');
    Script.Add('BEGIN');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_AUTEUR (');
    Script.Add('    ID_AUTEUR CHAR(38),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    METIER SMALLINT,');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(200);');
    Script.Add('BEGIN');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_COLLECTION (');
    Script.Add('    ID_COLLECTION CHAR(38),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(200);');
    Script.Add('BEGIN');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_EDITEUR (');
    Script.Add('    ID_EDITEUR CHAR(38),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(133);');
    Script.Add('BEGIN');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_GENRE (');
    Script.Add('    ID_GENRE CHAR(38),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(200);');
    Script.Add('BEGIN');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_INITIALE (');
    Script.Add('    INITIALE CHAR(1),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(133);');
    Script.Add('BEGIN');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_SERIE (');
    Script.Add('    IN_ID_SERIE CHAR(38),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(130);');
    Script.Add('BEGIN');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE ALBUMS_MANQUANTS (');
    Script.Add('    WITHINTEGRALE SMALLINT,');
    Script.Add('    WITHACHAT SMALLINT,');
    Script.Add('    IN_IDSERIE CHAR(38))');
    Script.Add('RETURNS (');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    COUNTSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    UPPERTITRESERIE VARCHAR(255),');
    Script.Add('    TOME INTEGER,');
    Script.Add('    ID_EDITEUR CHAR(38),');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    ID_COLLECTION CHAR(38),');
    Script.Add('    NOMCOLLECTION VARCHAR(50))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE MAXSERIE INTEGER;');
    Script.Add('DECLARE VARIABLE CURRENTTOME INTEGER;');
    Script.Add('DECLARE VARIABLE OWNEDTOME INTEGER;');
    Script.Add('DECLARE VARIABLE ACHAT SMALLINT;');
    Script.Add('DECLARE VARIABLE SUMACHAT INTEGER;');
    Script.Add('begin');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE CALCUL_ANNEE_SORTIE (');
    Script.Add('    WITHACHAT SMALLINT,');
    Script.Add('    IN_IDSERIE CHAR(38),');
    Script.Add('    SOMMEPONDEREE INTEGER,');
    Script.Add('    COMPTEALBUM INTEGER,');
    Script.Add('    MAXTOME INTEGER,');
    Script.Add('    MAXANNEE INTEGER,');
    Script.Add('    MAXMOIS INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    UPPERTITRESERIE VARCHAR(255),');
    Script.Add('    TOME INTEGER,');
    Script.Add('    ANNEEPARUTION INTEGER,');
    Script.Add('    MOISPARUTION INTEGER,');
    Script.Add('    ID_EDITEUR CHAR(38),');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    ID_COLLECTION CHAR(38),');
    Script.Add('    NOMCOLLECTION VARCHAR(50))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE MAXTOME2 INTEGER;');
    Script.Add('begin');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE PARABD_BY_SERIE (');
    Script.Add('    IN_ID_SERIE CHAR(38),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_PARABD CHAR(38),');
    Script.Add('    TITREPARABD VARCHAR(255),');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER,');
    Script.Add('    SCATEGORIE VARCHAR(50))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(130);');
    Script.Add('BEGIN');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE PREVISIONS_SORTIES (');
    Script.Add('    WITHACHAT SMALLINT,');
    Script.Add('    IN_ID_SERIE CHAR(38))');
    Script.Add('RETURNS (');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    UPPERTITRESERIE VARCHAR(255),');
    Script.Add('    TOME INTEGER,');
    Script.Add('    ANNEEPARUTION INTEGER,');
    Script.Add('    MOISPARUTION INTEGER,');
    Script.Add('    ID_EDITEUR CHAR(38),');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    ID_COLLECTION CHAR(38),');
    Script.Add('    NOMCOLLECTION VARCHAR(50))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE CURRENTIDSERIE CHAR(38) CHARACTER SET NONE;');
    Script.Add('DECLARE VARIABLE OLDIDSERIE CHAR(38) CHARACTER SET NONE;');
    Script.Add('DECLARE VARIABLE CURRENTTOME INTEGER;');
    Script.Add('DECLARE VARIABLE SOMMEPONDEREE INTEGER;');
    Script.Add('DECLARE VARIABLE COMPTEALBUM INTEGER;');
    Script.Add('DECLARE VARIABLE CURRENTANNEE INTEGER;');
    Script.Add('DECLARE VARIABLE CURRENTMOIS INTEGER;');
    Script.Add('DECLARE VARIABLE TOMEPRECEDENT INTEGER;');
    Script.Add('DECLARE VARIABLE ANNEEPRECEDENTE INTEGER;');
    Script.Add('DECLARE VARIABLE MOISPRECEDENT INTEGER;');
    Script.Add('DECLARE VARIABLE DIFFMOIS INTEGER;');
    Script.Add('begin');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE PROC_EMPRUNTS');
    Script.Add('RETURNS (');
    Script.Add('    ID_EDITION CHAR(38),');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    PRETE SMALLINT,');
    Script.Add('    ID_EMPRUNTEUR CHAR(38),');
    Script.Add('    NOMEMPRUNTEUR VARCHAR(150),');
    Script.Add('    PRETEMPRUNT SMALLINT,');
    Script.Add('    DATEEMPRUNT TIMESTAMP)');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  --');
    Script.Add('END;');

    Script.Add('ALTER PROCEDURE SERIES_ALBUMS (');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    COUNTSERIE INTEGER,');
    Script.Add('    ID_SERIE CHAR(38))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(132);');
    Script.Add('begin');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE SERIES_BY_INITIALE (');
    Script.Add('    INITIALE CHAR(1))');
    Script.Add('RETURNS (');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ID_EDITEUR CHAR(38),');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    ID_COLLECTION CHAR(38),');
    Script.Add('    NOMCOLLECTION VARCHAR(50))');
    Script.Add('AS');
    Script.Add('begin');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE SERIES_PARABD (');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    COUNTSERIE INTEGER,');
    Script.Add('    ID_SERIE CHAR(38))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(132);');
    Script.Add('begin');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER TRIGGER SERIES_DV');
    Script.Add('ACTIVE BEFORE INSERT OR UPDATE POSITION 0');
    Script.Add('AS');
    Script.Add('begin');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER TRIGGER PARABD_DV');
    Script.Add('ACTIVE BEFORE INSERT OR UPDATE POSITION 0');
    Script.Add('AS');
    Script.Add('begin');
    Script.Add('  --');
    Script.Add('end;');

    Script.Add('ALTER TRIGGER ALBUMS_DV');
    Script.Add('ACTIVE BEFORE INSERT OR UPDATE POSITION 0');
    Script.Add('AS');
    Script.Add('begin');
    Script.Add('  --');
    Script.Add('end;');

    ExecuteScript;
  end;
end;

procedure RestoreProcedures(Query: TJvUIBScript);
begin
  with Query do begin
    Script.Clear;

    Script.Add('ALTER PROCEDURE ALBUMS_BY_ANNEE (');
    Script.Add('    ANNEE INTEGER,');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(200);');
    Script.Add('BEGIN');
    Script.Add('  if (:Annee = -1) then sWhere = ''ANNEEPARUTION is null '';');
    Script.Add('                   else sWhere = ''ANNEEPARUTION = '' || :ANNEE || '' '';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = swhere || ''and '' || filtre || '' '';');
    Script.Add('  for execute statement');
    Script.Add('      ''SELECT ID_ALBUM,');
    Script.Add('             TITREALBUM,');
    Script.Add('             TOME,');
    Script.Add('             TOMEDEBUT,');
    Script.Add('             TOMEFIN,');
    Script.Add('             HORSSERIE,');
    Script.Add('             INTEGRALE,');
    Script.Add('             MOISPARUTION,');
    Script.Add('             ANNEEPARUTION,');
    Script.Add('             ID_SERIE,');
    Script.Add('             TITRESERIE,');
    Script.Add('             ACHAT,');
    Script.Add('             COMPLET');
    Script.Add('        FROM vw_liste_albums');
    Script.Add('        WHERE '' || :sWHERE ||');
    Script.Add('        ''ORDER BY UPPERTITREALBUM, UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST''');
    Script.Add('        INTO :ID_ALBUM,');
    Script.Add('             :TITREALBUM,');
    Script.Add('             :TOME,');
    Script.Add('             :TOMEDEBUT,');
    Script.Add('             :TOMEFIN,');
    Script.Add('             :HORSSERIE,');
    Script.Add('             :INTEGRALE,');
    Script.Add('             :MOISPARUTION,');
    Script.Add('             :ANNEEPARUTION,');
    Script.Add('             :ID_SERIE,');
    Script.Add('             :TITRESERIE,');
    Script.Add('             :ACHAT,');
    Script.Add('             :COMPLET');
    Script.Add('      DO');
    Script.Add('      BEGIN');
    Script.Add('        SUSPEND;');
    Script.Add('      END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE ALBUMS_BY_AUTEUR (');
    Script.Add('    ID_AUTEUR CHAR(38),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    METIER SMALLINT,');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(200);');
    Script.Add('BEGIN');
    Script.Add('  swhere = '''';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = ''and '' || filtre || '' '';');
    Script.Add('  FOR execute statement');
    Script.Add('     ''SELECT A.ID_ALBUM,');
    Script.Add('             A.TITREALBUM,');
    Script.Add('             A.TOME,');
    Script.Add('             A.TOMEDEBUT,');
    Script.Add('             A.TOMEFIN,');
    Script.Add('             A.HORSSERIE,');
    Script.Add('             A.INTEGRALE,');
    Script.Add('             A.MOISPARUTION,');
    Script.Add('             A.ANNEEPARUTION,');
    Script.Add('             A.ID_SERIE,');
    Script.Add('             A.TITRESERIE,');
    Script.Add('             AU.metier,');
    Script.Add('             A.ACHAT,');
    Script.Add('             A.COMPLET');
    Script.Add('      FROM vw_liste_albums A INNER JOIN auteurs au on a.ID_album = au.ID_album');
    Script.Add('      WHERE au.ID_personne = '''''' || :id_auteur || '''''' '' || swhere ||');
    Script.Add('      ''ORDER BY UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST, UPPERTITREALBUM, METIER''');
    Script.Add('      INTO :ID_ALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :MOISPARUTION,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :METIER,');
    Script.Add('           :ACHAT,');
    Script.Add('           :COMPLET');
    Script.Add('      DO');
    Script.Add('      BEGIN');
    Script.Add('        SUSPEND;');
    Script.Add('      END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE ALBUMS_BY_COLLECTION (');
    Script.Add('    ID_COLLECTION CHAR(38),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(200);');
    Script.Add('BEGIN');
    Script.Add('  if (:ID_COLLECTION = CAST('''' AS CHAR(38))) then sWhere = ''e.ID_COLLECTION is null '';');
    Script.Add('                           else sWhere = ''e.ID_COLLECTION = '''''' || :ID_COLLECTION || '''''' '';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = swhere || ''and '' || filtre || '' '';');
    Script.Add('  for execute statement');
    Script.Add('      ''SELECT a.ID_ALBUM,');
    Script.Add('             a.TITREALBUM,');
    Script.Add('             a.TOME,');
    Script.Add('             a.TOMEDEBUT,');
    Script.Add('             a.TOMEFIN,');
    Script.Add('             a.HORSSERIE,');
    Script.Add('             a.INTEGRALE,');
    Script.Add('             a.MOISPARUTION,');
    Script.Add('             a.ANNEEPARUTION,');
    Script.Add('             a.ID_SERIE,');
    Script.Add('             s.TITRESERIE,');
    Script.Add('             a.ACHAT,');
    Script.Add('             a.COMPLET');
    Script.Add('      from albums a left join editions e on a.ID_ALBUM = e.id_album');
    Script.Add('                    left join series s on a.id_serie = s.ID_SERIE');
    Script.Add('      WHERE '' || :sWHERE ||');
    Script.Add('     ''ORDER BY UPPERTITREALBUM, UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST''');
    Script.Add('      INTO :ID_ALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :MOISPARUTION,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :ACHAT,');
    Script.Add('           :COMPLET');
    Script.Add('      DO');
    Script.Add('      BEGIN');
    Script.Add('        SUSPEND;');
    Script.Add('      END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE ALBUMS_BY_EDITEUR (');
    Script.Add('    ID_EDITEUR CHAR(38),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(133);');
    Script.Add('BEGIN');
    Script.Add('  swhere = '''';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = ''and '' || filtre || '' '';');
    Script.Add('  FOR execute statement');
    Script.Add('     ''SELECT a.ID_ALBUM,');
    Script.Add('             a.TITREALBUM,');
    Script.Add('             a.TOME,');
    Script.Add('             a.TOMEDEBUT,');
    Script.Add('             a.TOMEFIN,');
    Script.Add('             a.HORSSERIE,');
    Script.Add('             a.INTEGRALE,');
    Script.Add('             a.MOISPARUTION,');
    Script.Add('             a.ANNEEPARUTION,');
    Script.Add('             a.ID_SERIE,');
    Script.Add('             s.TITRESERIE,');
    Script.Add('             a.ACHAT,');
    Script.Add('             a.COMPLET');
    Script.Add('      from albums a LEFT join editions e on a.ID_ALBUM = e.id_album');
    Script.Add('                    LEFT join series s on a.id_serie = s.ID_SERIE');
    Script.Add('      WHERE coalesce(e.id_editeur, -1) = '''''' || :id_editeur || '''''' '' || swhere ||');
    Script.Add('      ''ORDER BY UPPERTITREALBUM, UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST''');
    Script.Add('      INTO :ID_ALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :MOISPARUTION,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :ACHAT,');
    Script.Add('           :COMPLET');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE ALBUMS_BY_GENRE (');
    Script.Add('    ID_GENRE CHAR(38),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(200);');
    Script.Add('BEGIN');
    Script.Add('  if (:ID_Genre = CAST('''' AS CHAR(38))) then sWhere = ''ID_Genre is null '';');
    Script.Add('                      else sWhere = ''ID_genre = '''''' || :ID_genre || '''''' '';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = swhere || ''and '' || filtre || '' '';');
    Script.Add('  for execute statement');
    Script.Add('      ''SELECT ID_ALBUM,');
    Script.Add('             TITREALBUM,');
    Script.Add('             TOME,');
    Script.Add('             TOMEDEBUT,');
    Script.Add('             TOMEFIN,');
    Script.Add('             HORSSERIE,');
    Script.Add('             INTEGRALE,');
    Script.Add('             MOISPARUTION,');
    Script.Add('             ANNEEPARUTION,');
    Script.Add('             a.ID_SERIE,');
    Script.Add('             TITRESERIE,');
    Script.Add('             ACHAT,');
    Script.Add('             COMPLET');
    Script.Add('       FROM VW_LISTE_ALBUMS a LEFT JOIN GENRESERIES gs ON gs.id_serie = a.id_serie');
    Script.Add('                              LEFT JOIN GENRES g ON gs.id_genre = g.ID_GENRE');
    Script.Add('       WHERE '' || :sWHERE ||');
    Script.Add('      ''ORDER BY UPPERTITREALBUM, UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST''');
    Script.Add('       INTO :ID_ALBUM,');
    Script.Add('            :TITREALBUM,');
    Script.Add('            :TOME,');
    Script.Add('            :TOMEDEBUT,');
    Script.Add('            :TOMEFIN,');
    Script.Add('            :HORSSERIE,');
    Script.Add('            :INTEGRALE,');
    Script.Add('            :MOISPARUTION,');
    Script.Add('            :ANNEEPARUTION,');
    Script.Add('            :ID_SERIE,');
    Script.Add('            :TITRESERIE,');
    Script.Add('            :ACHAT,');
    Script.Add('            :COMPLET');
    Script.Add('      DO');
    Script.Add('      BEGIN');
    Script.Add('        SUSPEND;');
    Script.Add('      END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE ALBUMS_BY_INITIALE (');
    Script.Add('    INITIALE CHAR(1),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(133);');
    Script.Add('BEGIN');
    Script.Add('  swhere = '''';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = '' and '' || filtre || '' '';');
    Script.Add('  FOR execute statement');
    Script.Add('     ''SELECT a.ID_ALBUM,');
    Script.Add('             a.TITREALBUM,');
    Script.Add('             a.TOME,');
    Script.Add('             a.TOMEDEBUT,');
    Script.Add('             a.TOMEFIN,');
    Script.Add('             a.HORSSERIE,');
    Script.Add('             a.INTEGRALE,');
    Script.Add('             a.MOISPARUTION,');
    Script.Add('             a.ANNEEPARUTION,');
    Script.Add('             a.ID_SERIE,');
    Script.Add('             s.TITRESERIE,');
    Script.Add('             a.ACHAT,');
    Script.Add('             a.COMPLET');
    Script.Add('      FROM ALBUMS a LEFT JOIN SERIES s ON s.ID_SERIE = a.id_serie');
    Script.Add('      WHERE a.initialetitrealbum = '''''' ||: INITIALE || '''''' '' || swhere ||');
    Script.Add('      ''ORDER BY UPPERTITREALBUM, UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST ''');
    Script.Add('      INTO :ID_ALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :MOISPARUTION,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :ACHAT,');
    Script.Add('           :COMPLET');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE ALBUMS_BY_SERIE (');
    Script.Add('    IN_ID_SERIE CHAR(38),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    MOISPARUTION SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(130);');
    Script.Add('BEGIN');
    Script.Add('  if (:IN_ID_SERIE = CAST('''' AS CHAR(38))) then sWhere = ''ID_serie is null '';');
    Script.Add('                           else sWhere = ''ID_serie = '''''' || :IN_ID_SERIE || '''''' '';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = swhere || ''and '' || filtre || '' '';');
    Script.Add('  FOR execute statement');
    Script.Add('      ''SELECT ID_ALBUM,');
    Script.Add('             TITREALBUM,');
    Script.Add('             TOME,');
    Script.Add('             TOMEDEBUT,');
    Script.Add('             TOMEFIN,');
    Script.Add('             HORSSERIE,');
    Script.Add('             INTEGRALE,');
    Script.Add('             MOISPARUTION,');
    Script.Add('             ANNEEPARUTION,');
    Script.Add('             ID_SERIE,');
    Script.Add('             TITRESERIE,');
    Script.Add('             ACHAT,');
    Script.Add('             COMPLET');
    Script.Add('      FROM vw_liste_albums');
    Script.Add('      WHERE '' || :sWHERE ||');
    Script.Add('      ''ORDER BY HORSSERIE NULLS FIRST, INTEGRALE NULLS First, TOME NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST, UPPERTITREALBUM''');
    Script.Add('      INTO :ID_ALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :MOISPARUTION,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :ACHAT,');
    Script.Add('           :COMPLET');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE ALBUMS_MANQUANTS (');
    Script.Add('    WITHINTEGRALE SMALLINT,');
    Script.Add('    WITHACHAT SMALLINT,');
    Script.Add('    IN_IDSERIE CHAR(38))');
    Script.Add('RETURNS (');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    COUNTSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    UPPERTITRESERIE VARCHAR(255),');
    Script.Add('    TOME INTEGER,');
    Script.Add('    ID_EDITEUR CHAR(38),');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    ID_COLLECTION CHAR(38),');
    Script.Add('    NOMCOLLECTION VARCHAR(50))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE MAXSERIE INTEGER;');
    Script.Add('DECLARE VARIABLE CURRENTTOME INTEGER;');
    Script.Add('DECLARE VARIABLE OWNEDTOME INTEGER;');
    Script.Add('DECLARE VARIABLE ACHAT SMALLINT;');
    Script.Add('DECLARE VARIABLE SUMACHAT INTEGER;');
    Script.Add('begin');
    Script.Add('  if (WITHINTEGRALE is null) then WITHINTEGRALE = 1;');
    Script.Add('  if (WITHACHAT is null) then WITHACHAT = 1;');
    Script.Add('  for select');
    Script.Add('        A.id_serie,');
    Script.Add('        max(TOME),');
    Script.Add('        count(distinct TOME),');
    Script.Add('        cast(sum(ACHAT) as integer),');
    Script.Add('        S.id_editeur,');
    Script.Add('        NOMEDITEUR,');
    Script.Add('        S.id_collection,');
    Script.Add('        NOMCOLLECTION');
    Script.Add('      from liste_tomes(:WITHINTEGRALE, :in_idserie) A');
    Script.Add('         /* pas de left join: on cherche les manquants pour compléter les séries */');
    Script.Add('         inner join SERIES S on A.ID_SERIE = S.ID_SERIE');
    Script.Add('         left join EDITEURS E on S.ID_EDITEUR = E.ID_EDITEUR');
    Script.Add('         left join COLLECTIONS C on S.id_collection = C.ID_COLLECTION');
    Script.Add('      where S.SUIVREMANQUANTS = 1');
    Script.Add('      group by A.id_serie, UPPERTITRESERIE, UPPERNOMEDITEUR, UPPERNOMCOLLECTION,');
    Script.Add('               S.id_editeur, NOMEDITEUR, S.id_collection, NOMCOLLECTION');
    Script.Add('      order by UPPERTITRESERIE, UPPERNOMEDITEUR, UPPERNOMCOLLECTION');
    Script.Add('      into');
    Script.Add('        :ID_SERIE,');
    Script.Add('        :MAXSERIE,');
    Script.Add('        :COUNTSERIE,');
    Script.Add('        :SUMACHAT,');
    Script.Add('        :ID_EDITEUR,');
    Script.Add('        :NOMEDITEUR,');
    Script.Add('        :ID_COLLECTION,');
    Script.Add('        :NOMCOLLECTION');
    Script.Add('  do begin');
    Script.Add('    if (WITHACHAT = 0) then');
    Script.Add('      COUNTSERIE = COUNTSERIE - SUMACHAT;');
    Script.Add('    if (COUNTSERIE <> MAXSERIE) then begin');
    Script.Add('      CURRENTTOME = 0;');
    Script.Add('      for select distinct');
    Script.Add('            UPPERTITRESERIE,');
    Script.Add('            TITRESERIE,');
    Script.Add('            TOME,');
    Script.Add('            ACHAT');
    Script.Add('          from liste_tomes(:WITHINTEGRALE, :ID_SERIE) A inner join SERIES S on A.ID_SERIE = S.ID_SERIE');
    Script.Add('          order by TOME');
    Script.Add('          into');
    Script.Add('            :UPPERTITRESERIE,');
    Script.Add('            :TITRESERIE,');
    Script.Add('            :OWNEDTOME,');
    Script.Add('            :ACHAT');
    Script.Add('      do begin');
    Script.Add('        CURRENTTOME = CURRENTTOME + 1;');
    Script.Add('        while ((CURRENTTOME <> OWNEDTOME) and (CURRENTTOME < MAXSERIE)) do begin');
    Script.Add('          TOME = CURRENTTOME;');
    Script.Add('          suspend;');
    Script.Add('          CURRENTTOME = CURRENTTOME + 1;');
    Script.Add('        end');
    Script.Add('        if ((WITHACHAT = 0) AND (ACHAT = 1)) then begin');
    Script.Add('          TOME = OWNEDTOME;');
    Script.Add('          suspend;');
    Script.Add('        end');
    Script.Add('      end');
    Script.Add('    end');
    Script.Add('  end');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE CALCUL_ANNEE_SORTIE (');
    Script.Add('    WITHACHAT SMALLINT,');
    Script.Add('    IN_IDSERIE CHAR(38),');
    Script.Add('    SOMMEPONDEREE INTEGER,');
    Script.Add('    COMPTEALBUM INTEGER,');
    Script.Add('    MAXTOME INTEGER,');
    Script.Add('    MAXANNEE INTEGER,');
    Script.Add('    MAXMOIS INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    UPPERTITRESERIE VARCHAR(255),');
    Script.Add('    TOME INTEGER,');
    Script.Add('    ANNEEPARUTION INTEGER,');
    Script.Add('    MOISPARUTION INTEGER,');
    Script.Add('    ID_EDITEUR CHAR(38),');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    ID_COLLECTION CHAR(38),');
    Script.Add('    NOMCOLLECTION VARCHAR(50))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE MAXTOME2 INTEGER;');
    Script.Add('begin');
    Script.Add('  tome = maxtome + 1;');
    Script.Add('');
    Script.Add('  select cast(max(tomefin) + 1 as integer) from albums');
    Script.Add('  where horsserie = 0 and integrale = 1 and id_serie = :in_idserie and (:withachat = 1 or achat = 0)');
    Script.Add('  into');
    Script.Add('    :MAXTOME2;');
    Script.Add('');
    Script.Add('  if (maxtome2 > tome) then tome = maxtome2;');
    Script.Add('');
    Script.Add('  select s.ID_SERIE, s.TitreSerie, s.UpperTitreSerie, e.ID_EDITEUR, e.NomEditeur, c.ID_COLLECTION, c.NomCollection from');
    Script.Add('    series s left join editeurs e on e.ID_EDITEUR = s.id_editeur');
    Script.Add('             left join collections c on c.ID_COLLECTION = s.id_collection');
    Script.Add('  where s.ID_SERIE = :in_idserie');
    Script.Add('  into');
    Script.Add('    :ID_SERIE,');
    Script.Add('    :TITRESERIE,');
    Script.Add('    :UPPERTITRESERIE,');
    Script.Add('    :ID_EDITEUR,');
    Script.Add('    :NOMEDITEUR,');
    Script.Add('    :ID_COLLECTION,');
    Script.Add('    :NOMCOLLECTION;');
    Script.Add('');
    Script.Add('  if (maxmois is null) then begin');
    Script.Add('    ANNEEPARUTION = maxannee + ((tome - maxtome) * ((sommeponderee / 12) / comptealbum));');
    Script.Add('    MOISPARUTION = null;');
    Script.Add('  end else begin');
    Script.Add('    MOISPARUTION = maxmois + ((tome - maxtome) * (sommeponderee / comptealbum));');
    Script.Add('    ANNEEPARUTION = maxannee;');
    Script.Add('    while (MOISPARUTION > 12) do begin');
    Script.Add('      MOISPARUTION = MOISPARUTION - 12;');
    Script.Add('      ANNEEPARUTION = ANNEEPARUTION + 1;');
    Script.Add('    end');
    Script.Add('  end');
    Script.Add('  suspend;');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE PARABD_BY_SERIE (');
    Script.Add('    IN_ID_SERIE CHAR(38),');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    ID_PARABD CHAR(38),');
    Script.Add('    TITREPARABD VARCHAR(255),');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ACHAT SMALLINT,');
    Script.Add('    COMPLET INTEGER,');
    Script.Add('    SCATEGORIE VARCHAR(50))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(130);');
    Script.Add('BEGIN');
    Script.Add('  if (:IN_ID_SERIE = CAST('''' AS CHAR(38))) then sWhere = ''ID_serie is null '';');
    Script.Add('                           else sWhere = ''ID_serie = '''''' || :IN_ID_SERIE || '''''' '';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = swhere || ''and '' || filtre || '' '';');
    Script.Add('  FOR execute statement');
    Script.Add('      ''SELECT ID_PARABD,');
    Script.Add('             TITREPARABD,');
    Script.Add('             ID_PARABD,');
    Script.Add('             TITRESERIE,');
    Script.Add('             ACHAT,');
    Script.Add('             COMPLET,');
    Script.Add('             SCATEGORIE');
    Script.Add('      FROM vw_liste_PARABD');
    Script.Add('      WHERE '' || :sWHERE ||');
    Script.Add('      ''ORDER BY UPPERTITREPARABD''');
    Script.Add('      INTO :ID_PARABD,');
    Script.Add('           :TITREPARABD,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :ACHAT,');
    Script.Add('           :COMPLET,');
    Script.Add('           :SCATEGORIE');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE PREVISIONS_SORTIES (');
    Script.Add('    WITHACHAT SMALLINT,');
    Script.Add('    IN_ID_SERIE CHAR(38))');
    Script.Add('RETURNS (');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    UPPERTITRESERIE VARCHAR(255),');
    Script.Add('    TOME INTEGER,');
    Script.Add('    ANNEEPARUTION INTEGER,');
    Script.Add('    MOISPARUTION INTEGER,');
    Script.Add('    ID_EDITEUR CHAR(38),');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    ID_COLLECTION CHAR(38),');
    Script.Add('    NOMCOLLECTION VARCHAR(50))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE CURRENTIDSERIE CHAR(38) CHARACTER SET NONE;');
    Script.Add('DECLARE VARIABLE OLDIDSERIE CHAR(38) CHARACTER SET NONE;');
    Script.Add('DECLARE VARIABLE CURRENTTOME INTEGER;');
    Script.Add('DECLARE VARIABLE SOMMEPONDEREE INTEGER;');
    Script.Add('DECLARE VARIABLE COMPTEALBUM INTEGER;');
    Script.Add('DECLARE VARIABLE CURRENTANNEE INTEGER;');
    Script.Add('DECLARE VARIABLE CURRENTMOIS INTEGER;');
    Script.Add('DECLARE VARIABLE TOMEPRECEDENT INTEGER;');
    Script.Add('DECLARE VARIABLE ANNEEPRECEDENTE INTEGER;');
    Script.Add('DECLARE VARIABLE MOISPRECEDENT INTEGER;');
    Script.Add('DECLARE VARIABLE DIFFMOIS INTEGER;');
    Script.Add('begin');
    Script.Add('  if (withachat is Null) then withachat = 1;');
    Script.Add('  oldidserie = NULL;');
    Script.Add('  tomeprecedent = -1;');
    Script.Add('  anneeprecedente = -1;');
    Script.Add('  moisprecedent = null;');
    Script.Add('  for select TOME, ANNEEPARUTION, MOISPARUTION, s.ID_SERIE');
    Script.Add('      /* pas de left join: on calcul les prévisions de sorties des nouveautés des séries */');
    Script.Add('      from albums a inner join series s on s.ID_SERIE = a.id_serie');
    Script.Add('      where s.suivresorties = 1');
    Script.Add('            and a.horsserie = 0 and a.integrale = 0 and a.anneeparution is not null');
    Script.Add('            and (:in_id_serie is null or s.ID_SERIE = :in_id_serie)');
    Script.Add('            and (:withachat = 1 or achat = 0)');
    Script.Add('      order by s.ID_SERIE, TOME');
    Script.Add('      into :CURRENTTOME, :CURRENTANNEE, :CURRENTMOIS, :currentidserie');
    Script.Add('  do begin');
    Script.Add('    if (oldidserie is null or currentidserie <> oldidserie) then begin');
    Script.Add('');
    Script.Add('      if (oldidserie IS NOT NULL and comptealbum > 0) then begin');
    Script.Add('        select ID_SERIE, TITRESERIE, UPPERTITRESERIE,');
    Script.Add('               TOME, ANNEEPARUTION, MOISPARUTION,');
    Script.Add('               ID_EDITEUR, NOMEDITEUR,');
    Script.Add('               ID_COLLECTION, NOMCOLLECTION');
    Script.Add('        from CALCUL_ANNEE_SORTIE(:withachat, :oldidserie, :sommeponderee, :comptealbum, :tomeprecedent, :anneeprecedente, :moisprecedent)');
    Script.Add('        into :ID_SERIE, :TITRESERIE, :UPPERTITRESERIE,');
    Script.Add('             :TOME, :ANNEEPARUTION, :MOISPARUTION,');
    Script.Add('             :ID_EDITEUR, :NOMEDITEUR,');
    Script.Add('             :ID_COLLECTION, :NOMCOLLECTION;');
    Script.Add('        suspend;');
    Script.Add('      end');
    Script.Add('');
    Script.Add('      oldidserie = currentidserie;');
    Script.Add('      sommeponderee = 0;');
    Script.Add('      comptealbum = 0;');
    Script.Add('      tomeprecedent = -1;');
    Script.Add('      anneeprecedente = -1;');
    Script.Add('      moisprecedent = -1;');
    Script.Add('    end');
    Script.Add('    if (tomeprecedent <> -1 and CURRENTTOME - TOMEPRECEDENT <> 0) then begin');
    Script.Add('      if (CURRENTMOIS is null or MOISPRECEDENT is null) then');
    Script.Add('        diffmois = 0;');
    Script.Add('      else');
    Script.Add('        diffmois = CURRENTMOIS - MOISPRECEDENT;');
    Script.Add('      /* non pondéré: sommeponderee = sommeponderee + (((CURRENTANNEE - ANNEEPRECEDENTE) * 12 + (COALESCE(CURRENTMOIS, 1) - COALESCE(MOISPRECEDENT, 1))) / (CURRENTTOME - TOMEPRECEDENT)); */');
    Script.Add('      sommeponderee = sommeponderee + (((CURRENTANNEE - ANNEEPRECEDENTE) * 12 + diffmois) / (CURRENTTOME - TOMEPRECEDENT)) * CURRENTTOME;');
    Script.Add('      /* non pondéré: comptealbum = comptealbum + 1;*/');
    Script.Add('      comptealbum = comptealbum + CURRENTTOME;');
    Script.Add('    end');
    Script.Add('    tomeprecedent = CURRENTTOME;');
    Script.Add('    anneeprecedente = CURRENTANNEE;');
    Script.Add('    moisprecedent = CURRENTMOIS;');
    Script.Add('  end');
    Script.Add('');
    Script.Add('  if (oldidserie IS NOT NULL and comptealbum > 0) then begin');
    Script.Add('    select ID_SERIE, TITRESERIE, UPPERTITRESERIE,');
    Script.Add('           TOME, ANNEEPARUTION, MOISPARUTION,');
    Script.Add('           ID_EDITEUR, NOMEDITEUR,');
    Script.Add('           ID_COLLECTION, NOMCOLLECTION');
    Script.Add('    from CALCUL_ANNEE_SORTIE(:withachat, :oldidserie, :sommeponderee, :comptealbum, :tomeprecedent, :anneeprecedente, :moisprecedent)');
    Script.Add('    into :ID_SERIE, :TITRESERIE, :UPPERTITRESERIE,');
    Script.Add('         :TOME, :ANNEEPARUTION, :MOISPARUTION,');
    Script.Add('         :ID_EDITEUR, :NOMEDITEUR,');
    Script.Add('         :ID_COLLECTION, :NOMCOLLECTION;');
    Script.Add('    suspend;');
    Script.Add('  end');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE PROC_EMPRUNTS');
    Script.Add('RETURNS (');
    Script.Add('    ID_EDITION CHAR(38),');
    Script.Add('    ID_ALBUM CHAR(38),');
    Script.Add('    TITREALBUM VARCHAR(255),');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    PRETE SMALLINT,');
    Script.Add('    ID_EMPRUNTEUR CHAR(38),');
    Script.Add('    NOMEMPRUNTEUR VARCHAR(150),');
    Script.Add('    PRETEMPRUNT SMALLINT,');
    Script.Add('    DATEEMPRUNT TIMESTAMP)');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  FOR SELECT Ed.ID_EDITION,');
    Script.Add('             A.ID_ALBUM,');
    Script.Add('             A.titrealbum,');
    Script.Add('             A.id_serie,');
    Script.Add('             A.titreserie,');
    Script.Add('             Ed.prete,');
    Script.Add('             E.ID_EMPRUNTEUR,');
    Script.Add('             E.NomEmprunteur,');
    Script.Add('             S.PretEmprunt,');
    Script.Add('             S.DateEmprunt');
    Script.Add('      FROM VW_LISTE_ALBUMS A');
    Script.Add('        INNER JOIN EDITIONS Ed ON A.ID_ALBUM = Ed.id_album');
    Script.Add('        INNER JOIN STATUT S ON Ed.ID_EDITION = S.id_edition');
    Script.Add('        INNER JOIN EMPRUNTEURS E ON E.ID_EMPRUNTEUR = S.id_emprunteur');
    Script.Add('      ORDER BY S.DateEmprunt DESC');
    Script.Add('      INTO :ID_EDITION,');
    Script.Add('           :ID_ALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :PRETE,');
    Script.Add('           :ID_Emprunteur,');
    Script.Add('           :NomEmprunteur,');
    Script.Add('           :PretEmprunt,');
    Script.Add('           :DateEmprunt');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('END;');
    
    Script.Add('ALTER PROCEDURE SERIES_ALBUMS (');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    COUNTSERIE INTEGER,');
    Script.Add('    ID_SERIE CHAR(38))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(132);');
    Script.Add('begin');
    Script.Add('  swhere = '''';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = ''AND '' || filtre;');
    Script.Add('');
    Script.Add('  for execute statement');
    Script.Add('     ''select');
    Script.Add('             CAST(''''-1'''' AS VARCHAR(150)),');
    Script.Add('             ID_Serie,');
    Script.Add('             Count(ID_ALBUM)');
    Script.Add('      from vw_liste_albums');
    Script.Add('      where TITRESerie is null '' || SWHERE ||');
    Script.Add('    '' group by UPPERTITRESERIE, TITRESerie, ID_Serie''');
    Script.Add('  into :TITRESerie,');
    Script.Add('       :ID_Serie,');
    Script.Add('       :countSerie');
    Script.Add('  do');
    Script.Add('    suspend;');
    Script.Add('');
    Script.Add('  for execute statement');
    Script.Add('     ''select');
    Script.Add('             TITRESerie,');
    Script.Add('             ID_Serie,');
    Script.Add('             Count(ID_ALBUM)');
    Script.Add('      from vw_liste_albums');
    Script.Add('      where TITRESerie is not null '' || SWHERE ||');
    Script.Add('    '' group by UPPERTITRESERIE, TITRESerie, ID_Serie''');
    Script.Add('  into :TITRESerie,');
    Script.Add('       :ID_Serie,');
    Script.Add('       :countSerie');
    Script.Add('  do');
    Script.Add('    suspend;');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE SERIES_BY_INITIALE (');
    Script.Add('    INITIALE CHAR(1))');
    Script.Add('RETURNS (');
    Script.Add('    ID_SERIE CHAR(38),');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    ID_EDITEUR CHAR(38),');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    ID_COLLECTION CHAR(38),');
    Script.Add('    NOMCOLLECTION VARCHAR(50))');
    Script.Add('AS');
    Script.Add('begin');
    Script.Add('  FOR SELECT ID_SERIE,');
    Script.Add('             TITRESERIE,');
    Script.Add('             S.ID_EDITEUR,');
    Script.Add('             NOMEDITEUR,');
    Script.Add('             S.ID_COLLECTION,');
    Script.Add('             NOMCOLLECTION');
    Script.Add('      FROM SERIES S LEFT JOIN EDITEURS E ON S.id_editeur = E.ID_EDITEUR');
    Script.Add('                    LEFT JOIN COLLECTIONS C ON S.id_collection = C.ID_COLLECTION');
    Script.Add('      WHERE INITIALETITRESERIE = :INITIALE');
    Script.Add('      ORDER BY UPPERTITRESERIE, UPPERNOMEDITEUR, UPPERNOMCOLLECTION');
    Script.Add('      INTO :ID_SERIE,');
    Script.Add('           :TITRESERIE,');
    Script.Add('           :ID_EDITEUR,');
    Script.Add('           :NOMEDITEUR,');
    Script.Add('           :ID_COLLECTION,');
    Script.Add('           :NOMCOLLECTION');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('end;');
    
    Script.Add('ALTER PROCEDURE SERIES_PARABD (');
    Script.Add('    FILTRE VARCHAR(125))');
    Script.Add('RETURNS (');
    Script.Add('    TITRESERIE VARCHAR(255),');
    Script.Add('    COUNTSERIE INTEGER,');
    Script.Add('    ID_SERIE CHAR(38))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(132);');
    Script.Add('begin');
    Script.Add('  swhere = '''';');
    Script.Add('  if (filtre is not null and filtre <> '''') then swhere = ''AND '' || filtre;');
    Script.Add('');
    Script.Add('  for execute statement');
    Script.Add('     ''select');
    Script.Add('             CAST(''''-1'''' AS VARCHAR(150)),');
    Script.Add('             ID_Serie,');
    Script.Add('             Count(ID_PARABD)');
    Script.Add('      from vw_liste_PARABD');
    Script.Add('      where TITRESerie is null '' || SWHERE ||');
    Script.Add('    '' group by UPPERTITRESERIE, TITRESerie, ID_Serie''');
    Script.Add('  into :TITRESerie,');
    Script.Add('       :ID_Serie,');
    Script.Add('       :countSerie');
    Script.Add('  do');
    Script.Add('    suspend;');
    Script.Add('');
    Script.Add('  for execute statement');
    Script.Add('     ''select');
    Script.Add('             TITRESerie,');
    Script.Add('             ID_Serie,');
    Script.Add('             Count(ID_PARABD)');
    Script.Add('      from vw_liste_PARABD');
    Script.Add('      where TITRESerie is not null '' || SWHERE ||');
    Script.Add('    '' group by UPPERTITRESERIE, TITRESerie, ID_Serie''');
    Script.Add('  into :TITRESerie,');
    Script.Add('       :ID_Serie,');
    Script.Add('       :countSerie');
    Script.Add('  do');
    Script.Add('    suspend;');
    Script.Add('end;');

    Script.Add('ALTER TRIGGER SERIES_DV');
    Script.Add('ACTIVE BEFORE INSERT OR UPDATE POSITION 0');
    Script.Add('AS');
    Script.Add('begin');
    Script.Add('  if (inserting or new.titreserie <> old.titreserie) then begin');
    Script.Add('    new.uppertitreserie = UDF_UPPER(new.titreserie);');
    Script.Add('    new.SoundexTitreSerie = UDF_SOUNDEX(new.TitreSerie, 1);');
    Script.Add('    select initiale from get_initiale(new.uppertitreserie) into new.initialetitreserie;');
    Script.Add('  end');
    Script.Add('  if (new.sujetserie is null) then');
    Script.Add('    new.UPPERsujetserie = null;');
    Script.Add('  else');
    Script.Add('    new.UPPERsujetserie = UDF_UPPERBLOB(new.sujetserie);');
    Script.Add('  if (new.remarquesserie is null) then');
    Script.Add('    new.UPPERRemarquesserie = null;');
    Script.Add('  else');
    Script.Add('    new.UPPERRemarquesserie = UDF_UPPERBLOB(new.remarquesserie);');
    Script.Add('end;');

    Script.Add('ALTER TRIGGER PARABD_DV');
    Script.Add('ACTIVE BEFORE INSERT OR UPDATE POSITION 0');
    Script.Add('AS');
    Script.Add('begin');
    Script.Add('  if (new.TitreParaBD is null) then begin');
    Script.Add('    new.UpperTitreParaBD = null;');
    Script.Add('    new.SoundexTitreParaBD = null;');
    Script.Add('    new.initialetitreParaBD = null;');
    Script.Add('  end else');
    Script.Add('  if (inserting or old.TitreParaBD is null or new.TitreParaBD <> old.TitreParaBD) then begin');
    Script.Add('    new.UpperTitrePARABD = UDF_UPPER(new.TitrePARABD);');
    Script.Add('    new.SoundexTitrePARABD = UDF_SOUNDEX(new.TitrePARABD, 1);');
    Script.Add('    select initiale from get_initiale(new.UpperTitrePARABD) into new.initialetitrePARABD;');
    Script.Add('  end');
    Script.Add('  if (new.description is null) then');
    Script.Add('    new.upperdescription = null;');
    Script.Add('  else');
    Script.Add('    new.upperdescription = UDF_UPPERBLOB(new.description);');
    Script.Add('end;');

    Script.Add('ALTER TRIGGER ALBUMS_DV');
    Script.Add('ACTIVE BEFORE INSERT OR UPDATE POSITION 0');
    Script.Add('AS');
    Script.Add('begin');
    Script.Add('  if (new.TitreAlbum is null) then begin');
    Script.Add('    new.UpperTitreAlbum = null;');
    Script.Add('    new.SoundexTitreAlbum = null;');
    Script.Add('    new.initialetitreAlbum = null;');
    Script.Add('  end else');
    Script.Add('  if (inserting or old.TitreAlbum is null or new.TitreAlbum <> old.TitreAlbum) then begin');
    Script.Add('    new.UpperTitreAlbum = UDF_UPPER(new.TitreAlbum);');
    Script.Add('    new.SoundexTitreAlbum = UDF_SOUNDEX(new.TitreAlbum, 1);');
    Script.Add('    select initiale from get_initiale(new.UpperTitreAlbum) into new.initialetitreAlbum;');
    Script.Add('  end');
    Script.Add('  if (new.sujetalbum is null) then');
    Script.Add('    new.UPPERsujetAlbum = null;');
    Script.Add('  else');
    Script.Add('    new.UPPERsujetAlbum = UDF_UPPERBLOB(new.sujetalbum);');
    Script.Add('  if (new.remarquesalbum is null) then');
    Script.Add('    new.UPPERRemarquesAlbum = null;');
    Script.Add('  else');
    Script.Add('    new.UPPERRemarquesAlbum = UDF_UPPERBLOB(new.remarquesalbum);');
    Script.Add('end;');

    ExecuteScript;
  end;
end;

procedure MAJ1_2_3_3(Query: TJvUIBScript);
begin
  PrepareProcedures(Query);
  with Query do begin
    Script.Clear;

    Script.Add('ALTER TABLE SERIES ALTER TITRESERIE TYPE VARCHAR(255), ALTER UPPERTITRESERIE TYPE VARCHAR(255);');

    Script.Add('DROP INDEX ALBUMS_IDX3;');
    Script.Add('ALTER TABLE ALBUMS ALTER TITREALBUM TYPE VARCHAR(255), ALTER UPPERTITREALBUM TYPE VARCHAR(255);');

    Script.Add('ALTER TABLE PARABD ALTER TITREPARABD TYPE VARCHAR(255), ALTER UPPERTITREPARABD TYPE VARCHAR(255);');

    ExecuteScript;
  end;
  RestoreProcedures(Query);
end;

initialization
  RegisterUpdate('1.2.3.3', @MAJ1_2_3_3);

end.

