exclude:
- /documentation/.*
- /libs/.*
- /text2table/.*
- /wallpepper/.*
- /bdtheque/android/.*
- /bdtheque/delphi/.*
- /bdtheque/bdppc/.*
- /bdtheque/drafts/.*
- /bdtheque/dummy/.*
- /bdtheque/java/.*

languages:
- php
- javascript
- typescript
