//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateStructureBDPPC.Properties {
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreateStructureBDPPC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO SERIES (ID_SERIES, REFSERIE, TITRESERIE, UPPERTITRESERIE, INITIALETITRESERIE, REFEDITEUR, REFCOLLECTION, TERMINEE, COMPLETE, SOUNDEXTITRESERIE, SITEWEB, DC_SERIES, DM_SERIES) VALUES (&apos;{79746417-0E7A-4E9E-95C8-E928333C4CCF}&apos;, 1, &apos;Lanfeust de Troy&apos;, &apos;LANFEUST DE TROY&apos;, &apos;L&apos;, 1, 16, 1, 0, &apos;459836&apos;, &apos;&apos;, &apos;2005-04-03 16:13:03&apos;, &apos;2005-04-03 16:13:04&apos;);
        ///INSERT INTO SERIES (ID_SERIES, REFSERIE, TITRESERIE, UPPERTITRESERIE, INITIALETITRESERIE, REFEDITEUR, REFCOLLECTION, TERMINEE, COMPLETE, SOUNDEXTITRESER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScriptData {
            get {
                return ResourceManager.GetString("ScriptData", resourceCulture);
            }
        }
    }
}
