unit UMAJ0_0_2_19;

interface

implementation

uses UIB, Updates;

procedure MAJ0_0_2_19(Query: TUIBScript);
begin
  Query.Script.Clear;

  Query.Script.Add('ALTER PROCEDURE PREVISIONS_SORTIES (');
  Query.Script.Add('    INTEGRAL SMALLINT)');
  Query.Script.Add('RETURNS (');
  Query.Script.Add('    REFSERIE INTEGER,');
  Query.Script.Add('    TITRESERIE VARCHAR(150),');
  Query.Script.Add('    UPPERTITRESERIE VARCHAR(150),');
  Query.Script.Add('    TOME INTEGER,');
  Query.Script.Add('    ANNEEPARUTION INTEGER,');
  Query.Script.Add('    REFEDITEUR INTEGER,');
  Query.Script.Add('    NOMEDITEUR VARCHAR(50),');
  Query.Script.Add('    REFCOLLECTION INTEGER,');
  Query.Script.Add('    NOMCOLLECTION VARCHAR(50))');
  Query.Script.Add('AS');
  Query.Script.Add('DECLARE VARIABLE CURRENTREFSERIE INTEGER;');
  Query.Script.Add('DECLARE VARIABLE OLDREFSERIE INTEGER;');
  Query.Script.Add('DECLARE VARIABLE CURRENTTOME INTEGER;');
  Query.Script.Add('DECLARE VARIABLE MAXTOME INTEGER;');
  Query.Script.Add('DECLARE VARIABLE MAXTOME2 INTEGER;');
  Query.Script.Add('DECLARE VARIABLE SOMMEPONDEREE INTEGER;');
  Query.Script.Add('DECLARE VARIABLE COMPTEALBUM INTEGER;');
  Query.Script.Add('DECLARE VARIABLE CURRENTANNEE INTEGER;');
  Query.Script.Add('DECLARE VARIABLE MAXANNEE INTEGER;');
  Query.Script.Add('DECLARE VARIABLE TOMEPRECEDENT INTEGER;');
  Query.Script.Add('DECLARE VARIABLE ANNEEPRECEDENTE INTEGER;');
  Query.Script.Add('begin');
  Query.Script.Add('  oldrefserie = -1;');
  Query.Script.Add('  tomeprecedent = -1;');
  Query.Script.Add('  anneeprecedente = -1;');
  Query.Script.Add('  for select TOME, ANNEEPARUTION, s.RefSerie from');
  Query.Script.Add('        albums a inner join series s on s.refserie = a.refserie');
  Query.Script.Add('        where (s.terminee is null or s.terminee <> 1)');
  Query.Script.Add('        and a.horsserie = 0 and a.integrale = 0 and a.anneeparution is not null');
  Query.Script.Add('        order by s.refserie, TOME');
  Query.Script.Add('        into');
  Query.Script.Add('          :CURRENTTOME,');
  Query.Script.Add('          :CURRENTANNEE,');
  Query.Script.Add('          :CURRENTREFSERIE');
  Query.Script.Add('  do begin');
  Query.Script.Add('    if (currentrefserie <> oldrefserie) then begin');
  Query.Script.Add('');
  Query.Script.Add('      if (oldrefserie <> -1 and comptealbum > 0) then begin');
  Query.Script.Add('        select MAX(TOME) + 1, MAX(ANNEEPARUTION) from albums');
  Query.Script.Add('        where horsserie = 0 and integrale = 0 and refserie = :oldrefserie');
  Query.Script.Add('        into');
  Query.Script.Add('          :TOME,');
  Query.Script.Add('          :MAXANNEE;');
  Query.Script.Add('');
  Query.Script.Add('        if (INTEGRAL = 1) then begin');
  Query.Script.Add('          select max(tomefin) + 1 from albums');
  Query.Script.Add('          where integrale = 1 and refserie = :oldrefserie');
  Query.Script.Add('          into');
  Query.Script.Add('            :MAXTOME2;');
  Query.Script.Add('');
  Query.Script.Add('          if (maxtome2 > tome) then tome = maxtome2;');
  Query.Script.Add('        end');
  Query.Script.Add('');
  Query.Script.Add('        select s.RefSerie, s.TitreSerie, s.UpperTitreSerie, e.RefEditeur, e.NomEditeur, c.RefCollection, c.NomCollection from');
  Query.Script.Add('          series s left join editeurs e on e.refediteur = s.refediteur');
  Query.Script.Add('                   left join collections c on c.refcollection = s.refcollection');
  Query.Script.Add('        where s.RefSerie = :oldrefserie');
  Query.Script.Add('        into');
  Query.Script.Add('          :REFSERIE,');
  Query.Script.Add('          :TITRESERIE,');
  Query.Script.Add('          :UPPERTITRESERIE,');
  Query.Script.Add('          :REFEDITEUR,');
  Query.Script.Add('          :NOMEDITEUR,');
  Query.Script.Add('          :REFCOLLECTION,');
  Query.Script.Add('          :NOMCOLLECTION;');
  Query.Script.Add('');
  Query.Script.Add('        ANNEEPARUTION = maxannee + ((tome - maxtome) * (sommeponderee / comptealbum));');
  Query.Script.Add('        suspend;');
  Query.Script.Add('      end');
  Query.Script.Add('');
  Query.Script.Add('      oldrefserie = currentrefserie;');
  Query.Script.Add('      sommeponderee = 0;');
  Query.Script.Add('      comptealbum = 0;');
  Query.Script.Add('      tomeprecedent = -1;');
  Query.Script.Add('      anneeprecedente = -1;');
  Query.Script.Add('    end');
  Query.Script.Add('    if (tomeprecedent <> -1) then begin');
  Query.Script.Add('      /* non pondéré: sommeponderee = sommeponderee + ((CURRENTANNEE - ANNEEPRECEDENTE) / (CURRENTTOME - TOMEPRECEDENT)); */');
  Query.Script.Add('      sommeponderee = sommeponderee + ((CURRENTANNEE - ANNEEPRECEDENTE) / (CURRENTTOME - TOMEPRECEDENT)) * CURRENTTOME;');
  Query.Script.Add('      /* non pondéré: comptealbum = comptealbum + 1;*/');
  Query.Script.Add('      comptealbum = comptealbum + CURRENTTOME;');
  Query.Script.Add('    end');
  Query.Script.Add('    tomeprecedent = CURRENTTOME;');
  Query.Script.Add('    anneeprecedente = CURRENTANNEE;');
  Query.Script.Add('    maxtome = CURRENTTOME;');
  Query.Script.Add('  end');
  Query.Script.Add('');
  Query.Script.Add('  if (oldrefserie <> -1 and comptealbum > 0) then begin');
  Query.Script.Add('    select MAX(TOME) + 1, MAX(ANNEEPARUTION) from albums');
  Query.Script.Add('    where horsserie = 0 and integrale = 0 and refserie = :oldrefserie');
  Query.Script.Add('    into');
  Query.Script.Add('      :TOME,');
  Query.Script.Add('      :MAXANNEE;');
  Query.Script.Add('');
  Query.Script.Add('    if (INTEGRAL = 1) then begin');
  Query.Script.Add('      select max(tomefin) + 1 from albums');
  Query.Script.Add('      where integrale = 1 and refserie = :oldrefserie');
  Query.Script.Add('      into');
  Query.Script.Add('        :MAXTOME2;');
  Query.Script.Add('');
  Query.Script.Add('      if (maxtome2 > tome) then tome = maxtome2;');
  Query.Script.Add('    end');
  Query.Script.Add('');
  Query.Script.Add('    select s.RefSerie, s.TitreSerie, s.UpperTitreSerie, e.RefEditeur, e.NomEditeur, c.RefCollection, c.NomCollection from');
  Query.Script.Add('      series s left join editeurs e on e.refediteur = s.refediteur');
  Query.Script.Add('               left join collections c on c.refcollection = s.refcollection');
  Query.Script.Add('    where s.RefSerie = :oldrefserie');
  Query.Script.Add('    into');
  Query.Script.Add('      :REFSERIE,');
  Query.Script.Add('      :TITRESERIE,');
  Query.Script.Add('      :UPPERTITRESERIE,');
  Query.Script.Add('      :REFEDITEUR,');
  Query.Script.Add('      :NOMEDITEUR,');
  Query.Script.Add('      :REFCOLLECTION,');
  Query.Script.Add('      :NOMCOLLECTION;');
  Query.Script.Add('');
  Query.Script.Add('    ANNEEPARUTION = maxannee + ((tome - maxtome) * (sommeponderee / comptealbum));');
  Query.Script.Add('    suspend;');
  Query.Script.Add('  end');
  Query.Script.Add('end;');
  Query.Script.Add('');
  Query.Script.Add('DROP VIEW VW_EMPRUNTS;');
  Query.Script.Add('');
  Query.Script.Add('CREATE VIEW VW_EMPRUNTS(');
  Query.Script.Add('    REFEDITION,');
  Query.Script.Add('    REFALBUM,');
  Query.Script.Add('    TITREALBUM,');
  Query.Script.Add('    UPPERTITREALBUM,');
  Query.Script.Add('    REFSERIE,');
  Query.Script.Add('    TOME,');
  Query.Script.Add('    INTEGRALE,');
  Query.Script.Add('    TOMEDEBUT,');
  Query.Script.Add('    TOMEFIN,');
  Query.Script.Add('    HORSSERIE,');
  Query.Script.Add('    TITRESERIE,');
  Query.Script.Add('    REFEDITEUR,');
  Query.Script.Add('    NOMEDITEUR,');
  Query.Script.Add('    REFCOLLECTION,');
  Query.Script.Add('    NOMCOLLECTION,');
  Query.Script.Add('    PRETE,');
  Query.Script.Add('    ANNEEEDITION,');
  Query.Script.Add('    ISBN,');
  Query.Script.Add('    REFEMPRUNTEUR,');
  Query.Script.Add('    NOMEMPRUNTEUR,');
  Query.Script.Add('    PRETEMPRUNT,');
  Query.Script.Add('    DATEEMPRUNT)');
  Query.Script.Add('AS');
  Query.Script.Add('SELECT Ed.refedition,');
  Query.Script.Add('       A.refalbum,');
  Query.Script.Add('       A.titrealbum,');
  Query.Script.Add('       A.uppertitrealbum,');
  Query.Script.Add('       A.refserie,');
  Query.Script.Add('       A.Tome,');
  Query.Script.Add('       A.Integrale,');
  Query.Script.Add('       A.TomeDebut,');
  Query.Script.Add('       A.TomeFin,');
  Query.Script.Add('       A.HorsSerie,');
  Query.Script.Add('       Se.titreserie,');
  Query.Script.Add('       E.RefEditeur,');
  Query.Script.Add('       E.NomEditeur,');
  Query.Script.Add('       C.RefCollection,');
  Query.Script.Add('       C.NomCollection,');
  Query.Script.Add('       Ed.prete,');
  Query.Script.Add('       Ed.AnneeEdition,');
  Query.Script.Add('       Ed.ISBN,');
  Query.Script.Add('       Em.RefEmprunteur,');
  Query.Script.Add('       Em.NomEmprunteur,');
  Query.Script.Add('       S.PretEmprunt,');
  Query.Script.Add('       S.DateEmprunt');
  Query.Script.Add('FROM ALBUMS A INNER JOIN EDITIONS Ed ON A.refalbum = Ed.refalbum');
  Query.Script.Add('              INNER JOIN EDITEURS e ON e.RefEditeur = ed.RefEditeur');
  Query.Script.Add('              LEFT JOIN COLLECTIONS C ON C.refcollection = ed.refcollection');
  Query.Script.Add('              INNER JOIN STATUT S ON Ed.RefEdition = S.RefEdition');
  Query.Script.Add('              INNER JOIN EMPRUNTEURS Em ON Em.RefEmprunteur = S.RefEmprunteur');
  Query.Script.Add('              INNER JOIN SERIES Se ON A.refserie = Se.refserie;');

  Query.ExecuteScript;
end;

initialization

RegisterFBUpdate('0.0.2.19', @MAJ0_0_2_19);

end.
