genre:
    pattern:  /
    defaults: { _controller: BDThequeDataModelBundle:Genre:index }

genre_show:
    pattern:  /{id}/show
    defaults: { _controller: BDThequeDataModelBundle:Genre:show }

genre_new:
    pattern:  /new
    defaults: { _controller: BDThequeDataModelBundle:Genre:new }

genre_create:
    pattern:  /create
    defaults: { _controller: BDThequeDataModelBundle:Genre:create }
    requirements: { _method: post }

genre_edit:
    pattern:  /{id}/edit
    defaults: { _controller: BDThequeDataModelBundle:Genre:edit }

genre_update:
    pattern:  /{id}/update
    defaults: { _controller: BDThequeDataModelBundle:Genre:update }
    requirements: { _method: post }

genre_delete:
    pattern:  /{id}/delete
    defaults: { _controller: BDThequeDataModelBundle:Genre:delete }
    requirements: { _method: post }
