unit UMAJ0_0_2_5;

interface

implementation

uses UIB, Updates;

procedure MAJ0_0_2_5(Query: TUIBScript);
begin
  with Query do begin
    Script.Clear;
    Script.Add('ALTER TABLE ALBUMS ADD TOMEDEBUT SMALLINT, ADD TOMEFIN SMALLINT;');
    Script.Add('alter table ALBUMS alter REFALBUM position 1,');
    Script.Add('                   alter TITREALBUM position 2,');
    Script.Add('                   alter ANNEEPARUTION position 3,');
    Script.Add('                   alter REFSERIE position 4,');
    Script.Add('                   alter TOME position 5,');
    Script.Add('                   alter TOMEDEBUT position 6,');
    Script.Add('                   alter TOMEFIN position 7,');
    Script.Add('                   alter HORSSERIE position 8,');
    Script.Add('                   alter INTEGRALE position 9,');
    Script.Add('                   alter SUJETALBUM position 10,');
    Script.Add('                   alter REMARQUESALBUM position 11,');
    Script.Add('                   alter TITREINITIALESALBUM position 12,');
    Script.Add('                   alter UPPERTITREALBUM position 13,');
    Script.Add('                   alter UPPERSUJETALBUM position 14,');
    Script.Add('                   alter UPPERREMARQUESALBUM position 15,');
    Script.Add('                   alter SOUNDEXTITREALBUM position 16,');
    Script.Add('                   alter INITIALETITREALBUM position 17;');

    Script.Add('ALTER PROCEDURE PREVISIONS_SORTIES(');
    Script.Add('    INTEGRAL SMALLINT)');
    Script.Add('RETURNS (');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150),');
    Script.Add('    UPPERTITRESERIE VARCHAR(150),');
    Script.Add('    TOME INTEGER,');
    Script.Add('    ANNEEPARUTION INTEGER,');
    Script.Add('    REFEDITEUR INTEGER,');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    REFCOLLECTION INTEGER,');
    Script.Add('    NOMCOLLECTION VARCHAR(50))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE CURRENTREFSERIE INTEGER;');
    Script.Add('DECLARE VARIABLE OLDREFSERIE INTEGER;');
    Script.Add('DECLARE VARIABLE CURRENTTOME INTEGER;');
    Script.Add('DECLARE VARIABLE MAXTOME INTEGER;');
    Script.Add('DECLARE VARIABLE MAXTOME2 INTEGER;');
    Script.Add('DECLARE VARIABLE SOMMEPONDEREE INTEGER;');
    Script.Add('DECLARE VARIABLE COMPTEALBUM INTEGER;');
    Script.Add('DECLARE VARIABLE CURRENTANNEE INTEGER;');
    Script.Add('DECLARE VARIABLE MAXANNEE INTEGER;');
    Script.Add('DECLARE VARIABLE TOMEPRECEDENT INTEGER;');
    Script.Add('DECLARE VARIABLE ANNEEPRECEDENTE INTEGER;');
    Script.Add('begin');
    Script.Add('  oldrefserie = -1;');
    Script.Add('  tomeprecedent = -1;');
    Script.Add('  anneeprecedente = -1;');
    Script.Add('  for select TOME, ANNEEPARUTION, s.RefSerie from');
    Script.Add('        albums a inner join series s on s.refserie = a.refserie');
    Script.Add('        where (s.terminee is null or s.terminee <> 1)');
    Script.Add('        and a.horsserie = 0 and a.integrale = 0 and a.anneeparution is not null');
    Script.Add('        order by s.refserie, TOME');
    Script.Add('        into');
    Script.Add('          :CURRENTTOME,');
    Script.Add('          :CURRENTANNEE,');
    Script.Add('          :CURRENTREFSERIE');
    Script.Add('  do begin');
    Script.Add('    if (currentrefserie <> oldrefserie) then begin');
    Script.Add('');
    Script.Add('      if (oldrefserie <> -1 and comptealbum > 0) then begin');
    Script.Add('        select MAX(TOME) + 1, MAX(ANNEEPARUTION) from albums');
    Script.Add('        where horsserie = 0 and integrale = 0 and refserie = :oldrefserie');
    Script.Add('        into');
    Script.Add('          :TOME,');
    Script.Add('          :MAXANNEE;');
    Script.Add('');
    Script.Add('        if (INTEGRAL = 1) then begin');
    Script.Add('          select max(tomefin) + 1 from albums');
    Script.Add('          where integrale = 1 and refserie = :oldrefserie');
    Script.Add('          into');
    Script.Add('            :MAXTOME2;');
    Script.Add('');
    Script.Add('          if (maxtome2 > tome) then tome = maxtome2;');
    Script.Add('        end');
    Script.Add('');
    Script.Add('        select s.RefSerie, s.TitreSerie, s.UpperTitreSerie, e.RefEditeur, e.NomEditeur, c.RefCollection, c.NomCollection from');
    Script.Add('          series s left join editeurs e on e.refediteur = s.refediteur');
    Script.Add('                   left join collections c on c.refcollection = s.refcollection');
    Script.Add('        where s.RefSerie = :oldrefserie');
    Script.Add('        into');
    Script.Add('          :REFSERIE,');
    Script.Add('          :TITRESERIE,');
    Script.Add('          :UPPERTITRESERIE,');
    Script.Add('          :REFEDITEUR,');
    Script.Add('          :NOMEDITEUR,');
    Script.Add('          :REFCOLLECTION,');
    Script.Add('          :NOMCOLLECTION;');
    Script.Add('');
    Script.Add('        ANNEEPARUTION = maxannee + ((tome - maxtome) * (sommeponderee / comptealbum));');
    Script.Add('        suspend;');
    Script.Add('      end');
    Script.Add('');
    Script.Add('      oldrefserie = currentrefserie;');
    Script.Add('      sommeponderee = 0;');
    Script.Add('      comptealbum = 0;');
    Script.Add('      tomeprecedent = -1;');
    Script.Add('      anneeprecedente = -1;');
    Script.Add('    end');
    Script.Add('    if (tomeprecedent <> -1) then begin');
    Script.Add('      /* non pondéré: sommeponderee = sommeponderee + ((CURRENTANNEE - ANNEEPRECEDENTE) / (CURRENTTOME - TOMEPRECEDENT)); */');
    Script.Add('      sommeponderee = sommeponderee + ((CURRENTANNEE - ANNEEPRECEDENTE) / (CURRENTTOME - TOMEPRECEDENT)) * CURRENTTOME;');
    Script.Add('      /* non pondéré: comptealbum = comptealbum + 1;*/');
    Script.Add('      comptealbum = comptealbum + CURRENTTOME;');
    Script.Add('    end');
    Script.Add('    tomeprecedent = CURRENTTOME;');
    Script.Add('    anneeprecedente = CURRENTANNEE;');
    Script.Add('    maxtome = CURRENTTOME;');
    Script.Add('  end');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_AUTEUR(');
    Script.Add('    REFAUTEUR INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    REFALBUM INTEGER,');
    Script.Add('    TITREALBUM VARCHAR(150),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150),');
    Script.Add('    METIER SMALLINT)');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  EXIT;');
    Script.Add('END;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_SERIE(');
    Script.Add('    SERIE INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    REFALBUM INTEGER,');
    Script.Add('    TITREALBUM VARCHAR(150),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150))');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  EXIT;');
    Script.Add('END;');

    Script.Add('ALTER PROCEDURE ANNEES_ALBUMS');
    Script.Add('RETURNS (');
    Script.Add('    ANNEEPARUTION INTEGER,');
    Script.Add('    COUNTANNEE INTEGER)');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  EXIT;');
    Script.Add('END;');

    Script.Add('ALTER PROCEDURE SERIES_ALBUMS');
    Script.Add('RETURNS (');
    Script.Add('    TITRESERIE VARCHAR(150),');
    Script.Add('    COUNTSERIE INTEGER,');
    Script.Add('    REFSERIE INTEGER)');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  EXIT;');
    Script.Add('END;');

    Script.Add('ALTER PROCEDURE COLLECTIONS_ALBUMS');
    Script.Add('RETURNS (');
    Script.Add('    NOMCOLLECTION VARCHAR(50),');
    Script.Add('    COUNTCOLLECTION INTEGER,');
    Script.Add('    REFCOLLECTION INTEGER)');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  EXIT;');
    Script.Add('END;');

    Script.Add('ALTER PROCEDURE EDITEURS_ALBUMS');
    Script.Add('RETURNS (');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    COUNTEDITEUR INTEGER,');
    Script.Add('    REFEDITEUR INTEGER)');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  EXIT;');
    Script.Add('END;');

    Script.Add('ALTER PROCEDURE GENRES_ALBUMS');
    Script.Add('RETURNS (');
    Script.Add('    GENRE VARCHAR(30),');
    Script.Add('    COUNTGENRE INTEGER,');
    Script.Add('    REFGENRE INTEGER)');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  EXIT;');
    Script.Add('END;');

    Script.Add('DROP VIEW VW_LISTE_GENRES_ALBUMS;');
    Script.Add('DROP VIEW VW_LISTE_EDITEURS_ALBUMS;');
    Script.Add('DROP VIEW VW_LISTE_COLLECTIONS_ALBUMS;');
    Script.Add('DROP VIEW VW_LISTE_ALBUMS;');

    Script.Add('CREATE VIEW VW_LISTE_ALBUMS(');
    Script.Add('    REFALBUM,');
    Script.Add('    TITREALBUM,');
    Script.Add('    TOME,');
    Script.Add('    TOMEDEBUT,');
    Script.Add('    TOMEFIN,');
    Script.Add('    HORSSERIE,');
    Script.Add('    INTEGRALE,');
    Script.Add('    ANNEEPARUTION,');
    Script.Add('    REFSERIE,');
    Script.Add('    TITRESERIE,');
    Script.Add('    UPPERTITREALBUM,');
    Script.Add('    UPPERTITRESERIE)');
    Script.Add('AS');
    Script.Add('select a.REFALBUM,');
    Script.Add('       a.TITREALBUM,');
    Script.Add('       a.TOME,');
    Script.Add('       a.TOMEDEBUT,');
    Script.Add('       a.TOMEFIN,');
    Script.Add('       a.HORSSERIE,');
    Script.Add('       a.INTEGRALE,');
    Script.Add('       a.ANNEEPARUTION,');
    Script.Add('       a.REFSERIE,');
    Script.Add('       s.TITRESERIE,');
    Script.Add('       a.UPPERTITREALBUM,');
    Script.Add('       s.UPPERTITRESERIE');
    Script.Add('FROM ALBUMS a INNER JOIN SERIES s ON s.refserie = a.refserie;');

    Script.Add('CREATE VIEW VW_LISTE_COLLECTIONS_ALBUMS(');
    Script.Add('    REFALBUM,');
    Script.Add('    TITREALBUM,');
    Script.Add('    TOME,');
    Script.Add('    TOMEDEBUT,');
    Script.Add('    TOMEFIN,');
    Script.Add('    HORSSERIE,');
    Script.Add('    INTEGRALE,');
    Script.Add('    ANNEEPARUTION,');
    Script.Add('    REFSERIE,');
    Script.Add('    TITRESERIE,');
    Script.Add('    UPPERTITREALBUM,');
    Script.Add('    REFCOLLECTION,');
    Script.Add('    NOMCOLLECTION,');
    Script.Add('    UPPERNOMCOLLECTION)');
    Script.Add('AS');
    Script.Add('select a.REFALBUM,');
    Script.Add('       a.TITREALBUM,');
    Script.Add('       a.TOME,');
    Script.Add('       a.TOMEDEBUT,');
    Script.Add('       a.TOMEFIN,');
    Script.Add('       a.HORSSERIE,');
    Script.Add('       a.INTEGRALE,');
    Script.Add('       a.ANNEEPARUTION,');
    Script.Add('       a.REFSERIE,');
    Script.Add('       a.TITRESERIE,');
    Script.Add('       a.UPPERTITREALBUM,');
    Script.Add('       c.REFCOLLECTION,');
    Script.Add('       c.NOMCOLLECTION,');
    Script.Add('       c.UPPERNOMCOLLECTION');
    Script.Add('FROM VW_LISTE_ALBUMS a LEFT JOIN EDITIONS e ON e.refalbum = a.refalbum');
    Script.Add('                       LEFT JOIN COLLECTIONS c ON e.refcollection = c.refcollection;');

    Script.Add('CREATE VIEW VW_LISTE_EDITEURS_ALBUMS(');
    Script.Add('    REFALBUM,');
    Script.Add('    TITREALBUM,');
    Script.Add('    TOME,');
    Script.Add('    TOMEDEBUT,');
    Script.Add('    TOMEFIN,');
    Script.Add('    HORSSERIE,');
    Script.Add('    INTEGRALE,');
    Script.Add('    ANNEEPARUTION,');
    Script.Add('    REFSERIE,');
    Script.Add('    TITRESERIE,');
    Script.Add('    UPPERTITREALBUM,');
    Script.Add('    REFEDITEUR,');
    Script.Add('    NOMEDITEUR,');
    Script.Add('    UPPERNOMEDITEUR)');
    Script.Add('AS');
    Script.Add('select a.REFALBUM,');
    Script.Add('       a.TITREALBUM,');
    Script.Add('       a.TOME,');
    Script.Add('       a.TOMEDEBUT,');
    Script.Add('       a.TOMEFIN,');
    Script.Add('       a.HORSSERIE,');
    Script.Add('       a.INTEGRALE,');
    Script.Add('       a.ANNEEPARUTION,');
    Script.Add('       a.REFSERIE,');
    Script.Add('       a.TITRESERIE,');
    Script.Add('       a.UPPERTITREALBUM,');
    Script.Add('       e.REFEDITEUR,');
    Script.Add('       e.NOMEDITEUR,');
    Script.Add('       e.UPPERNOMEDITEUR');
    Script.Add('FROM VW_LISTE_ALBUMS a LEFT JOIN EDITIONS ed ON ed.refalbum = a.refalbum');
    Script.Add('                       LEFT JOIN EDITEURS e ON e.refediteur = ed.refediteur;');

    Script.Add('CREATE VIEW VW_LISTE_GENRES_ALBUMS(');
    Script.Add('    REFALBUM,');
    Script.Add('    TITREALBUM,');
    Script.Add('    TOME,');
    Script.Add('    TOMEDEBUT,');
    Script.Add('    TOMEFIN,');
    Script.Add('    HORSSERIE,');
    Script.Add('    INTEGRALE,');
    Script.Add('    ANNEEPARUTION,');
    Script.Add('    REFSERIE,');
    Script.Add('    TITRESERIE,');
    Script.Add('    UPPERTITREALBUM,');
    Script.Add('    REFGENRE,');
    Script.Add('    GENRE,');
    Script.Add('    UPPERGENRE)');
    Script.Add('AS');
    Script.Add('select a.REFALBUM,');
    Script.Add('       a.TITREALBUM,');
    Script.Add('       a.TOME,');
    Script.Add('       a.TOMEDEBUT,');
    Script.Add('       a.TOMEFIN,');
    Script.Add('       a.HORSSERIE,');
    Script.Add('       a.INTEGRALE,');
    Script.Add('       a.ANNEEPARUTION,');
    Script.Add('       a.REFSERIE,');
    Script.Add('       a.TITRESERIE,');
    Script.Add('       a.UPPERTITREALBUM,');
    Script.Add('       g.REFGENRE,');
    Script.Add('       g.GENRE,');
    Script.Add('       g.UPPERGENRE');
    Script.Add('FROM VW_LISTE_ALBUMS a LEFT JOIN GENRESERIES gs ON gs.refserie = a.refserie');
    Script.Add('                       LEFT JOIN GENRES g ON gs.refgenre = g.refgenre;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_AUTEUR(');
    Script.Add('    REFAUTEUR INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    REFALBUM INTEGER,');
    Script.Add('    TITREALBUM VARCHAR(150),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150),');
    Script.Add('    METIER SMALLINT)');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  for SELECT A.REFALBUM,');
    Script.Add('             A.TITREALBUM,');
    Script.Add('             A.TOME,');
    Script.Add('             A.TOMEDEBUT,');
    Script.Add('             A.TOMEFIN,');
    Script.Add('             A.HORSSERIE,');
    Script.Add('             A.INTEGRALE,');
    Script.Add('             A.ANNEEPARUTION,');
    Script.Add('             A.REFSERIE,');
    Script.Add('             A.TITRESERIE,');
    Script.Add('             AU.metier');
    Script.Add('        FROM vw_liste_albums A INNER JOIN auteurs au on a.refalbum = au.refalbum');
    Script.Add('        WHERE au.refpersonne = :RefAuteur');
    Script.Add('        ORDER BY UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, ANNEEPARUTION NULLS FIRST, UPPERTITREALBUM, METIER');
    Script.Add('        INTO :REFALBUM,');
    Script.Add('             :TITREALBUM,');
    Script.Add('             :TOME,');
    Script.Add('             :TOMEDEBUT,');
    Script.Add('             :TOMEFIN,');
    Script.Add('             :HORSSERIE,');
    Script.Add('             :INTEGRALE,');
    Script.Add('             :ANNEEPARUTION,');
    Script.Add('             :REFSERIE,');
    Script.Add('             :TITRESERIE,');
    Script.Add('             :METIER');
    Script.Add('      DO');
    Script.Add('      BEGIN');
    Script.Add('        SUSPEND;');
    Script.Add('      END');
    Script.Add('END;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_SERIE(');
    Script.Add('    SERIE INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    REFALBUM INTEGER,');
    Script.Add('    TITREALBUM VARCHAR(150),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150))');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  FOR SELECT REFALBUM,');
    Script.Add('             TITREALBUM,');
    Script.Add('             TOME,');
    Script.Add('             TOMEDEBUT,');
    Script.Add('             TOMEFIN,');
    Script.Add('             HORSSERIE,');
    Script.Add('             INTEGRALE,');
    Script.Add('             ANNEEPARUTION,');
    Script.Add('             REFSERIE,');
    Script.Add('             TITRESERIE');
    Script.Add('      FROM vw_liste_albums');
    Script.Add('      WHERE refserie = :serie');
    Script.Add('      ORDER BY HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, ANNEEPARUTION NULLS FIRST, UPPERTITREALBUM');
    Script.Add('      INTO :REFALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :REFSERIE,');
    Script.Add('           :TITRESERIE');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('END;');

    Script.Add('ALTER PROCEDURE ANNEES_ALBUMS');
    Script.Add('RETURNS (');
    Script.Add('    ANNEEPARUTION INTEGER,');
    Script.Add('    COUNTANNEE INTEGER)');
    Script.Add('AS');
    Script.Add('begin');
    Script.Add('  for select');
    Script.Add('    -1,');
    Script.Add('    Count(REFALBUM)');
    Script.Add('  from vw_liste_albums');
    Script.Add('  where AnneeParution is null');
    Script.Add('  group by AnneeParution');
    Script.Add('  into :AnneeParution,');
    Script.Add('       :countannee');
    Script.Add('  do begin');
    Script.Add('    suspend;');
    Script.Add('  end');
    Script.Add('');
    Script.Add('  for select');
    Script.Add('    AnneeParution,');
    Script.Add('    Count(REFALBUM)');
    Script.Add('  from vw_liste_albums');
    Script.Add('  where AnneeParution is not null');
    Script.Add('  group by AnneeParution');
    Script.Add('  into :AnneeParution,');
    Script.Add('       :countannee');
    Script.Add('  do begin');
    Script.Add('    suspend;');
    Script.Add('  end');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE SERIES_ALBUMS');
    Script.Add('RETURNS (');
    Script.Add('    TITRESERIE VARCHAR(150),');
    Script.Add('    COUNTSERIE INTEGER,');
    Script.Add('    REFSERIE INTEGER)');
    Script.Add('AS');
    Script.Add('begin');
    Script.Add('  for select');
    Script.Add('    -1,');
    Script.Add('    RefSerie,');
    Script.Add('    Count(REFALBUM)');
    Script.Add('  from vw_liste_albums');
    Script.Add('  where TITRESerie is null');
    Script.Add('  group by UPPERTITRESERIE, TITRESerie, RefSerie');
    Script.Add('  into :TITRESerie,');
    Script.Add('       :RefSerie,');
    Script.Add('       :countSerie');
    Script.Add('  do begin');
    Script.Add('    suspend;');
    Script.Add('  end');
    Script.Add('');
    Script.Add('  for select');
    Script.Add('    TITRESerie,');
    Script.Add('    RefSerie,');
    Script.Add('    Count(REFALBUM)');
    Script.Add('  from vw_liste_albums');
    Script.Add('  where TITRESerie is not null');
    Script.Add('  group by UPPERTITRESERIE, TITRESerie, RefSerie');
    Script.Add('  into :TITRESerie,');
    Script.Add('       :RefSerie,');
    Script.Add('       :countSerie');
    Script.Add('  do begin');
    Script.Add('    suspend;');
    Script.Add('  end');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE COLLECTIONS_ALBUMS');
    Script.Add('RETURNS (');
    Script.Add('    NOMCOLLECTION VARCHAR(50),');
    Script.Add('    COUNTCOLLECTION INTEGER,');
    Script.Add('    REFCOLLECTION INTEGER)');
    Script.Add('AS');
    Script.Add('begin');
    Script.Add('  for select');
    Script.Add('    CAST(''-1'' AS VARCHAR(50)),');
    Script.Add('    Count(REFALBUM),');
    Script.Add('    -1');
    Script.Add('  from vw_liste_collections_albums');
    Script.Add('  where REFCOLLECTION is null');
    Script.Add('  group by uppernomcollection, nomCOLLECTION, refCOLLECTION');
    Script.Add('  into :nomCOLLECTION,');
    Script.Add('       :countCOLLECTION,');
    Script.Add('       :RefCOLLECTION');
    Script.Add('  do begin');
    Script.Add('    suspend;');
    Script.Add('  end');
    Script.Add('');
    Script.Add('  for select');
    Script.Add('    nomCOLLECTION,');
    Script.Add('    Count(REFALBUM),');
    Script.Add('    RefCOLLECTION');
    Script.Add('  from vw_liste_collections_albums');
    Script.Add('  where REFCOLLECTION is not null');
    Script.Add('  group by uppernomcollection, nomCOLLECTION, refCOLLECTION');
    Script.Add('  into :nomCOLLECTION,');
    Script.Add('       :countCOLLECTION,');
    Script.Add('       :RefCOLLECTION');
    Script.Add('  do begin');
    Script.Add('    suspend;');
    Script.Add('  end');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE EDITEURS_ALBUMS');
    Script.Add('RETURNS (');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    COUNTEDITEUR INTEGER,');
    Script.Add('    REFEDITEUR INTEGER)');
    Script.Add('AS');
    Script.Add('begin');
    Script.Add('  for select');
    Script.Add('    CAST(''-1'' AS VARCHAR(50)),');
    Script.Add('    Count(REFALBUM),');
    Script.Add('    RefEditeur');
    Script.Add('  from vw_liste_editeurs_albums');
    Script.Add('  where REFEDITEUR is null');
    Script.Add('  group by uppernomediteur, nomediteur, refediteur');
    Script.Add('  into :nomediteur,');
    Script.Add('       :countediteur,');
    Script.Add('       :RefEditeur');
    Script.Add('  do begin');
    Script.Add('    suspend;');
    Script.Add('  end');
    Script.Add('');
    Script.Add('  for select');
    Script.Add('    nomediteur,');
    Script.Add('    Count(REFALBUM),');
    Script.Add('    RefEditeur');
    Script.Add('  from vw_liste_editeurs_albums');
    Script.Add('  where REFEDITEUR is not null');
    Script.Add('  group by uppernomediteur, nomediteur, refediteur');
    Script.Add('  into :nomediteur,');
    Script.Add('       :countediteur,');
    Script.Add('       :RefEditeur');
    Script.Add('  do begin');
    Script.Add('    suspend;');
    Script.Add('  end');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE GENRES_ALBUMS');
    Script.Add('RETURNS (');
    Script.Add('    GENRE VARCHAR(30),');
    Script.Add('    COUNTGENRE INTEGER,');
    Script.Add('    REFGENRE INTEGER)');
    Script.Add('AS');
    Script.Add('begin');
    Script.Add('  for select');
    Script.Add('    CAST(''-1'' AS VARCHAR(30)),');
    Script.Add('    Count(REFALBUM),');
    Script.Add('    -1');
    Script.Add('  from vw_liste_genres_albums');
    Script.Add('  where REFGENRE is null');
    Script.Add('  group by uppergenre, Genre, refgenre');
    Script.Add('  into :genre,');
    Script.Add('       :countgenre,');
    Script.Add('       :refgenre');
    Script.Add('  do begin');
    Script.Add('    suspend;');
    Script.Add('  end');
    Script.Add('');
    Script.Add('  for select');
    Script.Add('    Genre,');
    Script.Add('    Count(REFALBUM),');
    Script.Add('    refgenre');
    Script.Add('  from vw_liste_genres_albums');
    Script.Add('  where REFGENRE is not null');
    Script.Add('  group by uppergenre, Genre, refgenre');
    Script.Add('  into :genre,');
    Script.Add('       :countgenre,');
    Script.Add('       :refgenre');
    Script.Add('  do begin');
    Script.Add('    suspend;');
    Script.Add('  end');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_ANNEE (');
    Script.Add('    ANNEE INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    REFALBUM INTEGER,');
    Script.Add('    TITREALBUM VARCHAR(150),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(25);');
    Script.Add('BEGIN');
    Script.Add('  if (:Annee = -1) then sWhere = ''ANNEEPARUTION is null '';');
    Script.Add('                   else sWhere = ''ANNEEPARUTION = '' || :ANNEE;');
    Script.Add('  for execute statement');
    Script.Add('      ''SELECT REFALBUM,');
    Script.Add('             TITREALBUM,');
    Script.Add('             TOME,');
    Script.Add('             TOMEDEBUT,');
    Script.Add('             TOMEFIN,');
    Script.Add('             HORSSERIE,');
    Script.Add('             INTEGRALE,');
    Script.Add('             ANNEEPARUTION,');
    Script.Add('             REFSERIE,');
    Script.Add('             TITRESERIE');
    Script.Add('        FROM vw_liste_albums');
    Script.Add('        WHERE '' || :sWHERE ||');
    Script.Add('        ''ORDER BY UPPERTITREALBUM, UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST''');
    Script.Add('        INTO :REFALBUM,');
    Script.Add('             :TITREALBUM,');
    Script.Add('             :TOME,');
    Script.Add('             :TOMEDEBUT,');
    Script.Add('             :TOMEFIN,');
    Script.Add('             :HORSSERIE,');
    Script.Add('             :INTEGRALE,');
    Script.Add('             :ANNEEPARUTION,');
    Script.Add('             :REFSERIE,');
    Script.Add('             :TITRESERIE');
    Script.Add('      DO');
    Script.Add('      BEGIN');
    Script.Add('        SUSPEND;');
    Script.Add('      END');
    Script.Add('END;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_COLLECTION (');
    Script.Add('    REFCOLLECTION INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    REFALBUM INTEGER,');
    Script.Add('    TITREALBUM VARCHAR(150),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(30);');
    Script.Add('BEGIN');
    Script.Add('  if (:refCOLLECTION = -1) then sWhere = ''e.refCOLLECTION is null '';');
    Script.Add('                           else sWhere = ''e.refCOLLECTION = '' || :refCOLLECTION;');
    Script.Add('  for execute statement');
    Script.Add('      ''SELECT a.REFALBUM,');
    Script.Add('             a.TITREALBUM,');
    Script.Add('             a.TOME,');
    Script.Add('             a.TOMEDEBUT,');
    Script.Add('             a.TOMEFIN,');
    Script.Add('             a.HORSSERIE,');
    Script.Add('             a.INTEGRALE,');
    Script.Add('             a.ANNEEPARUTION,');
    Script.Add('             a.REFSERIE,');
    Script.Add('             s.TITRESERIE');
    Script.Add('      from albums a left join editions e on a.refalbum = e.refalbum');
    Script.Add('                    left join series s on a.refserie = s.refserie');
    Script.Add('      WHERE '' || :sWHERE ||');
    Script.Add('     ''ORDER BY UPPERTITREALBUM, UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST''');
    Script.Add('      INTO :REFALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :REFSERIE,');
    Script.Add('           :TITRESERIE');
    Script.Add('      DO');
    Script.Add('      BEGIN');
    Script.Add('        SUSPEND;');
    Script.Add('      END');
    Script.Add('END;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_EDITEUR (');
    Script.Add('    REFEDITEUR INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    REFALBUM INTEGER,');
    Script.Add('    TITREALBUM VARCHAR(150),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150))');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  FOR SELECT a.REFALBUM,');
    Script.Add('             a.TITREALBUM,');
    Script.Add('             a.TOME,');
    Script.Add('             a.TOMEDEBUT,');
    Script.Add('             a.TOMEFIN,');
    Script.Add('             a.HORSSERIE,');
    Script.Add('             a.INTEGRALE,');
    Script.Add('             a.ANNEEPARUTION,');
    Script.Add('             a.REFSERIE,');
    Script.Add('             s.TITRESERIE');
    Script.Add('      from albums a LEFT join editions e on a.refalbum = e.refalbum');
    Script.Add('                    LEFT join series s on a.refserie = s.refserie');
    Script.Add('      WHERE e.refediteur = :refediteur');
    Script.Add('      ORDER BY UPPERTITREALBUM, UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST');
    Script.Add('      INTO :REFALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :REFSERIE,');
    Script.Add('           :TITRESERIE');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('END;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_GENRE (');
    Script.Add('    REFGENRE INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    REFALBUM INTEGER,');
    Script.Add('    TITREALBUM VARCHAR(150),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE SWHERE VARCHAR(25);');
    Script.Add('BEGIN');
    Script.Add('  if (:RefGenre = -1) then sWhere = ''RefGenre is null '';');
    Script.Add('                      else sWhere = ''refgenre = '' || :refgenre;');
    Script.Add('  for execute statement');
    Script.Add('      ''SELECT REFALBUM,');
    Script.Add('             TITREALBUM,');
    Script.Add('             TOME,');
    Script.Add('             TOMEDEBUT,');
    Script.Add('             TOMEFIN,');
    Script.Add('             HORSSERIE,');
    Script.Add('             INTEGRALE,');
    Script.Add('             ANNEEPARUTION,');
    Script.Add('             a.REFSERIE,');
    Script.Add('             TITRESERIE');
    Script.Add('       FROM VW_LISTE_ALBUMS a LEFT JOIN GENRESERIES gs ON gs.refserie = a.refserie');
    Script.Add('                              LEFT JOIN GENRES g ON gs.refgenre = g.refgenre');
    Script.Add('       WHERE '' || :sWHERE ||');
    Script.Add('      ''ORDER BY UPPERTITREALBUM, UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST''');
    Script.Add('       INTO :REFALBUM,');
    Script.Add('            :TITREALBUM,');
    Script.Add('            :TOME,');
    Script.Add('            :TOMEDEBUT,');
    Script.Add('            :TOMEFIN,');
    Script.Add('            :HORSSERIE,');
    Script.Add('            :INTEGRALE,');
    Script.Add('            :ANNEEPARUTION,');
    Script.Add('            :REFSERIE,');
    Script.Add('            :TITRESERIE');
    Script.Add('      DO');
    Script.Add('      BEGIN');
    Script.Add('        SUSPEND;');
    Script.Add('      END');
    Script.Add('END;');

    Script.Add('ALTER PROCEDURE ALBUMS_BY_INITIALE (');
    Script.Add('    INITIALE CHAR(1))');
    Script.Add('RETURNS (');
    Script.Add('    REFALBUM INTEGER,');
    Script.Add('    TITREALBUM VARCHAR(150),');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    TOMEDEBUT SMALLINT,');
    Script.Add('    TOMEFIN SMALLINT,');
    Script.Add('    HORSSERIE SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    ANNEEPARUTION SMALLINT,');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150))');
    Script.Add('AS');
    Script.Add('BEGIN');
    Script.Add('  FOR SELECT a.REFALBUM,');
    Script.Add('             a.TITREALBUM,');
    Script.Add('             a.TOME,');
    Script.Add('             a.TOMEDEBUT,');
    Script.Add('             a.TOMEFIN,');
    Script.Add('             a.HORSSERIE,');
    Script.Add('             a.INTEGRALE,');
    Script.Add('             a.ANNEEPARUTION,');
    Script.Add('             a.REFSERIE,');
    Script.Add('             s.TITRESERIE');
    Script.Add('      FROM ALBUMS a INNER JOIN SERIES s ON s.refserie = a.refserie');
    Script.Add('      WHERE a.initialetitrealbum = :INITIALE');
    Script.Add('      ORDER BY UPPERTITREALBUM, UPPERTITRESERIE, HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST');
    Script.Add('      INTO :REFALBUM,');
    Script.Add('           :TITREALBUM,');
    Script.Add('           :TOME,');
    Script.Add('           :TOMEDEBUT,');
    Script.Add('           :TOMEFIN,');
    Script.Add('           :HORSSERIE,');
    Script.Add('           :INTEGRALE,');
    Script.Add('           :ANNEEPARUTION,');
    Script.Add('           :REFSERIE,');
    Script.Add('           :TITRESERIE');
    Script.Add('  DO');
    Script.Add('  BEGIN');
    Script.Add('    SUSPEND;');
    Script.Add('  END');
    Script.Add('END;');

    Script.Add('CREATE PROCEDURE LISTE_TOMES (');
    Script.Add('    WITHINTEGRALE SMALLINT)');
    Script.Add('RETURNS (');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE TOMEDEBUT INTEGER;');
    Script.Add('DECLARE VARIABLE TOMEFIN INTEGER;');
    Script.Add('begin');
    Script.Add('  for');
    Script.Add('    select refserie, tome, integrale');
    Script.Add('    from albums');
    Script.Add('    where TOME is not null and integrale = 0 and horsserie = 0');
    Script.Add('    order by refserie, tome');
    Script.Add('    into :REFSERIE, :TOME, :INTEGRALE');
    Script.Add('    do');
    Script.Add('      suspend;');
    Script.Add('');
    Script.Add('  if (withintegrale = 1) then');
    Script.Add('    for');
    Script.Add('      select refserie, tomedebut, tomefin, integrale');
    Script.Add('      from albums');
    Script.Add('      where TOMEDEBUT is not null and TOMEFIN is not null and integrale = 1 and horsserie = 0');
    Script.Add('      order by refserie, tomedebut, tomefin');
    Script.Add('      into :REFSERIE, :TOMEDEBUT, :TOMEFIN, :INTEGRALE');
    Script.Add('      do begin');
    Script.Add('        TOME = TOMEDEBUT - 1;');
    Script.Add('        while (TOME <> TOMEFIN) do begin');
    Script.Add('          TOME = TOME + 1;');
    Script.Add('          suspend;');
    Script.Add('        end');
    Script.Add('      end');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE ALBUMS_MANQUANTS (');
    Script.Add('    INTEGRALE INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    COUNTSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150),');
    Script.Add('    UPPERTITRESERIE VARCHAR(150),');
    Script.Add('    TOME INTEGER,');
    Script.Add('    REFEDITEUR INTEGER,');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    REFCOLLECTION INTEGER,');
    Script.Add('    NOMCOLLECTION VARCHAR(50))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE MAXSERIE INTEGER;');
    Script.Add('DECLARE VARIABLE CURRENTTOME INTEGER;');
    Script.Add('DECLARE VARIABLE OWNEDTOME INTEGER;');
    Script.Add('begin');
    Script.Add('  if (integrale is null) then integrale = 1;');
    Script.Add('  for select');
    Script.Add('        A.REFSERIE,');
    Script.Add('        max(TOME),');
    Script.Add('        count(distinct TOME),');
    Script.Add('        S.REFEDITEUR,');
    Script.Add('        NOMEDITEUR,');
    Script.Add('        S.REFCOLLECTION,');
    Script.Add('        NOMCOLLECTION');
    Script.Add('      from liste_tomes(:integrale) A inner join SERIES S on A.REFSERIE = S.REFSERIE');
    Script.Add('                                     left join EDITEURS E on S.REFEDITEUR = E.REFEDITEUR');
    Script.Add('                                     left join COLLECTIONS C on S.REFCOLLECTION = C.REFCOLLECTION');
    Script.Add('      where S.COMPLETE = 0');
    Script.Add('      group by A.REFSERIE, UPPERTITRESERIE, UPPERNOMEDITEUR, UPPERNOMCOLLECTION,');
    Script.Add('               S.REFEDITEUR, NOMEDITEUR, S.REFCOLLECTION, NOMCOLLECTION');
    Script.Add('      order by UPPERTITRESERIE, UPPERNOMEDITEUR, UPPERNOMCOLLECTION');
    Script.Add('      into');
    Script.Add('        :REFSERIE,');
    Script.Add('        :MAXSERIE,');
    Script.Add('        :COUNTSERIE,');
    Script.Add('        :REFEDITEUR,');
    Script.Add('        :NOMEDITEUR,');
    Script.Add('        :REFCOLLECTION,');
    Script.Add('        :NOMCOLLECTION');
    Script.Add('  do begin');
    Script.Add('    if (COUNTSERIE <> MAXSERIE) then begin');
    Script.Add('      CURRENTTOME = 0;');
    Script.Add('      for select distinct');
    Script.Add('            UPPERTITRESERIE,');
    Script.Add('            TITRESERIE,');
    Script.Add('            TOME');
    Script.Add('          from liste_tomes(:integrale) A inner join SERIES S on A.REFSERIE = S.REFSERIE and S.REFSERIE = :REFSERIE');
    Script.Add('          order by TOME');
    Script.Add('          into');
    Script.Add('            :UPPERTITRESERIE,');
    Script.Add('            :TITRESERIE,');
    Script.Add('            :OWNEDTOME');
    Script.Add('      do begin');
    Script.Add('        CURRENTTOME = CURRENTTOME + 1;');
    Script.Add('        while ((CURRENTTOME <> OWNEDTOME) and (CURRENTTOME < MAXSERIE)) do begin');
    Script.Add('          TOME = CURRENTTOME;');
    Script.Add('          suspend;');
    Script.Add('          CURRENTTOME = CURRENTTOME + 1;');
    Script.Add('        end');
    Script.Add('      end');
    Script.Add('    end');
    Script.Add('  end');
    Script.Add('end;');

    ExecuteScript;
  end;
end;

initialization
  RegisterFBUpdate('0.0.2.5', @MAJ0_0_2_5);

end.
