unit UMAJ0_0_3_21;

interface

implementation

uses UIB, Updates;

procedure MAJ0_0_3_21(Query: TUIBScript);
begin
  with Query do begin
    Script.Clear;

    Script.Add('ALTER TABLE ALBUMS ADD ACHAT T_YESNO_BASENO;');
    Script.Add('UPDATE ALBUMS SET ACHAT = 0 WHERE ACHAT IS NULL;');

    Script.Add('ALTER PROCEDURE LISTE_TOMES (');
    Script.Add('    WITHINTEGRALE SMALLINT,');
    Script.Add('    IN_REFSERIE INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TOME SMALLINT,');
    Script.Add('    INTEGRALE SMALLINT,');
    Script.Add('    ACHAT SMALLINT)');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE TOMEDEBUT INTEGER;');
    Script.Add('DECLARE VARIABLE TOMEFIN INTEGER;');
    Script.Add('begin');
    Script.Add('  for');
    Script.Add('    select refserie, tome, integrale, achat');
    Script.Add('    from albums');
    Script.Add('    where TOME is not null and integrale = 0 and horsserie = 0');
    Script.Add('          and (:in_refserie is null or refserie = :in_refserie)');
    Script.Add('    order by refserie, tome');
    Script.Add('    into :REFSERIE, :TOME, :INTEGRALE, :ACHAT');
    Script.Add('    do');
    Script.Add('      suspend;');
    Script.Add('');
    Script.Add('  if (withintegrale is null) then withintegrale = 1;');
    Script.Add('  if (withintegrale = 1) then');
    Script.Add('    for');
    Script.Add('      select refserie, tomedebut, tomefin, integrale, achat');
    Script.Add('      from albums');
    Script.Add('      where TOMEDEBUT is not null and TOMEFIN is not null and integrale = 1 and horsserie = 0');
    Script.Add('            and (:in_refserie is null or refserie = :in_refserie)');
    Script.Add('      order by refserie, tomedebut, tomefin');
    Script.Add('      into :REFSERIE, :TOMEDEBUT, :TOMEFIN, :INTEGRALE, :ACHAT');
    Script.Add('      do begin');
    Script.Add('        TOME = TOMEDEBUT - 1;');
    Script.Add('        while (TOME <> TOMEFIN) do begin');
    Script.Add('          TOME = TOME + 1;');
    Script.Add('          suspend;');
    Script.Add('        end');
    Script.Add('      end');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE ALBUMS_MANQUANTS (');
    Script.Add('    WITHINTEGRALE SMALLINT,');
    Script.Add('    WITHACHAT SMALLINT,');
    Script.Add('    IN_REFSERIE INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    COUNTSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150),');
    Script.Add('    UPPERTITRESERIE VARCHAR(150),');
    Script.Add('    TOME INTEGER,');
    Script.Add('    REFEDITEUR INTEGER,');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    REFCOLLECTION INTEGER,');
    Script.Add('    NOMCOLLECTION VARCHAR(50))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE MAXSERIE INTEGER;');
    Script.Add('DECLARE VARIABLE CURRENTTOME Integer;');
    Script.Add('DECLARE VARIABLE OWNEDTOME Integer;');
    Script.Add('DECLARE VARIABLE ACHAT Smallint;');
    Script.Add('DECLARE VARIABLE SUMACHAT Integer;');
    Script.Add('begin');
    Script.Add('  if (WITHINTEGRALE is null) then WITHINTEGRALE = 1;');
    Script.Add('  if (WITHACHAT is null) then WITHACHAT = 1;');
    Script.Add('  for select');
    Script.Add('        A.REFSERIE,');
    Script.Add('        max(TOME),');
    Script.Add('        count(distinct TOME),');
    Script.Add('        sum(ACHAT),');
    Script.Add('        S.REFEDITEUR,');
    Script.Add('        NOMEDITEUR,');
    Script.Add('        S.REFCOLLECTION,');
    Script.Add('        NOMCOLLECTION');
    Script.Add('      from liste_tomes(:WITHINTEGRALE, :in_refserie) A');
    Script.Add('         inner join SERIES S on A.REFSERIE = S.REFSERIE');
    Script.Add('         left join EDITEURS E on S.REFEDITEUR = E.REFEDITEUR');
    Script.Add('         left join COLLECTIONS C on S.REFCOLLECTION = C.REFCOLLECTION');
    Script.Add('      where S.COMPLETE = 0');
    Script.Add('      group by A.REFSERIE, UPPERTITRESERIE, UPPERNOMEDITEUR, UPPERNOMCOLLECTION,');
    Script.Add('               S.REFEDITEUR, NOMEDITEUR, S.REFCOLLECTION, NOMCOLLECTION');
    Script.Add('      order by UPPERTITRESERIE, UPPERNOMEDITEUR, UPPERNOMCOLLECTION');
    Script.Add('      into');
    Script.Add('        :REFSERIE,');
    Script.Add('        :MAXSERIE,');
    Script.Add('        :COUNTSERIE,');
    Script.Add('        :SUMACHAT,');
    Script.Add('        :REFEDITEUR,');
    Script.Add('        :NOMEDITEUR,');
    Script.Add('        :REFCOLLECTION,');
    Script.Add('        :NOMCOLLECTION');
    Script.Add('  do begin');
    Script.Add('    if (WITHACHAT = 0) then');
    Script.Add('      COUNTSERIE = COUNTSERIE - SUMACHAT;');
    Script.Add('    if (COUNTSERIE <> MAXSERIE) then begin');
    Script.Add('      CURRENTTOME = 0;');
    Script.Add('      for select distinct');
    Script.Add('            UPPERTITRESERIE,');
    Script.Add('            TITRESERIE,');
    Script.Add('            TOME,');
    Script.Add('            ACHAT');
    Script.Add('          from liste_tomes(:WITHINTEGRALE, :REFSERIE) A inner join SERIES S on A.REFSERIE = S.REFSERIE');
    Script.Add('          order by TOME');
    Script.Add('          into');
    Script.Add('            :UPPERTITRESERIE,');
    Script.Add('            :TITRESERIE,');
    Script.Add('            :OWNEDTOME,');
    Script.Add('            :ACHAT');
    Script.Add('      do begin');
    Script.Add('        CURRENTTOME = CURRENTTOME + 1;');
    Script.Add('        while ((CURRENTTOME <> OWNEDTOME) and (CURRENTTOME < MAXSERIE)) do begin');
    Script.Add('          TOME = CURRENTTOME;');
    Script.Add('          suspend;');
    Script.Add('          CURRENTTOME = CURRENTTOME + 1;');
    Script.Add('        end');
    Script.Add('        if ((WITHACHAT = 0) AND (ACHAT = 1)) then begin');
    Script.Add('          TOME = OWNEDTOME;');
    Script.Add('          suspend;');
    Script.Add('        end');
    Script.Add('      end');
    Script.Add('    end');
    Script.Add('  end');
    Script.Add('end;');

    Script.Add('CREATE PROCEDURE CALCUL_ANNEE_SORTIE (');
    Script.Add('    WITHACHAT SMALLINT,');
    Script.Add('    IN_REFSERIE INTEGER,');
    Script.Add('    SOMMEPONDEREE INTEGER,');
    Script.Add('    COMPTEALBUM INTEGER,');
    Script.Add('    MAXTOME INTEGER,');
    Script.Add('    MAXANNEE INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150),');
    Script.Add('    UPPERTITRESERIE VARCHAR(150),');
    Script.Add('    TOME INTEGER,');
    Script.Add('    ANNEEPARUTION INTEGER,');
    Script.Add('    REFEDITEUR INTEGER,');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    REFCOLLECTION INTEGER,');
    Script.Add('    NOMCOLLECTION VARCHAR(50))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE MAXTOME2 INTEGER;');
    Script.Add('begin');
    Script.Add('  tome = maxtome + 1;');
    Script.Add('');
    Script.Add('  select max(tomefin) + 1 from albums');
    Script.Add('  where horsserie = 0 and integrale = 1 and refserie = :in_refserie and (:withachat = 1 or achat = 0)');
    Script.Add('  into');
    Script.Add('    :MAXTOME2;');
    Script.Add('');
    Script.Add('  if (maxtome2 > tome) then tome = maxtome2;');
    Script.Add('');
    Script.Add('  select s.RefSerie, s.TitreSerie, s.UpperTitreSerie, e.RefEditeur, e.NomEditeur, c.RefCollection, c.NomCollection from');
    Script.Add('    series s left join editeurs e on e.refediteur = s.refediteur');
    Script.Add('             left join collections c on c.refcollection = s.refcollection');
    Script.Add('  where s.RefSerie = :in_refserie');
    Script.Add('  into');
    Script.Add('    :REFSERIE,');
    Script.Add('    :TITRESERIE,');
    Script.Add('    :UPPERTITRESERIE,');
    Script.Add('    :REFEDITEUR,');
    Script.Add('    :NOMEDITEUR,');
    Script.Add('    :REFCOLLECTION,');
    Script.Add('    :NOMCOLLECTION;');
    Script.Add('');
    Script.Add('  ANNEEPARUTION = maxannee + ((tome - maxtome) * (sommeponderee / comptealbum));');
    Script.Add('  suspend;');
    Script.Add('end;');

    Script.Add('ALTER PROCEDURE PREVISIONS_SORTIES (');
    Script.Add('    WITHACHAT SMALLINT,');
    Script.Add('    IN_REFSERIE INTEGER)');
    Script.Add('RETURNS (');
    Script.Add('    REFSERIE INTEGER,');
    Script.Add('    TITRESERIE VARCHAR(150),');
    Script.Add('    UPPERTITRESERIE VARCHAR(150),');
    Script.Add('    TOME INTEGER,');
    Script.Add('    ANNEEPARUTION INTEGER,');
    Script.Add('    REFEDITEUR INTEGER,');
    Script.Add('    NOMEDITEUR VARCHAR(50),');
    Script.Add('    REFCOLLECTION INTEGER,');
    Script.Add('    NOMCOLLECTION VARCHAR(50))');
    Script.Add('AS');
    Script.Add('DECLARE VARIABLE CURRENTREFSERIE INTEGER;');
    Script.Add('DECLARE VARIABLE OLDREFSERIE Integer;');
    Script.Add('DECLARE VARIABLE CURRENTTOME Integer;');
    Script.Add('DECLARE VARIABLE SOMMEPONDEREE Integer;');
    Script.Add('DECLARE VARIABLE COMPTEALBUM Integer;');
    Script.Add('DECLARE VARIABLE CURRENTANNEE Integer;');
    Script.Add('DECLARE VARIABLE TOMEPRECEDENT Integer;');
    Script.Add('DECLARE VARIABLE ANNEEPRECEDENTE Integer;');
    Script.Add('begin');
    Script.Add('  if (withachat is Null) then withachat = 1;');
    Script.Add('  oldrefserie = -1;');
    Script.Add('  tomeprecedent = -1;');
    Script.Add('  anneeprecedente = -1;');
    Script.Add('  for select TOME, ANNEEPARUTION, s.RefSerie');
    Script.Add('      from albums a inner join series s on s.refserie = a.refserie');
    Script.Add('      where (s.terminee is null or s.terminee <> 1)');
    Script.Add('            and a.horsserie = 0 and a.integrale = 0 and a.anneeparution is not null');
    Script.Add('            and (:in_refserie is null or s.refserie = :in_refserie)');
    Script.Add('            and (:withachat = 1 or achat = 0)');
    Script.Add('      order by s.refserie, TOME');
    Script.Add('      into :CURRENTTOME, :CURRENTANNEE, :CURRENTREFSERIE');
    Script.Add('  do begin');
    Script.Add('    if (currentrefserie <> oldrefserie) then begin');
    Script.Add('');
    Script.Add('      if (oldrefserie <> -1 and comptealbum > 0) then begin');
    Script.Add('        select REFSERIE, TITRESERIE, UPPERTITRESERIE,');
    Script.Add('               TOME, ANNEEPARUTION,');
    Script.Add('               REFEDITEUR, NOMEDITEUR,');
    Script.Add('               REFCOLLECTION, NOMCOLLECTION');
    Script.Add('        from CALCUL_ANNEE_SORTIE(:withachat, :oldrefserie, :sommeponderee, :comptealbum, :tomeprecedent, :anneeprecedente)');
    Script.Add('        into :REFSERIE, :TITRESERIE, :UPPERTITRESERIE,');
    Script.Add('             :TOME, :ANNEEPARUTION,');
    Script.Add('             :REFEDITEUR, :NOMEDITEUR,');
    Script.Add('             :REFCOLLECTION, :NOMCOLLECTION;');
    Script.Add('        suspend;');
    Script.Add('      end');
    Script.Add('');
    Script.Add('      oldrefserie = currentrefserie;');
    Script.Add('      sommeponderee = 0;');
    Script.Add('      comptealbum = 0;');
    Script.Add('      tomeprecedent = -1;');
    Script.Add('      anneeprecedente = -1;');
    Script.Add('    end');
    Script.Add('    if (tomeprecedent <> -1) then begin');
    Script.Add('      /* non pondéré: sommeponderee = sommeponderee + ((CURRENTANNEE - ANNEEPRECEDENTE) / (CURRENTTOME - TOMEPRECEDENT)); */');
    Script.Add('      sommeponderee = sommeponderee + ((CURRENTANNEE - ANNEEPRECEDENTE) / (CURRENTTOME - TOMEPRECEDENT)) * CURRENTTOME;');
    Script.Add('      /* non pondéré: comptealbum = comptealbum + 1;*/');
    Script.Add('      comptealbum = comptealbum + CURRENTTOME;');
    Script.Add('    end');
    Script.Add('    tomeprecedent = CURRENTTOME;');
    Script.Add('    anneeprecedente = CURRENTANNEE;');
    Script.Add('  end');
    Script.Add('');
    Script.Add('  if (oldrefserie <> -1 and comptealbum > 0) then begin');
    Script.Add('    select REFSERIE, TITRESERIE, UPPERTITRESERIE,');
    Script.Add('           TOME, ANNEEPARUTION,');
    Script.Add('           REFEDITEUR, NOMEDITEUR,');
    Script.Add('           REFCOLLECTION, NOMCOLLECTION');
    Script.Add('    from CALCUL_ANNEE_SORTIE(:withachat, :oldrefserie, :sommeponderee, :comptealbum, :tomeprecedent, :anneeprecedente)');
    Script.Add('    into :REFSERIE, :TITRESERIE, :UPPERTITRESERIE,');
    Script.Add('         :TOME, :ANNEEPARUTION,');
    Script.Add('         :REFEDITEUR, :NOMEDITEUR,');
    Script.Add('         :REFCOLLECTION, :NOMCOLLECTION;');
    Script.Add('    suspend;');
    Script.Add('  end');
    Script.Add('end;');

    ExecuteScript;
  end;
end;

initialization
  RegisterFBUpdate('0.0.3.21', @MAJ0_0_3_21);

end.
