unit UMAJ1_2_0_0;

interface

implementation

uses UIB, Updates;

procedure MAJ1_2_0_0(Query: TUIBScript);
begin
  with Query do begin
    Script.Clear;

    // InitialiseTables
    LoadScript('MAJ1_2_0_0part1', Script);
    ExecuteScript;

    // RecreerVuesProcTrigger
    LoadScript('MAJ1_2_0_0part2', Script);
    ExecuteScript;

    Script.Clear;

    Script.Add('DROP GENERATOR AI_REFALBUM;');
    Script.Add('DROP GENERATOR AI_REFCOLLECTION;');
    Script.Add('DROP GENERATOR AI_REFCOUVERTURE;');
    Script.Add('DROP GENERATOR AI_REFEDITEUR;');
    Script.Add('DROP GENERATOR AI_REFEDITION;');
    Script.Add('DROP GENERATOR AI_REFEMPRUNT;');
    Script.Add('DROP GENERATOR AI_REFEMPRUNTEUR;');
    Script.Add('DROP GENERATOR AI_REFGENRE;');
    Script.Add('DROP GENERATOR AI_REFPARABD;');
    Script.Add('DROP GENERATOR AI_REFPERSONNE;');
    Script.Add('DROP GENERATOR AI_REFSERIE;');
    Script.Add('ALTER TABLE ALBUMS DROP REFALBUM, DROP REFSERIE;');
    Script.Add('ALTER TABLE AUTEURS DROP REFALBUM, DROP REFPERSONNE;');
    Script.Add('ALTER TABLE AUTEURS_PARABD DROP REFPARABD, DROP REFPERSONNE;');
    Script.Add('ALTER TABLE AUTEURS_SERIES DROP REFSERIE, DROP REFPERSONNE;');
    Script.Add('ALTER TABLE COLLECTIONS DROP REFCOLLECTION, DROP REFEDITEUR;');
    Script.Add('ALTER TABLE COTES DROP REFEDITION;');
    Script.Add('ALTER TABLE COTES_PARABD DROP REFPARABD;');
    Script.Add('ALTER TABLE COUVERTURES DROP REFCOUVERTURE, DROP REFALBUM, DROP REFEDITION;');
    Script.Add('ALTER TABLE EDITEURS DROP REFEDITEUR;');
    Script.Add('ALTER TABLE EDITIONS DROP REFEDITION, DROP REFALBUM, DROP REFEDITEUR, DROP REFCOLLECTION;');
    Script.Add('ALTER TABLE EMPRUNTEURS DROP REFEMPRUNTEUR;');
    Script.Add('ALTER TABLE GENRES DROP REFGENRE;');
    Script.Add('ALTER TABLE GENRESERIES DROP REFSERIE, DROP REFGENRE;');
    Script.Add('ALTER TABLE PARABD DROP REFPARABD, DROP REFSERIE;');
    Script.Add('ALTER TABLE PERSONNES DROP REFPERSONNE;');
    Script.Add('ALTER TABLE SERIES DROP REFSERIE, DROP REFEDITEUR, DROP REFCOLLECTION;');
    Script.Add('ALTER TABLE STATUT DROP REFEMPRUNT, DROP REFEDITION, DROP REFEMPRUNTEUR;');

    ExecuteScript;
  end;
end;

initialization
  RegisterFBUpdate('1.2.0.0', @MAJ1_2_0_0);

end.

