//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.42
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD.Workstation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("User=SYSDBA;Password=masterkey;Database=SampleDatabase.fdb;DataSource=localhost;P" +
            "ort=3050;Dialect=3;Charset=NONE;Role=;Connection lifetime=15;Pooling=true;MinPoo" +
            "lSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;")]
        public string bdConnectionString {
            get {
                return ((string)(this["bdConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\Programmation\\MEDIA.KIT\\BDThèque\\bin\\BD.GDB")]
        public string database {
            get {
                return ((string)(this["database"]));
            }
            set {
                this["database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SYSDBA")]
        public string dbusername {
            get {
                return ((string)(this["dbusername"]));
            }
            set {
                this["dbusername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("masterkey")]
        public string dbuserpassword {
            get {
                return ((string)(this["dbuserpassword"]));
            }
            set {
                this["dbuserpassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string dbserver {
            get {
                return ((string)(this["dbserver"]));
            }
            set {
                this["dbserver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::FirebirdSql.Data.FirebirdClient.FbServerType dbservertype {
            get {
                return ((global::FirebirdSql.Data.FirebirdClient.FbServerType)(this["dbservertype"]));
            }
            set {
                this["dbservertype"] = value;
            }
        }
    }
}
