unit BDTK.Updates.v1_2_3_25;

interface

implementation

uses UIB, BDTK.Updates;

procedure MAJ1_2_3_25(Query: TUIBScript);
begin
  Query.Script.Clear;

  Query.Script.Add('ALTER PROCEDURE PROC_EMPRUNTS');
  Query.Script.Add('RETURNS (');
  Query.Script.Add('    ID_EDITION CHAR(38),');
  Query.Script.Add('    ID_ALBUM CHAR(38),');
  Query.Script.Add('    TITREALBUM VARCHAR(150),');
  Query.Script.Add('    ID_SERIE CHAR(38),');
  Query.Script.Add('    TITRESERIE VARCHAR(150),');
  Query.Script.Add('    PRETE SMALLINT,');
  Query.Script.Add('    ID_EMPRUNTEUR CHAR(38),');
  Query.Script.Add('    NOMEMPRUNTEUR VARCHAR(150),');
  Query.Script.Add('    PRETEMPRUNT SMALLINT,');
  Query.Script.Add('    DATEEMPRUNT TIMESTAMP)');
  Query.Script.Add('AS');
  Query.Script.Add('BEGIN');
  Query.Script.Add('  EXIT;');
  Query.Script.Add('END;');

  Query.Script.Add('DROP VIEW VW_LISTE_GENRES_ALBUMS;');
  Query.Script.Add('DROP VIEW VW_LISTE_EDITEURS_ALBUMS;');
  Query.Script.Add('DROP VIEW VW_LISTE_EDITEURS_ACHATALBUMS;');
  Query.Script.Add('DROP VIEW VW_LISTE_COLLECTIONS_ALBUMS;');
  Query.Script.Add('DROP VIEW VW_EMPRUNTS;');
  Query.Script.Add('DROP VIEW VW_LISTE_ALBUMS;');

  Query.Script.Add('CREATE VIEW VW_LISTE_ALBUMS(');
  Query.Script.Add('    ID_ALBUM,');
  Query.Script.Add('    TITREALBUM,');
  Query.Script.Add('    TOME,');
  Query.Script.Add('    TOMEDEBUT,');
  Query.Script.Add('    TOMEFIN,');
  Query.Script.Add('    HORSSERIE,');
  Query.Script.Add('    INTEGRALE,');
  Query.Script.Add('    MOISPARUTION,');
  Query.Script.Add('    ANNEEPARUTION,');
  Query.Script.Add('    ID_SERIE,');
  Query.Script.Add('    TITRESERIE,');
  Query.Script.Add('    UPPERTITREALBUM,');
  Query.Script.Add('    UPPERTITRESERIE,');
  Query.Script.Add('    ACHAT,');
  Query.Script.Add('    COMPLET,');
  Query.Script.Add('    initialetitrealbum,');
  Query.Script.Add('    initialetitreserie)');
  Query.Script.Add('AS');
  Query.Script.Add('select a.ID_ALBUM,');
  Query.Script.Add('       a.TITREALBUM,');
  Query.Script.Add('       a.TOME,');
  Query.Script.Add('       a.TOMEDEBUT,');
  Query.Script.Add('       a.TOMEFIN,');
  Query.Script.Add('       a.HORSSERIE,');
  Query.Script.Add('       a.INTEGRALE,');
  Query.Script.Add('       a.MOISPARUTION,');
  Query.Script.Add('       a.ANNEEPARUTION,');
  Query.Script.Add('       a.ID_SERIE,');
  Query.Script.Add('       s.TITRESERIE,');
  Query.Script.Add('       a.UPPERTITREALBUM,');
  Query.Script.Add('       s.UPPERTITRESERIE,');
  Query.Script.Add('       a.ACHAT,');
  Query.Script.Add('       a.COMPLET,');
  Query.Script.Add('       COALESCE(a.INITIALETITREALBUM, s.INITIALETITRESERIE),');
  Query.Script.Add('       s.INITIALETITRESERIE');
  Query.Script.Add('FROM ALBUMS a LEFT JOIN SERIES s ON s.ID_SERIE = a.id_serie;');

  Query.Script.Add('CREATE VIEW VW_EMPRUNTS(');
  Query.Script.Add('    ID_STATUT,');
  Query.Script.Add('    ID_EDITION,');
  Query.Script.Add('    ID_ALBUM,');
  Query.Script.Add('    TITREALBUM,');
  Query.Script.Add('    UPPERTITREALBUM,');
  Query.Script.Add('    ID_SERIE,');
  Query.Script.Add('    TOME,');
  Query.Script.Add('    INTEGRALE,');
  Query.Script.Add('    TOMEDEBUT,');
  Query.Script.Add('    TOMEFIN,');
  Query.Script.Add('    HORSSERIE,');
  Query.Script.Add('    TITRESERIE,');
  Query.Script.Add('    ID_EDITEUR,');
  Query.Script.Add('    NOMEDITEUR,');
  Query.Script.Add('    ID_COLLECTION,');
  Query.Script.Add('    NOMCOLLECTION,');
  Query.Script.Add('    PRETE,');
  Query.Script.Add('    ANNEEEDITION,');
  Query.Script.Add('    ISBN,');
  Query.Script.Add('    ID_EMPRUNTEUR,');
  Query.Script.Add('    NOMEMPRUNTEUR,');
  Query.Script.Add('    PRETEMPRUNT,');
  Query.Script.Add('    DATEEMPRUNT)');
  Query.Script.Add('AS');
  Query.Script.Add('SELECT S.id_statut,');
  Query.Script.Add('       Ed.ID_EDITION,');
  Query.Script.Add('       A.ID_ALBUM,');
  Query.Script.Add('       A.titrealbum,');
  Query.Script.Add('       A.uppertitrealbum,');
  Query.Script.Add('       A.id_serie,');
  Query.Script.Add('       A.Tome,');
  Query.Script.Add('       A.Integrale,');
  Query.Script.Add('       A.TomeDebut,');
  Query.Script.Add('       A.TomeFin,');
  Query.Script.Add('       A.HorsSerie,');
  Query.Script.Add('       A.titreserie,');
  Query.Script.Add('       E.ID_EDITEUR,');
  Query.Script.Add('       E.NomEditeur,');
  Query.Script.Add('       C.ID_COLLECTION,');
  Query.Script.Add('       C.NomCollection,');
  Query.Script.Add('       Ed.prete,');
  Query.Script.Add('       Ed.AnneeEdition,');
  Query.Script.Add('       Ed.ISBN,');
  Query.Script.Add('       Em.ID_EMPRUNTEUR,');
  Query.Script.Add('       Em.NomEmprunteur,');
  Query.Script.Add('       S.PretEmprunt,');
  Query.Script.Add('       S.DateEmprunt');
  Query.Script.Add('FROM VW_LISTE_ALBUMS A');
  Query.Script.Add('  INNER JOIN EDITIONS Ed ON A.ID_ALBUM = Ed.id_album');
  Query.Script.Add('  INNER JOIN EDITEURS e ON e.ID_EDITEUR = ed.id_editeur');
  Query.Script.Add('  LEFT JOIN COLLECTIONS C ON C.ID_COLLECTION = ed.id_collection');
  Query.Script.Add('  INNER JOIN STATUT S ON Ed.ID_EDITION = S.id_edition');
  Query.Script.Add('  INNER JOIN EMPRUNTEURS Em ON Em.ID_EMPRUNTEUR = S.id_emprunteur;');

  Query.Script.Add('CREATE VIEW VW_LISTE_COLLECTIONS_ALBUMS(');
  Query.Script.Add('    ID_ALBUM,');
  Query.Script.Add('    TITREALBUM,');
  Query.Script.Add('    TOME,');
  Query.Script.Add('    TOMEDEBUT,');
  Query.Script.Add('    TOMEFIN,');
  Query.Script.Add('    HORSSERIE,');
  Query.Script.Add('    INTEGRALE,');
  Query.Script.Add('    MOISPARUTION,');
  Query.Script.Add('    ANNEEPARUTION,');
  Query.Script.Add('    ID_SERIE,');
  Query.Script.Add('    TITRESERIE,');
  Query.Script.Add('    UPPERTITREALBUM,');
  Query.Script.Add('    ID_COLLECTION,');
  Query.Script.Add('    NOMCOLLECTION,');
  Query.Script.Add('    UPPERNOMCOLLECTION,');
  Query.Script.Add('    UPPERTITRESERIE,');
  Query.Script.Add('    ACHAT,');
  Query.Script.Add('    COMPLET)');
  Query.Script.Add('AS');
  Query.Script.Add('select a.ID_ALBUM,');
  Query.Script.Add('       a.TITREALBUM,');
  Query.Script.Add('       a.TOME,');
  Query.Script.Add('       a.TOMEDEBUT,');
  Query.Script.Add('       a.TOMEFIN,');
  Query.Script.Add('       a.HORSSERIE,');
  Query.Script.Add('       a.INTEGRALE,');
  Query.Script.Add('       a.MOISPARUTION,');
  Query.Script.Add('       a.ANNEEPARUTION,');
  Query.Script.Add('       a.ID_SERIE,');
  Query.Script.Add('       a.TITRESERIE,');
  Query.Script.Add('       a.UPPERTITREALBUM,');
  Query.Script.Add('       c.ID_COLLECTION,');
  Query.Script.Add('       c.NOMCOLLECTION,');
  Query.Script.Add('       c.UPPERNOMCOLLECTION,');
  Query.Script.Add('       a.UPPERTITRESERIE,');
  Query.Script.Add('       a.ACHAT,');
  Query.Script.Add('       a.COMPLET');
  Query.Script.Add('FROM VW_LISTE_ALBUMS a LEFT JOIN EDITIONS e ON e.id_album = a.id_album');
  Query.Script.Add('                       LEFT JOIN COLLECTIONS c ON e.id_collection = c.ID_COLLECTION;');

  Query.Script.Add('CREATE VIEW VW_LISTE_EDITEURS_ACHATALBUMS(');
  Query.Script.Add('    ID_ALBUM,');
  Query.Script.Add('    TITREALBUM,');
  Query.Script.Add('    TOME,');
  Query.Script.Add('    TOMEDEBUT,');
  Query.Script.Add('    TOMEFIN,');
  Query.Script.Add('    HORSSERIE,');
  Query.Script.Add('    INTEGRALE,');
  Query.Script.Add('    MOISPARUTION,');
  Query.Script.Add('    ANNEEPARUTION,');
  Query.Script.Add('    ID_SERIE,');
  Query.Script.Add('    TITRESERIE,');
  Query.Script.Add('    UPPERTITREALBUM,');
  Query.Script.Add('    ID_EDITEUR,');
  Query.Script.Add('    NOMEDITEUR,');
  Query.Script.Add('    UPPERNOMEDITEUR,');
  Query.Script.Add('    UPPERTITRESERIE,');
  Query.Script.Add('    ACHAT,');
  Query.Script.Add('    COMPLET)');
  Query.Script.Add('AS');
  Query.Script.Add('select a.ID_ALBUM,');
  Query.Script.Add('       a.TITREALBUM,');
  Query.Script.Add('       a.TOME,');
  Query.Script.Add('       a.TOMEDEBUT,');
  Query.Script.Add('       a.TOMEFIN,');
  Query.Script.Add('       a.HORSSERIE,');
  Query.Script.Add('       a.INTEGRALE,');
  Query.Script.Add('       a.MOISPARUTION,');
  Query.Script.Add('       a.ANNEEPARUTION,');
  Query.Script.Add('       a.ID_SERIE,');
  Query.Script.Add('       a.TITRESERIE,');
  Query.Script.Add('       a.UPPERTITREALBUM,');
  Query.Script.Add('       e.ID_EDITEUR,');
  Query.Script.Add('       e.NOMEDITEUR,');
  Query.Script.Add('       e.UPPERNOMEDITEUR,');
  Query.Script.Add('       a.UPPERTITRESERIE,');
  Query.Script.Add('       a.ACHAT,');
  Query.Script.Add('       a.COMPLET');
  Query.Script.Add('FROM VW_LISTE_ALBUMS a LEFT JOIN SERIES s ON s.id_serie = a.id_serie');
  Query.Script.Add('                       LEFT JOIN EDITEURS e ON e.ID_EDITEUR = s.id_editeur;');

  Query.Script.Add('CREATE VIEW VW_LISTE_EDITEURS_ALBUMS(');
  Query.Script.Add('    ID_ALBUM,');
  Query.Script.Add('    TITREALBUM,');
  Query.Script.Add('    TOME,');
  Query.Script.Add('    TOMEDEBUT,');
  Query.Script.Add('    TOMEFIN,');
  Query.Script.Add('    HORSSERIE,');
  Query.Script.Add('    INTEGRALE,');
  Query.Script.Add('    MOISPARUTION,');
  Query.Script.Add('    ANNEEPARUTION,');
  Query.Script.Add('    ID_SERIE,');
  Query.Script.Add('    TITRESERIE,');
  Query.Script.Add('    UPPERTITREALBUM,');
  Query.Script.Add('    ID_EDITEUR,');
  Query.Script.Add('    NOMEDITEUR,');
  Query.Script.Add('    UPPERNOMEDITEUR,');
  Query.Script.Add('    UPPERTITRESERIE,');
  Query.Script.Add('    ACHAT,');
  Query.Script.Add('    COMPLET)');
  Query.Script.Add('AS');
  Query.Script.Add('select a.ID_ALBUM,');
  Query.Script.Add('       a.TITREALBUM,');
  Query.Script.Add('       a.TOME,');
  Query.Script.Add('       a.TOMEDEBUT,');
  Query.Script.Add('       a.TOMEFIN,');
  Query.Script.Add('       a.HORSSERIE,');
  Query.Script.Add('       a.INTEGRALE,');
  Query.Script.Add('       a.MOISPARUTION,');
  Query.Script.Add('       a.ANNEEPARUTION,');
  Query.Script.Add('       a.ID_SERIE,');
  Query.Script.Add('       a.TITRESERIE,');
  Query.Script.Add('       a.UPPERTITREALBUM,');
  Query.Script.Add('       e.ID_EDITEUR,');
  Query.Script.Add('       e.NOMEDITEUR,');
  Query.Script.Add('       e.UPPERNOMEDITEUR,');
  Query.Script.Add('       a.UPPERTITRESERIE,');
  Query.Script.Add('       a.ACHAT,');
  Query.Script.Add('       a.COMPLET');
  Query.Script.Add('FROM VW_LISTE_ALBUMS a LEFT JOIN EDITIONS ed ON ed.id_album = a.id_album');
  Query.Script.Add('                       LEFT JOIN EDITEURS e ON e.ID_EDITEUR = ed.id_editeur;');

  Query.Script.Add('CREATE VIEW VW_LISTE_GENRES_ALBUMS(');
  Query.Script.Add('    ID_ALBUM,');
  Query.Script.Add('    TITREALBUM,');
  Query.Script.Add('    TOME,');
  Query.Script.Add('    TOMEDEBUT,');
  Query.Script.Add('    TOMEFIN,');
  Query.Script.Add('    HORSSERIE,');
  Query.Script.Add('    INTEGRALE,');
  Query.Script.Add('    MOISPARUTION,');
  Query.Script.Add('    ANNEEPARUTION,');
  Query.Script.Add('    ID_SERIE,');
  Query.Script.Add('    TITRESERIE,');
  Query.Script.Add('    UPPERTITREALBUM,');
  Query.Script.Add('    ID_GENRE,');
  Query.Script.Add('    GENRE,');
  Query.Script.Add('    UPPERGENRE,');
  Query.Script.Add('    UPPERTITRESERIE,');
  Query.Script.Add('    ACHAT,');
  Query.Script.Add('    COMPLET)');
  Query.Script.Add('AS');
  Query.Script.Add('select a.ID_ALBUM,');
  Query.Script.Add('       a.TITREALBUM,');
  Query.Script.Add('       a.TOME,');
  Query.Script.Add('       a.TOMEDEBUT,');
  Query.Script.Add('       a.TOMEFIN,');
  Query.Script.Add('       a.HORSSERIE,');
  Query.Script.Add('       a.INTEGRALE,');
  Query.Script.Add('       a.MOISPARUTION,');
  Query.Script.Add('       a.ANNEEPARUTION,');
  Query.Script.Add('       a.ID_SERIE,');
  Query.Script.Add('       a.TITRESERIE,');
  Query.Script.Add('       a.UPPERTITREALBUM,');
  Query.Script.Add('       g.ID_GENRE,');
  Query.Script.Add('       g.GENRE,');
  Query.Script.Add('       g.UPPERGENRE,');
  Query.Script.Add('       a.UPPERTITRESERIE,');
  Query.Script.Add('       a.ACHAT,');
  Query.Script.Add('       a.COMPLET');
  Query.Script.Add('FROM VW_LISTE_ALBUMS a LEFT JOIN GENRESERIES gs ON gs.id_serie = a.id_serie');
  Query.Script.Add('                       LEFT JOIN GENRES g ON gs.id_genre = g.ID_GENRE;');

  Query.Script.Add('ALTER PROCEDURE PROC_EMPRUNTS');
  Query.Script.Add('RETURNS (');
  Query.Script.Add('    ID_EDITION CHAR(38),');
  Query.Script.Add('    ID_ALBUM CHAR(38),');
  Query.Script.Add('    TITREALBUM VARCHAR(150),');
  Query.Script.Add('    ID_SERIE CHAR(38),');
  Query.Script.Add('    TITRESERIE VARCHAR(150),');
  Query.Script.Add('    PRETE SMALLINT,');
  Query.Script.Add('    ID_EMPRUNTEUR CHAR(38),');
  Query.Script.Add('    NOMEMPRUNTEUR VARCHAR(150),');
  Query.Script.Add('    PRETEMPRUNT SMALLINT,');
  Query.Script.Add('    DATEEMPRUNT TIMESTAMP)');
  Query.Script.Add('AS');
  Query.Script.Add('BEGIN');
  Query.Script.Add('  FOR SELECT Ed.ID_EDITION,');
  Query.Script.Add('             A.ID_ALBUM,');
  Query.Script.Add('             A.titrealbum,');
  Query.Script.Add('             A.id_serie,');
  Query.Script.Add('             A.titreserie,');
  Query.Script.Add('             Ed.prete,');
  Query.Script.Add('             E.ID_EMPRUNTEUR,');
  Query.Script.Add('             E.NomEmprunteur,');
  Query.Script.Add('             S.PretEmprunt,');
  Query.Script.Add('             S.DateEmprunt');
  Query.Script.Add('      FROM VW_LISTE_ALBUMS A');
  Query.Script.Add('        INNER JOIN EDITIONS Ed ON A.ID_ALBUM = Ed.id_album');
  Query.Script.Add('        INNER JOIN STATUT S ON Ed.ID_EDITION = S.id_edition');
  Query.Script.Add('        INNER JOIN EMPRUNTEURS E ON E.ID_EMPRUNTEUR = S.id_emprunteur');
  Query.Script.Add('      ORDER BY S.DateEmprunt DESC');
  Query.Script.Add('      INTO :ID_EDITION,');
  Query.Script.Add('           :ID_ALBUM,');
  Query.Script.Add('           :TITREALBUM,');
  Query.Script.Add('           :ID_SERIE,');
  Query.Script.Add('           :TITRESERIE,');
  Query.Script.Add('           :PRETE,');
  Query.Script.Add('           :ID_Emprunteur,');
  Query.Script.Add('           :NomEmprunteur,');
  Query.Script.Add('           :PretEmprunt,');
  Query.Script.Add('           :DateEmprunt');
  Query.Script.Add('  DO');
  Query.Script.Add('  BEGIN');
  Query.Script.Add('    SUSPEND;');
  Query.Script.Add('  END');
  Query.Script.Add('end;');

  Query.Script.Add('ALTER PROCEDURE ALBUMS_BY_INITIALE (');
  Query.Script.Add('    initiale char(1),');
  Query.Script.Add('    filtre varchar(125))');
  Query.Script.Add('returns (');
  Query.Script.Add('    id_album char(38),');
  Query.Script.Add('    titrealbum varchar(150),');
  Query.Script.Add('    tome smallint,');
  Query.Script.Add('    tomedebut smallint,');
  Query.Script.Add('    tomefin smallint,');
  Query.Script.Add('    horsserie smallint,');
  Query.Script.Add('    integrale smallint,');
  Query.Script.Add('    moisparution smallint,');
  Query.Script.Add('    anneeparution smallint,');
  Query.Script.Add('    id_serie char(38),');
  Query.Script.Add('    titreserie varchar(150),');
  Query.Script.Add('    achat smallint,');
  Query.Script.Add('    complet integer)');
  Query.Script.Add('as');
  Query.Script.Add('declare variable swhere varchar(133);');
  Query.Script.Add('BEGIN');
  Query.Script.Add('  swhere = '''';');
  Query.Script.Add('  if (filtre is not null and filtre <> '''') then swhere = '' and '' || filtre || '' '';');
  Query.Script.Add('  FOR execute statement');
  Query.Script.Add('     ''SELECT a.ID_ALBUM,');
  Query.Script.Add('             a.TITREALBUM,');
  Query.Script.Add('             a.TOME,');
  Query.Script.Add('             a.TOMEDEBUT,');
  Query.Script.Add('             a.TOMEFIN,');
  Query.Script.Add('             a.HORSSERIE,');
  Query.Script.Add('             a.INTEGRALE,');
  Query.Script.Add('             a.MOISPARUTION,');
  Query.Script.Add('             a.ANNEEPARUTION,');
  Query.Script.Add('             a.ID_SERIE,');
  Query.Script.Add('             s.TITRESERIE,');
  Query.Script.Add('             a.ACHAT,');
  Query.Script.Add('             a.COMPLET');
  Query.Script.Add('      FROM ALBUMS a LEFT JOIN SERIES s ON s.ID_SERIE = a.id_serie');
  Query.Script.Add('      WHERE coalesce(a.initialetitrealbum, s.initialetitreserie) = '''''' ||: INITIALE || '''''' '' || swhere ||');
  Query.Script.Add
    ('      ''ORDER BY coalesce(UPPERTITREALBUM, UPPERTITRESERIE), HORSSERIE NULLS FIRST, INTEGRALE NULLS FIRST, TOME NULLS FIRST, TOMEDEBUT NULLS FIRST, TOMEFIN NULLS FIRST, ANNEEPARUTION NULLS FIRST, MOISPARUTION NULLS FIRST ''');
  Query.Script.Add('      INTO :ID_ALBUM,');
  Query.Script.Add('           :TITREALBUM,');
  Query.Script.Add('           :TOME,');
  Query.Script.Add('           :TOMEDEBUT,');
  Query.Script.Add('           :TOMEFIN,');
  Query.Script.Add('           :HORSSERIE,');
  Query.Script.Add('           :INTEGRALE,');
  Query.Script.Add('           :MOISPARUTION,');
  Query.Script.Add('           :ANNEEPARUTION,');
  Query.Script.Add('           :ID_SERIE,');
  Query.Script.Add('           :TITRESERIE,');
  Query.Script.Add('           :ACHAT,');
  Query.Script.Add('           :COMPLET');
  Query.Script.Add('  DO');
  Query.Script.Add('  BEGIN');
  Query.Script.Add('    SUSPEND;');
  Query.Script.Add('  END');
  Query.Script.Add('end;');

  Query.ExecuteScript;
end;

initialization

RegisterFBUpdate('1.2.3.25', @MAJ1_2_3_25);

end.
