package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuteursSeriesId generated by hbm2java
 */
@Embeddable
public class AuteursSeriesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idSerie;
	private String idPersonne;
	private short metier;

	public AuteursSeriesId() {
	}

	public AuteursSeriesId(String idSerie, String idPersonne, short metier) {
		this.idSerie = idSerie;
		this.idPersonne = idPersonne;
		this.metier = metier;
	}

	@Column(name = "ID_SERIE", nullable = false, length = 38)
	public String getIdSerie() {
		return this.idSerie;
	}

	public void setIdSerie(String idSerie) {
		this.idSerie = idSerie;
	}

	@Column(name = "ID_PERSONNE", nullable = false, length = 38)
	public String getIdPersonne() {
		return this.idPersonne;
	}

	public void setIdPersonne(String idPersonne) {
		this.idPersonne = idPersonne;
	}

	@Column(name = "METIER", nullable = false)
	public short getMetier() {
		return this.metier;
	}

	public void setMetier(short metier) {
		this.metier = metier;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuteursSeriesId))
			return false;
		AuteursSeriesId castOther = (AuteursSeriesId) other;

		return ((this.getIdSerie() == castOther.getIdSerie()) || (this
				.getIdSerie() != null && castOther.getIdSerie() != null && this
				.getIdSerie().equals(castOther.getIdSerie())))
				&& ((this.getIdPersonne() == castOther.getIdPersonne()) || (this
						.getIdPersonne() != null
						&& castOther.getIdPersonne() != null && this
						.getIdPersonne().equals(castOther.getIdPersonne())))
				&& (this.getMetier() == castOther.getMetier());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdSerie() == null ? 0 : this.getIdSerie().hashCode());
		result = 37
				* result
				+ (getIdPersonne() == null ? 0 : this.getIdPersonne()
						.hashCode());
		result = 37 * result + this.getMetier();
		return result;
	}

}
