package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CotesId generated by hbm2java
 */
@Embeddable
public class CotesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short anneecote;
	private String idEdition;

	public CotesId() {
	}

	public CotesId(short anneecote, String idEdition) {
		this.anneecote = anneecote;
		this.idEdition = idEdition;
	}

	@Column(name = "ANNEECOTE", nullable = false)
	public short getAnneecote() {
		return this.anneecote;
	}

	public void setAnneecote(short anneecote) {
		this.anneecote = anneecote;
	}

	@Column(name = "ID_EDITION", nullable = false, length = 38)
	public String getIdEdition() {
		return this.idEdition;
	}

	public void setIdEdition(String idEdition) {
		this.idEdition = idEdition;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CotesId))
			return false;
		CotesId castOther = (CotesId) other;

		return (this.getAnneecote() == castOther.getAnneecote())
				&& ((this.getIdEdition() == castOther.getIdEdition()) || (this
						.getIdEdition() != null
						&& castOther.getIdEdition() != null && this
						.getIdEdition().equals(castOther.getIdEdition())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAnneecote();
		result = 37 * result
				+ (getIdEdition() == null ? 0 : this.getIdEdition().hashCode());
		return result;
	}

}
