package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Couvertures generated by hbm2java
 */
@Entity
@Table(name = "COUVERTURES")
public class Couvertures implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idCouverture;
	private Albums albums;
	private String idEdition;
	private Integer ordre;
	private Short stockagecouverture;
	private byte[] imagecouverture;
	private Date dcCouvertures;
	private Date dmCouvertures;
	private String fichiercouverture;
	private String categorieimage;

	public Couvertures() {
	}

	public Couvertures(String idCouverture, Date dcCouvertures,
			Date dmCouvertures) {
		this.idCouverture = idCouverture;
		this.dcCouvertures = dcCouvertures;
		this.dmCouvertures = dmCouvertures;
	}

	public Couvertures(String idCouverture, Albums albums, String idEdition,
			Integer ordre, Short stockagecouverture, byte[] imagecouverture,
			Date dcCouvertures, Date dmCouvertures, String fichiercouverture,
			String categorieimage) {
		this.idCouverture = idCouverture;
		this.albums = albums;
		this.idEdition = idEdition;
		this.ordre = ordre;
		this.stockagecouverture = stockagecouverture;
		this.imagecouverture = imagecouverture;
		this.dcCouvertures = dcCouvertures;
		this.dmCouvertures = dmCouvertures;
		this.fichiercouverture = fichiercouverture;
		this.categorieimage = categorieimage;
	}

	@Id
	@Column(name = "ID_COUVERTURE", unique = true, nullable = false, length = 38)
	public String getIdCouverture() {
		return this.idCouverture;
	}

	public void setIdCouverture(String idCouverture) {
		this.idCouverture = idCouverture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ALBUM")
	public Albums getAlbums() {
		return this.albums;
	}

	public void setAlbums(Albums albums) {
		this.albums = albums;
	}

	@Column(name = "ID_EDITION", length = 38)
	public String getIdEdition() {
		return this.idEdition;
	}

	public void setIdEdition(String idEdition) {
		this.idEdition = idEdition;
	}

	@Column(name = "ORDRE")
	public Integer getOrdre() {
		return this.ordre;
	}

	public void setOrdre(Integer ordre) {
		this.ordre = ordre;
	}

	@Column(name = "STOCKAGECOUVERTURE")
	public Short getStockagecouverture() {
		return this.stockagecouverture;
	}

	public void setStockagecouverture(Short stockagecouverture) {
		this.stockagecouverture = stockagecouverture;
	}

	@Column(name = "IMAGECOUVERTURE")
	public byte[] getImagecouverture() {
		return this.imagecouverture;
	}

	public void setImagecouverture(byte[] imagecouverture) {
		this.imagecouverture = imagecouverture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_COUVERTURES", nullable = false, length = 19)
	public Date getDcCouvertures() {
		return this.dcCouvertures;
	}

	public void setDcCouvertures(Date dcCouvertures) {
		this.dcCouvertures = dcCouvertures;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_COUVERTURES", nullable = false, length = 19)
	public Date getDmCouvertures() {
		return this.dmCouvertures;
	}

	public void setDmCouvertures(Date dmCouvertures) {
		this.dmCouvertures = dmCouvertures;
	}

	@Column(name = "FICHIERCOUVERTURE")
	public String getFichiercouverture() {
		return this.fichiercouverture;
	}

	public void setFichiercouverture(String fichiercouverture) {
		this.fichiercouverture = fichiercouverture;
	}

	@Column(name = "CATEGORIEIMAGE", length = 38)
	public String getCategorieimage() {
		return this.categorieimage;
	}

	public void setCategorieimage(String categorieimage) {
		this.categorieimage = categorieimage;
	}

}
