package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Criteres generated by hbm2java
 */
@Entity
@Table(name = "CRITERES")
public class Criteres implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CriteresId id;

	public Criteres() {
	}

	public Criteres(CriteresId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idCritere", column = @Column(name = "ID_CRITERE", nullable = false, length = 38)),
			@AttributeOverride(name = "typeCritere", column = @Column(name = "TYPE_CRITERE", length = 20)),
			@AttributeOverride(name = "refcritere", column = @Column(name = "REFCRITERE", nullable = false)),
			@AttributeOverride(name = "dcCritere", column = @Column(name = "DC_CRITERE", nullable = false, length = 19)),
			@AttributeOverride(name = "dmCritere", column = @Column(name = "DM_CRITERE", nullable = false, length = 19)),
			@AttributeOverride(name = "critere", column = @Column(name = "CRITERE", length = 20)) })
	public CriteresId getId() {
		return this.id;
	}

	public void setId(CriteresId id) {
		this.id = id;
	}

}
