package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CriteresId generated by hbm2java
 */
@Embeddable
public class CriteresId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idCritere;
	private String typeCritere;
	private int refcritere;
	private Date dcCritere;
	private Date dmCritere;
	private String critere;

	public CriteresId() {
	}

	public CriteresId(String idCritere, int refcritere, Date dcCritere,
			Date dmCritere) {
		this.idCritere = idCritere;
		this.refcritere = refcritere;
		this.dcCritere = dcCritere;
		this.dmCritere = dmCritere;
	}

	public CriteresId(String idCritere, String typeCritere, int refcritere,
			Date dcCritere, Date dmCritere, String critere) {
		this.idCritere = idCritere;
		this.typeCritere = typeCritere;
		this.refcritere = refcritere;
		this.dcCritere = dcCritere;
		this.dmCritere = dmCritere;
		this.critere = critere;
	}

	@Column(name = "ID_CRITERE", nullable = false, length = 38)
	public String getIdCritere() {
		return this.idCritere;
	}

	public void setIdCritere(String idCritere) {
		this.idCritere = idCritere;
	}

	@Column(name = "TYPE_CRITERE", length = 20)
	public String getTypeCritere() {
		return this.typeCritere;
	}

	public void setTypeCritere(String typeCritere) {
		this.typeCritere = typeCritere;
	}

	@Column(name = "REFCRITERE", nullable = false)
	public int getRefcritere() {
		return this.refcritere;
	}

	public void setRefcritere(int refcritere) {
		this.refcritere = refcritere;
	}

	@Column(name = "DC_CRITERE", nullable = false, length = 19)
	public Date getDcCritere() {
		return this.dcCritere;
	}

	public void setDcCritere(Date dcCritere) {
		this.dcCritere = dcCritere;
	}

	@Column(name = "DM_CRITERE", nullable = false, length = 19)
	public Date getDmCritere() {
		return this.dmCritere;
	}

	public void setDmCritere(Date dmCritere) {
		this.dmCritere = dmCritere;
	}

	@Column(name = "CRITERE", length = 20)
	public String getCritere() {
		return this.critere;
	}

	public void setCritere(String critere) {
		this.critere = critere;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CriteresId))
			return false;
		CriteresId castOther = (CriteresId) other;

		return ((this.getIdCritere() == castOther.getIdCritere()) || (this
				.getIdCritere() != null && castOther.getIdCritere() != null && this
				.getIdCritere().equals(castOther.getIdCritere())))
				&& ((this.getTypeCritere() == castOther.getTypeCritere()) || (this
						.getTypeCritere() != null
						&& castOther.getTypeCritere() != null && this
						.getTypeCritere().equals(castOther.getTypeCritere())))
				&& (this.getRefcritere() == castOther.getRefcritere())
				&& ((this.getDcCritere() == castOther.getDcCritere()) || (this
						.getDcCritere() != null
						&& castOther.getDcCritere() != null && this
						.getDcCritere().equals(castOther.getDcCritere())))
				&& ((this.getDmCritere() == castOther.getDmCritere()) || (this
						.getDmCritere() != null
						&& castOther.getDmCritere() != null && this
						.getDmCritere().equals(castOther.getDmCritere())))
				&& ((this.getCritere() == castOther.getCritere()) || (this
						.getCritere() != null && castOther.getCritere() != null && this
						.getCritere().equals(castOther.getCritere())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdCritere() == null ? 0 : this.getIdCritere().hashCode());
		result = 37
				* result
				+ (getTypeCritere() == null ? 0 : this.getTypeCritere()
						.hashCode());
		result = 37 * result + this.getRefcritere();
		result = 37 * result
				+ (getDcCritere() == null ? 0 : this.getDcCritere().hashCode());
		result = 37 * result
				+ (getDmCritere() == null ? 0 : this.getDmCritere().hashCode());
		result = 37 * result
				+ (getCritere() == null ? 0 : this.getCritere().hashCode());
		return result;
	}

}
