package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Editions generated by hbm2java
 */
@Entity
@Table(name = "EDITIONS")
public class Editions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idEdition;
	private Editeurs editeurs;
	private Albums albums;
	private String idCollection;
	private Short anneeedition;
	private BigDecimal prix;
	private Short vo;
	private Short couleur;
	private Short prete;
	private Short stock;
	private Short dedicace;
	private Date dateachat;
	private Short gratuit;
	private Short offert;
	private Integer nombredepages;
	private Short anneecote;
	private BigDecimal prixcote;
	private Date dcEditions;
	private Date dmEditions;
	private String isbn;
	private String numeroperso;
	private String notes;
	private String etat;
	private String reliure;
	private String typeedition;
	private String orientation;
	private String formatedition;
	private String senslecture;
	private Set<Statut> statuts = new HashSet<Statut>(0);
	private Set<Cotes> coteses = new HashSet<Cotes>(0);

	public Editions() {
	}

	public Editions(String idEdition, Editeurs editeurs, Albums albums,
			Date dcEditions, Date dmEditions) {
		this.idEdition = idEdition;
		this.editeurs = editeurs;
		this.albums = albums;
		this.dcEditions = dcEditions;
		this.dmEditions = dmEditions;
	}

	public Editions(String idEdition, Editeurs editeurs, Albums albums,
			String idCollection, Short anneeedition, BigDecimal prix, Short vo,
			Short couleur, Short prete, Short stock, Short dedicace,
			Date dateachat, Short gratuit, Short offert, Integer nombredepages,
			Short anneecote, BigDecimal prixcote, Date dcEditions,
			Date dmEditions, String isbn, String numeroperso, String notes,
			String etat, String reliure, String typeedition,
			String orientation, String formatedition, String senslecture,
			Set<Statut> statuts, Set<Cotes> coteses) {
		this.idEdition = idEdition;
		this.editeurs = editeurs;
		this.albums = albums;
		this.idCollection = idCollection;
		this.anneeedition = anneeedition;
		this.prix = prix;
		this.vo = vo;
		this.couleur = couleur;
		this.prete = prete;
		this.stock = stock;
		this.dedicace = dedicace;
		this.dateachat = dateachat;
		this.gratuit = gratuit;
		this.offert = offert;
		this.nombredepages = nombredepages;
		this.anneecote = anneecote;
		this.prixcote = prixcote;
		this.dcEditions = dcEditions;
		this.dmEditions = dmEditions;
		this.isbn = isbn;
		this.numeroperso = numeroperso;
		this.notes = notes;
		this.etat = etat;
		this.reliure = reliure;
		this.typeedition = typeedition;
		this.orientation = orientation;
		this.formatedition = formatedition;
		this.senslecture = senslecture;
		this.statuts = statuts;
		this.coteses = coteses;
	}

	@Id
	@Column(name = "ID_EDITION", unique = true, nullable = false, length = 38)
	public String getIdEdition() {
		return this.idEdition;
	}

	public void setIdEdition(String idEdition) {
		this.idEdition = idEdition;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EDITEUR", nullable = false)
	public Editeurs getEditeurs() {
		return this.editeurs;
	}

	public void setEditeurs(Editeurs editeurs) {
		this.editeurs = editeurs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ALBUM", nullable = false)
	public Albums getAlbums() {
		return this.albums;
	}

	public void setAlbums(Albums albums) {
		this.albums = albums;
	}

	@Column(name = "ID_COLLECTION", length = 38)
	public String getIdCollection() {
		return this.idCollection;
	}

	public void setIdCollection(String idCollection) {
		this.idCollection = idCollection;
	}

	@Column(name = "ANNEEEDITION")
	public Short getAnneeedition() {
		return this.anneeedition;
	}

	public void setAnneeedition(Short anneeedition) {
		this.anneeedition = anneeedition;
	}

	@Column(name = "PRIX", precision = 15)
	public BigDecimal getPrix() {
		return this.prix;
	}

	public void setPrix(BigDecimal prix) {
		this.prix = prix;
	}

	@Column(name = "VO")
	public Short getVo() {
		return this.vo;
	}

	public void setVo(Short vo) {
		this.vo = vo;
	}

	@Column(name = "COULEUR")
	public Short getCouleur() {
		return this.couleur;
	}

	public void setCouleur(Short couleur) {
		this.couleur = couleur;
	}

	@Column(name = "PRETE")
	public Short getPrete() {
		return this.prete;
	}

	public void setPrete(Short prete) {
		this.prete = prete;
	}

	@Column(name = "STOCK")
	public Short getStock() {
		return this.stock;
	}

	public void setStock(Short stock) {
		this.stock = stock;
	}

	@Column(name = "DEDICACE")
	public Short getDedicace() {
		return this.dedicace;
	}

	public void setDedicace(Short dedicace) {
		this.dedicace = dedicace;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEACHAT", length = 10)
	public Date getDateachat() {
		return this.dateachat;
	}

	public void setDateachat(Date dateachat) {
		this.dateachat = dateachat;
	}

	@Column(name = "GRATUIT")
	public Short getGratuit() {
		return this.gratuit;
	}

	public void setGratuit(Short gratuit) {
		this.gratuit = gratuit;
	}

	@Column(name = "OFFERT")
	public Short getOffert() {
		return this.offert;
	}

	public void setOffert(Short offert) {
		this.offert = offert;
	}

	@Column(name = "NOMBREDEPAGES")
	public Integer getNombredepages() {
		return this.nombredepages;
	}

	public void setNombredepages(Integer nombredepages) {
		this.nombredepages = nombredepages;
	}

	@Column(name = "ANNEECOTE")
	public Short getAnneecote() {
		return this.anneecote;
	}

	public void setAnneecote(Short anneecote) {
		this.anneecote = anneecote;
	}

	@Column(name = "PRIXCOTE", precision = 15)
	public BigDecimal getPrixcote() {
		return this.prixcote;
	}

	public void setPrixcote(BigDecimal prixcote) {
		this.prixcote = prixcote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_EDITIONS", nullable = false, length = 19)
	public Date getDcEditions() {
		return this.dcEditions;
	}

	public void setDcEditions(Date dcEditions) {
		this.dcEditions = dcEditions;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_EDITIONS", nullable = false, length = 19)
	public Date getDmEditions() {
		return this.dmEditions;
	}

	public void setDmEditions(Date dmEditions) {
		this.dmEditions = dmEditions;
	}

	@Column(name = "ISBN", length = 13)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "NUMEROPERSO", length = 25)
	public String getNumeroperso() {
		return this.numeroperso;
	}

	public void setNumeroperso(String numeroperso) {
		this.numeroperso = numeroperso;
	}

	@Column(name = "NOTES", length = 0)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "ETAT", length = 38)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@Column(name = "RELIURE", length = 38)
	public String getReliure() {
		return this.reliure;
	}

	public void setReliure(String reliure) {
		this.reliure = reliure;
	}

	@Column(name = "TYPEEDITION", length = 38)
	public String getTypeedition() {
		return this.typeedition;
	}

	public void setTypeedition(String typeedition) {
		this.typeedition = typeedition;
	}

	@Column(name = "ORIENTATION", length = 38)
	public String getOrientation() {
		return this.orientation;
	}

	public void setOrientation(String orientation) {
		this.orientation = orientation;
	}

	@Column(name = "FORMATEDITION", length = 38)
	public String getFormatedition() {
		return this.formatedition;
	}

	public void setFormatedition(String formatedition) {
		this.formatedition = formatedition;
	}

	@Column(name = "SENSLECTURE", length = 38)
	public String getSenslecture() {
		return this.senslecture;
	}

	public void setSenslecture(String senslecture) {
		this.senslecture = senslecture;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "editions")
	public Set<Statut> getStatuts() {
		return this.statuts;
	}

	public void setStatuts(Set<Statut> statuts) {
		this.statuts = statuts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "editions")
	public Set<Cotes> getCoteses() {
		return this.coteses;
	}

	public void setCoteses(Set<Cotes> coteses) {
		this.coteses = coteses;
	}

}
