package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Editeurs generated by hbm2java
 */
@Entity
@Table(name = "EDITEURS")
public class Editeurs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idEditeur;
	private char initialenomediteur;
	private Date dcEditeurs;
	private Date dmEditeurs;
	private String nomediteur;
	private String siteweb;
	private Set<Editions> editionses = new HashSet<Editions>(0);
	private Set<Collections> collectionses = new HashSet<Collections>(0);

	public Editeurs() {
	}

	public Editeurs(String idEditeur, char initialenomediteur, Date dcEditeurs,
			Date dmEditeurs) {
		this.idEditeur = idEditeur;
		this.initialenomediteur = initialenomediteur;
		this.dcEditeurs = dcEditeurs;
		this.dmEditeurs = dmEditeurs;
	}

	public Editeurs(String idEditeur, char initialenomediteur, Date dcEditeurs,
			Date dmEditeurs, String nomediteur, String siteweb,
			Set<Editions> editionses, Set<Collections> collectionses) {
		this.idEditeur = idEditeur;
		this.initialenomediteur = initialenomediteur;
		this.dcEditeurs = dcEditeurs;
		this.dmEditeurs = dmEditeurs;
		this.nomediteur = nomediteur;
		this.siteweb = siteweb;
		this.editionses = editionses;
		this.collectionses = collectionses;
	}

	@Id
	@Column(name = "ID_EDITEUR", unique = true, nullable = false, length = 38)
	public String getIdEditeur() {
		return this.idEditeur;
	}

	public void setIdEditeur(String idEditeur) {
		this.idEditeur = idEditeur;
	}

	@Column(name = "INITIALENOMEDITEUR", nullable = false, length = 1)
	public char getInitialenomediteur() {
		return this.initialenomediteur;
	}

	public void setInitialenomediteur(char initialenomediteur) {
		this.initialenomediteur = initialenomediteur;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_EDITEURS", nullable = false, length = 19)
	public Date getDcEditeurs() {
		return this.dcEditeurs;
	}

	public void setDcEditeurs(Date dcEditeurs) {
		this.dcEditeurs = dcEditeurs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_EDITEURS", nullable = false, length = 19)
	public Date getDmEditeurs() {
		return this.dmEditeurs;
	}

	public void setDmEditeurs(Date dmEditeurs) {
		this.dmEditeurs = dmEditeurs;
	}

	@Column(name = "NOMEDITEUR", length = 50)
	public String getNomediteur() {
		return this.nomediteur;
	}

	public void setNomediteur(String nomediteur) {
		this.nomediteur = nomediteur;
	}

	@Column(name = "SITEWEB")
	public String getSiteweb() {
		return this.siteweb;
	}

	public void setSiteweb(String siteweb) {
		this.siteweb = siteweb;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "editeurs")
	public Set<Editions> getEditionses() {
		return this.editionses;
	}

	public void setEditionses(Set<Editions> editionses) {
		this.editionses = editionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "editeurs")
	public Set<Collections> getCollectionses() {
		return this.collectionses;
	}

	public void setCollectionses(Set<Collections> collectionses) {
		this.collectionses = collectionses;
	}

}
