package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImportAssociationsId generated by hbm2java
 */
@Embeddable
public class ImportAssociationsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String chaine;
	private short typedata;
	private String parentid;

	public ImportAssociationsId() {
	}

	public ImportAssociationsId(String chaine, short typedata, String parentid) {
		this.chaine = chaine;
		this.typedata = typedata;
		this.parentid = parentid;
	}

	@Column(name = "CHAINE", nullable = false, length = 100)
	public String getChaine() {
		return this.chaine;
	}

	public void setChaine(String chaine) {
		this.chaine = chaine;
	}

	@Column(name = "TYPEDATA", nullable = false)
	public short getTypedata() {
		return this.typedata;
	}

	public void setTypedata(short typedata) {
		this.typedata = typedata;
	}

	@Column(name = "PARENTID", nullable = false, length = 38)
	public String getParentid() {
		return this.parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImportAssociationsId))
			return false;
		ImportAssociationsId castOther = (ImportAssociationsId) other;

		return ((this.getChaine() == castOther.getChaine()) || (this
				.getChaine() != null && castOther.getChaine() != null && this
				.getChaine().equals(castOther.getChaine())))
				&& (this.getTypedata() == castOther.getTypedata())
				&& ((this.getParentid() == castOther.getParentid()) || (this
						.getParentid() != null
						&& castOther.getParentid() != null && this
						.getParentid().equals(castOther.getParentid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getChaine() == null ? 0 : this.getChaine().hashCode());
		result = 37 * result + this.getTypedata();
		result = 37 * result
				+ (getParentid() == null ? 0 : this.getParentid().hashCode());
		return result;
	}

}
