package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ImportAssociations generated by hbm2java
 */
@Entity
@Table(name = "IMPORT_ASSOCIATIONS")
public class ImportAssociations implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ImportAssociationsId id;
	private String id_1;
	private Short always;

	public ImportAssociations() {
	}

	public ImportAssociations(ImportAssociationsId id, String id_1) {
		this.id = id;
		this.id_1 = id_1;
	}

	public ImportAssociations(ImportAssociationsId id, String id_1, Short always) {
		this.id = id;
		this.id_1 = id_1;
		this.always = always;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "chaine", column = @Column(name = "CHAINE", nullable = false, length = 100)),
			@AttributeOverride(name = "typedata", column = @Column(name = "TYPEDATA", nullable = false)),
			@AttributeOverride(name = "parentid", column = @Column(name = "PARENTID", nullable = false, length = 38)) })
	public ImportAssociationsId getId() {
		return this.id;
	}

	public void setId(ImportAssociationsId id) {
		this.id = id;
	}

	@Column(name = "ID", nullable = false, length = 38)
	public String getId_1() {
		return this.id_1;
	}

	public void setId_1(String id_1) {
		this.id_1 = id_1;
	}

	@Column(name = "ALWAYS")
	public Short getAlways() {
		return this.always;
	}

	public void setAlways(Short always) {
		this.always = always;
	}

}
