package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Listes generated by hbm2java
 */
@Entity
@Table(name = "LISTES", uniqueConstraints = @UniqueConstraint(columnNames = "ID_LISTE"))
public class Listes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ListesId id;
	private String idListe;
	private Integer ordre;
	private Short defaut;
	private Date dcListes;
	private Date dmListes;
	private String libelle;

	public Listes() {
	}

	public Listes(ListesId id, String idListe, Date dcListes, Date dmListes) {
		this.id = id;
		this.idListe = idListe;
		this.dcListes = dcListes;
		this.dmListes = dmListes;
	}

	public Listes(ListesId id, String idListe, Integer ordre, Short defaut,
			Date dcListes, Date dmListes, String libelle) {
		this.id = id;
		this.idListe = idListe;
		this.ordre = ordre;
		this.defaut = defaut;
		this.dcListes = dcListes;
		this.dmListes = dmListes;
		this.libelle = libelle;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "categorie", column = @Column(name = "CATEGORIE", nullable = false)),
			@AttributeOverride(name = "ref", column = @Column(name = "REF", nullable = false)) })
	public ListesId getId() {
		return this.id;
	}

	public void setId(ListesId id) {
		this.id = id;
	}

	@Column(name = "ID_LISTE", unique = true, nullable = false, length = 38)
	public String getIdListe() {
		return this.idListe;
	}

	public void setIdListe(String idListe) {
		this.idListe = idListe;
	}

	@Column(name = "ORDRE")
	public Integer getOrdre() {
		return this.ordre;
	}

	public void setOrdre(Integer ordre) {
		this.ordre = ordre;
	}

	@Column(name = "DEFAUT")
	public Short getDefaut() {
		return this.defaut;
	}

	public void setDefaut(Short defaut) {
		this.defaut = defaut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_LISTES", nullable = false, length = 19)
	public Date getDcListes() {
		return this.dcListes;
	}

	public void setDcListes(Date dcListes) {
		this.dcListes = dcListes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_LISTES", nullable = false, length = 19)
	public Date getDmListes() {
		return this.dmListes;
	}

	public void setDmListes(Date dmListes) {
		this.dmListes = dmListes;
	}

	@Column(name = "LIBELLE", length = 50)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
