package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ListesId generated by hbm2java
 */
@Embeddable
public class ListesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int categorie;
	private int ref;

	public ListesId() {
	}

	public ListesId(int categorie, int ref) {
		this.categorie = categorie;
		this.ref = ref;
	}

	@Column(name = "CATEGORIE", nullable = false)
	public int getCategorie() {
		return this.categorie;
	}

	public void setCategorie(int categorie) {
		this.categorie = categorie;
	}

	@Column(name = "REF", nullable = false)
	public int getRef() {
		return this.ref;
	}

	public void setRef(int ref) {
		this.ref = ref;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ListesId))
			return false;
		ListesId castOther = (ListesId) other;

		return (this.getCategorie() == castOther.getCategorie())
				&& (this.getRef() == castOther.getRef());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCategorie();
		result = 37 * result + this.getRef();
		return result;
	}

}
