package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Options generated by hbm2java
 */
@Entity
@Table(name = "OPTIONS", uniqueConstraints = @UniqueConstraint(columnNames = "ID_OPTION"))
public class Options implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String nomOption;
	private String idOption;
	private Date dcOptions;
	private Date dmOptions;
	private String valeur;

	public Options() {
	}

	public Options(String nomOption, String idOption, Date dcOptions,
			Date dmOptions) {
		this.nomOption = nomOption;
		this.idOption = idOption;
		this.dcOptions = dcOptions;
		this.dmOptions = dmOptions;
	}

	public Options(String nomOption, String idOption, Date dcOptions,
			Date dmOptions, String valeur) {
		this.nomOption = nomOption;
		this.idOption = idOption;
		this.dcOptions = dcOptions;
		this.dmOptions = dmOptions;
		this.valeur = valeur;
	}

	@Id
	@Column(name = "NOM_OPTION", unique = true, nullable = false, length = 15)
	public String getNomOption() {
		return this.nomOption;
	}

	public void setNomOption(String nomOption) {
		this.nomOption = nomOption;
	}

	@Column(name = "ID_OPTION", unique = true, nullable = false, length = 38)
	public String getIdOption() {
		return this.idOption;
	}

	public void setIdOption(String idOption) {
		this.idOption = idOption;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_OPTIONS", nullable = false, length = 19)
	public Date getDcOptions() {
		return this.dcOptions;
	}

	public void setDcOptions(Date dcOptions) {
		this.dcOptions = dcOptions;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_OPTIONS", nullable = false, length = 19)
	public Date getDmOptions() {
		return this.dmOptions;
	}

	public void setDmOptions(Date dmOptions) {
		this.dmOptions = dmOptions;
	}

	@Column(name = "VALEUR")
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

}
