package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OptionsScriptsId generated by hbm2java
 */
@Embeddable
public class OptionsScriptsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String script;
	private String nomOption;

	public OptionsScriptsId() {
	}

	public OptionsScriptsId(String script, String nomOption) {
		this.script = script;
		this.nomOption = nomOption;
	}

	@Column(name = "SCRIPT", nullable = false, length = 50)
	public String getScript() {
		return this.script;
	}

	public void setScript(String script) {
		this.script = script;
	}

	@Column(name = "NOM_OPTION", nullable = false, length = 50)
	public String getNomOption() {
		return this.nomOption;
	}

	public void setNomOption(String nomOption) {
		this.nomOption = nomOption;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OptionsScriptsId))
			return false;
		OptionsScriptsId castOther = (OptionsScriptsId) other;

		return ((this.getScript() == castOther.getScript()) || (this
				.getScript() != null && castOther.getScript() != null && this
				.getScript().equals(castOther.getScript())))
				&& ((this.getNomOption() == castOther.getNomOption()) || (this
						.getNomOption() != null
						&& castOther.getNomOption() != null && this
						.getNomOption().equals(castOther.getNomOption())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getScript() == null ? 0 : this.getScript().hashCode());
		result = 37 * result
				+ (getNomOption() == null ? 0 : this.getNomOption().hashCode());
		return result;
	}

}
