package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * OptionsScripts generated by hbm2java
 */
@Entity
@Table(name = "OPTIONS_SCRIPTS", uniqueConstraints = @UniqueConstraint(columnNames = "ID_OPTION"))
public class OptionsScripts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private OptionsScriptsId id;
	private String idOption;
	private Date dcOptions;
	private Date dmOptions;
	private String valeur;

	public OptionsScripts() {
	}

	public OptionsScripts(OptionsScriptsId id, String idOption, Date dcOptions,
			Date dmOptions) {
		this.id = id;
		this.idOption = idOption;
		this.dcOptions = dcOptions;
		this.dmOptions = dmOptions;
	}

	public OptionsScripts(OptionsScriptsId id, String idOption, Date dcOptions,
			Date dmOptions, String valeur) {
		this.id = id;
		this.idOption = idOption;
		this.dcOptions = dcOptions;
		this.dmOptions = dmOptions;
		this.valeur = valeur;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "script", column = @Column(name = "SCRIPT", nullable = false, length = 50)),
			@AttributeOverride(name = "nomOption", column = @Column(name = "NOM_OPTION", nullable = false, length = 50)) })
	public OptionsScriptsId getId() {
		return this.id;
	}

	public void setId(OptionsScriptsId id) {
		this.id = id;
	}

	@Column(name = "ID_OPTION", unique = true, nullable = false, length = 38)
	public String getIdOption() {
		return this.idOption;
	}

	public void setIdOption(String idOption) {
		this.idOption = idOption;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_OPTIONS", nullable = false, length = 19)
	public Date getDcOptions() {
		return this.dcOptions;
	}

	public void setDcOptions(Date dcOptions) {
		this.dcOptions = dcOptions;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_OPTIONS", nullable = false, length = 19)
	public Date getDmOptions() {
		return this.dmOptions;
	}

	public void setDmOptions(Date dmOptions) {
		this.dmOptions = dmOptions;
	}

	@Column(name = "VALEUR")
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

}
