package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parabd generated by hbm2java
 */
@Entity
@Table(name = "PARABD")
public class Parabd implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idParabd;
	private String idSerie;
	private Short achat;
	private Integer complet;
	private Short dedicace;
	private Short numerote;
	private Short annee;
	private Short anneecote;
	private BigDecimal prixcote;
	private Short prete;
	private Short stock;
	private Date dateachat;
	private BigDecimal prix;
	private Short gratuit;
	private Short offert;
	private Short stockageparabd;
	private byte[] imageparabd;
	private Character initialetitreparabd;
	private Date dcParabd;
	private Date dmParabd;
	private String titreparabd;
	private String soundextitreparabd;
	private String fichierparabd;
	private String description;
	private String categorieparabd;
	private Set<AuteursParabd> auteursParabds = new HashSet<AuteursParabd>(0);
	private Set<CotesParabd> cotesParabds = new HashSet<CotesParabd>(0);

	public Parabd() {
	}

	public Parabd(String idParabd, Date dcParabd, Date dmParabd) {
		this.idParabd = idParabd;
		this.dcParabd = dcParabd;
		this.dmParabd = dmParabd;
	}

	public Parabd(String idParabd, String idSerie, Short achat,
			Integer complet, Short dedicace, Short numerote, Short annee,
			Short anneecote, BigDecimal prixcote, Short prete, Short stock,
			Date dateachat, BigDecimal prix, Short gratuit, Short offert,
			Short stockageparabd, byte[] imageparabd,
			Character initialetitreparabd, Date dcParabd, Date dmParabd,
			String titreparabd, String soundextitreparabd,
			String fichierparabd, String description, String categorieparabd,
			Set<AuteursParabd> auteursParabds, Set<CotesParabd> cotesParabds) {
		this.idParabd = idParabd;
		this.idSerie = idSerie;
		this.achat = achat;
		this.complet = complet;
		this.dedicace = dedicace;
		this.numerote = numerote;
		this.annee = annee;
		this.anneecote = anneecote;
		this.prixcote = prixcote;
		this.prete = prete;
		this.stock = stock;
		this.dateachat = dateachat;
		this.prix = prix;
		this.gratuit = gratuit;
		this.offert = offert;
		this.stockageparabd = stockageparabd;
		this.imageparabd = imageparabd;
		this.initialetitreparabd = initialetitreparabd;
		this.dcParabd = dcParabd;
		this.dmParabd = dmParabd;
		this.titreparabd = titreparabd;
		this.soundextitreparabd = soundextitreparabd;
		this.fichierparabd = fichierparabd;
		this.description = description;
		this.categorieparabd = categorieparabd;
		this.auteursParabds = auteursParabds;
		this.cotesParabds = cotesParabds;
	}

	@Id
	@Column(name = "ID_PARABD", unique = true, nullable = false, length = 38)
	public String getIdParabd() {
		return this.idParabd;
	}

	public void setIdParabd(String idParabd) {
		this.idParabd = idParabd;
	}

	@Column(name = "ID_SERIE", length = 38)
	public String getIdSerie() {
		return this.idSerie;
	}

	public void setIdSerie(String idSerie) {
		this.idSerie = idSerie;
	}

	@Column(name = "ACHAT")
	public Short getAchat() {
		return this.achat;
	}

	public void setAchat(Short achat) {
		this.achat = achat;
	}

	@Column(name = "COMPLET")
	public Integer getComplet() {
		return this.complet;
	}

	public void setComplet(Integer complet) {
		this.complet = complet;
	}

	@Column(name = "DEDICACE")
	public Short getDedicace() {
		return this.dedicace;
	}

	public void setDedicace(Short dedicace) {
		this.dedicace = dedicace;
	}

	@Column(name = "NUMEROTE")
	public Short getNumerote() {
		return this.numerote;
	}

	public void setNumerote(Short numerote) {
		this.numerote = numerote;
	}

	@Column(name = "ANNEE")
	public Short getAnnee() {
		return this.annee;
	}

	public void setAnnee(Short annee) {
		this.annee = annee;
	}

	@Column(name = "ANNEECOTE")
	public Short getAnneecote() {
		return this.anneecote;
	}

	public void setAnneecote(Short anneecote) {
		this.anneecote = anneecote;
	}

	@Column(name = "PRIXCOTE", precision = 15)
	public BigDecimal getPrixcote() {
		return this.prixcote;
	}

	public void setPrixcote(BigDecimal prixcote) {
		this.prixcote = prixcote;
	}

	@Column(name = "PRETE")
	public Short getPrete() {
		return this.prete;
	}

	public void setPrete(Short prete) {
		this.prete = prete;
	}

	@Column(name = "STOCK")
	public Short getStock() {
		return this.stock;
	}

	public void setStock(Short stock) {
		this.stock = stock;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEACHAT", length = 10)
	public Date getDateachat() {
		return this.dateachat;
	}

	public void setDateachat(Date dateachat) {
		this.dateachat = dateachat;
	}

	@Column(name = "PRIX", precision = 15)
	public BigDecimal getPrix() {
		return this.prix;
	}

	public void setPrix(BigDecimal prix) {
		this.prix = prix;
	}

	@Column(name = "GRATUIT")
	public Short getGratuit() {
		return this.gratuit;
	}

	public void setGratuit(Short gratuit) {
		this.gratuit = gratuit;
	}

	@Column(name = "OFFERT")
	public Short getOffert() {
		return this.offert;
	}

	public void setOffert(Short offert) {
		this.offert = offert;
	}

	@Column(name = "STOCKAGEPARABD")
	public Short getStockageparabd() {
		return this.stockageparabd;
	}

	public void setStockageparabd(Short stockageparabd) {
		this.stockageparabd = stockageparabd;
	}

	@Column(name = "IMAGEPARABD")
	public byte[] getImageparabd() {
		return this.imageparabd;
	}

	public void setImageparabd(byte[] imageparabd) {
		this.imageparabd = imageparabd;
	}

	@Column(name = "INITIALETITREPARABD", length = 1)
	public Character getInitialetitreparabd() {
		return this.initialetitreparabd;
	}

	public void setInitialetitreparabd(Character initialetitreparabd) {
		this.initialetitreparabd = initialetitreparabd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_PARABD", nullable = false, length = 19)
	public Date getDcParabd() {
		return this.dcParabd;
	}

	public void setDcParabd(Date dcParabd) {
		this.dcParabd = dcParabd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_PARABD", nullable = false, length = 19)
	public Date getDmParabd() {
		return this.dmParabd;
	}

	public void setDmParabd(Date dmParabd) {
		this.dmParabd = dmParabd;
	}

	@Column(name = "TITREPARABD", length = 150)
	public String getTitreparabd() {
		return this.titreparabd;
	}

	public void setTitreparabd(String titreparabd) {
		this.titreparabd = titreparabd;
	}

	@Column(name = "SOUNDEXTITREPARABD", length = 30)
	public String getSoundextitreparabd() {
		return this.soundextitreparabd;
	}

	public void setSoundextitreparabd(String soundextitreparabd) {
		this.soundextitreparabd = soundextitreparabd;
	}

	@Column(name = "FICHIERPARABD")
	public String getFichierparabd() {
		return this.fichierparabd;
	}

	public void setFichierparabd(String fichierparabd) {
		this.fichierparabd = fichierparabd;
	}

	@Column(name = "DESCRIPTION", length = 0)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CATEGORIEPARABD", length = 38)
	public String getCategorieparabd() {
		return this.categorieparabd;
	}

	public void setCategorieparabd(String categorieparabd) {
		this.categorieparabd = categorieparabd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parabd")
	public Set<AuteursParabd> getAuteursParabds() {
		return this.auteursParabds;
	}

	public void setAuteursParabds(Set<AuteursParabd> auteursParabds) {
		this.auteursParabds = auteursParabds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parabd")
	public Set<CotesParabd> getCotesParabds() {
		return this.cotesParabds;
	}

	public void setCotesParabds(Set<CotesParabd> cotesParabds) {
		this.cotesParabds = cotesParabds;
	}

}
