package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personnes generated by hbm2java
 */
@Entity
@Table(name = "PERSONNES")
public class Personnes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idPersonne;
	private Character initialenompersonne;
	private Date dcPersonnes;
	private Date dmPersonnes;
	private String nompersonne;
	private String siteweb;
	private String biographie;
	private Set<AuteursParabd> auteursParabds = new HashSet<AuteursParabd>(0);
	private Set<Auteurs> auteurses = new HashSet<Auteurs>(0);
	private Set<AuteursSeries> auteursSerieses = new HashSet<AuteursSeries>(0);

	public Personnes() {
	}

	public Personnes(String idPersonne, Date dcPersonnes, Date dmPersonnes) {
		this.idPersonne = idPersonne;
		this.dcPersonnes = dcPersonnes;
		this.dmPersonnes = dmPersonnes;
	}

	public Personnes(String idPersonne, Character initialenompersonne,
			Date dcPersonnes, Date dmPersonnes, String nompersonne,
			String siteweb, String biographie,
			Set<AuteursParabd> auteursParabds, Set<Auteurs> auteurses,
			Set<AuteursSeries> auteursSerieses) {
		this.idPersonne = idPersonne;
		this.initialenompersonne = initialenompersonne;
		this.dcPersonnes = dcPersonnes;
		this.dmPersonnes = dmPersonnes;
		this.nompersonne = nompersonne;
		this.siteweb = siteweb;
		this.biographie = biographie;
		this.auteursParabds = auteursParabds;
		this.auteurses = auteurses;
		this.auteursSerieses = auteursSerieses;
	}

	@Id
	@Column(name = "ID_PERSONNE", unique = true, nullable = false, length = 38)
	public String getIdPersonne() {
		return this.idPersonne;
	}

	public void setIdPersonne(String idPersonne) {
		this.idPersonne = idPersonne;
	}

	@Column(name = "INITIALENOMPERSONNE", length = 1)
	public Character getInitialenompersonne() {
		return this.initialenompersonne;
	}

	public void setInitialenompersonne(Character initialenompersonne) {
		this.initialenompersonne = initialenompersonne;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_PERSONNES", nullable = false, length = 19)
	public Date getDcPersonnes() {
		return this.dcPersonnes;
	}

	public void setDcPersonnes(Date dcPersonnes) {
		this.dcPersonnes = dcPersonnes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_PERSONNES", nullable = false, length = 19)
	public Date getDmPersonnes() {
		return this.dmPersonnes;
	}

	public void setDmPersonnes(Date dmPersonnes) {
		this.dmPersonnes = dmPersonnes;
	}

	@Column(name = "NOMPERSONNE", length = 150)
	public String getNompersonne() {
		return this.nompersonne;
	}

	public void setNompersonne(String nompersonne) {
		this.nompersonne = nompersonne;
	}

	@Column(name = "SITEWEB")
	public String getSiteweb() {
		return this.siteweb;
	}

	public void setSiteweb(String siteweb) {
		this.siteweb = siteweb;
	}

	@Column(name = "BIOGRAPHIE", length = 0)
	public String getBiographie() {
		return this.biographie;
	}

	public void setBiographie(String biographie) {
		this.biographie = biographie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnes")
	public Set<AuteursParabd> getAuteursParabds() {
		return this.auteursParabds;
	}

	public void setAuteursParabds(Set<AuteursParabd> auteursParabds) {
		this.auteursParabds = auteursParabds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnes")
	public Set<Auteurs> getAuteurses() {
		return this.auteurses;
	}

	public void setAuteurses(Set<Auteurs> auteurses) {
		this.auteurses = auteurses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnes")
	public Set<AuteursSeries> getAuteursSerieses() {
		return this.auteursSerieses;
	}

	public void setAuteursSerieses(Set<AuteursSeries> auteursSerieses) {
		this.auteursSerieses = auteursSerieses;
	}

}
