package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Series generated by hbm2java
 */
@Entity
@Table(name = "SERIES")
public class Series implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idSerie;
	private String idEditeur;
	private String idCollection;
	private Short terminee;
	private Short complete;
	private Short suivremanquants;
	private Short suivresorties;
	private char initialetitreserie;
	private Date dcSeries;
	private Date dmSeries;
	private Integer nbAlbums;
	private Short vo;
	private Short couleur;
	private String titreserie;
	private String soundextitreserie;
	private Short notation;
	private String siteweb;
	private String sujetserie;
	private String remarquesserie;
	private String etat;
	private String reliure;
	private String typeedition;
	private String orientation;
	private String formatedition;
	private String senslecture;
	private Set<AuteursSeries> auteursSerieses = new HashSet<AuteursSeries>(0);
	private Set<Genreseries> genreserieses = new HashSet<Genreseries>(0);

	public Series() {
	}

	public Series(String idSerie, String idEditeur, char initialetitreserie,
			Date dcSeries, Date dmSeries) {
		this.idSerie = idSerie;
		this.idEditeur = idEditeur;
		this.initialetitreserie = initialetitreserie;
		this.dcSeries = dcSeries;
		this.dmSeries = dmSeries;
	}

	public Series(String idSerie, String idEditeur, String idCollection,
			Short terminee, Short complete, Short suivremanquants,
			Short suivresorties, char initialetitreserie, Date dcSeries,
			Date dmSeries, Integer nbAlbums, Short vo, Short couleur,
			String titreserie, String soundextitreserie, Short notation,
			String siteweb, String sujetserie, String remarquesserie,
			String etat, String reliure, String typeedition,
			String orientation, String formatedition, String senslecture,
			Set<AuteursSeries> auteursSerieses, Set<Genreseries> genreserieses) {
		this.idSerie = idSerie;
		this.idEditeur = idEditeur;
		this.idCollection = idCollection;
		this.terminee = terminee;
		this.complete = complete;
		this.suivremanquants = suivremanquants;
		this.suivresorties = suivresorties;
		this.initialetitreserie = initialetitreserie;
		this.dcSeries = dcSeries;
		this.dmSeries = dmSeries;
		this.nbAlbums = nbAlbums;
		this.vo = vo;
		this.couleur = couleur;
		this.titreserie = titreserie;
		this.soundextitreserie = soundextitreserie;
		this.notation = notation;
		this.siteweb = siteweb;
		this.sujetserie = sujetserie;
		this.remarquesserie = remarquesserie;
		this.etat = etat;
		this.reliure = reliure;
		this.typeedition = typeedition;
		this.orientation = orientation;
		this.formatedition = formatedition;
		this.senslecture = senslecture;
		this.auteursSerieses = auteursSerieses;
		this.genreserieses = genreserieses;
	}

	@Id
	@Column(name = "ID_SERIE", unique = true, nullable = false, length = 38)
	public String getIdSerie() {
		return this.idSerie;
	}

	public void setIdSerie(String idSerie) {
		this.idSerie = idSerie;
	}

	@Column(name = "ID_EDITEUR", nullable = false, length = 38)
	public String getIdEditeur() {
		return this.idEditeur;
	}

	public void setIdEditeur(String idEditeur) {
		this.idEditeur = idEditeur;
	}

	@Column(name = "ID_COLLECTION", length = 38)
	public String getIdCollection() {
		return this.idCollection;
	}

	public void setIdCollection(String idCollection) {
		this.idCollection = idCollection;
	}

	@Column(name = "TERMINEE")
	public Short getTerminee() {
		return this.terminee;
	}

	public void setTerminee(Short terminee) {
		this.terminee = terminee;
	}

	@Column(name = "COMPLETE")
	public Short getComplete() {
		return this.complete;
	}

	public void setComplete(Short complete) {
		this.complete = complete;
	}

	@Column(name = "SUIVREMANQUANTS")
	public Short getSuivremanquants() {
		return this.suivremanquants;
	}

	public void setSuivremanquants(Short suivremanquants) {
		this.suivremanquants = suivremanquants;
	}

	@Column(name = "SUIVRESORTIES")
	public Short getSuivresorties() {
		return this.suivresorties;
	}

	public void setSuivresorties(Short suivresorties) {
		this.suivresorties = suivresorties;
	}

	@Column(name = "INITIALETITRESERIE", nullable = false, length = 1)
	public char getInitialetitreserie() {
		return this.initialetitreserie;
	}

	public void setInitialetitreserie(char initialetitreserie) {
		this.initialetitreserie = initialetitreserie;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_SERIES", nullable = false, length = 19)
	public Date getDcSeries() {
		return this.dcSeries;
	}

	public void setDcSeries(Date dcSeries) {
		this.dcSeries = dcSeries;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_SERIES", nullable = false, length = 19)
	public Date getDmSeries() {
		return this.dmSeries;
	}

	public void setDmSeries(Date dmSeries) {
		this.dmSeries = dmSeries;
	}

	@Column(name = "NB_ALBUMS")
	public Integer getNbAlbums() {
		return this.nbAlbums;
	}

	public void setNbAlbums(Integer nbAlbums) {
		this.nbAlbums = nbAlbums;
	}

	@Column(name = "VO")
	public Short getVo() {
		return this.vo;
	}

	public void setVo(Short vo) {
		this.vo = vo;
	}

	@Column(name = "COULEUR")
	public Short getCouleur() {
		return this.couleur;
	}

	public void setCouleur(Short couleur) {
		this.couleur = couleur;
	}

	@Column(name = "TITRESERIE", length = 150)
	public String getTitreserie() {
		return this.titreserie;
	}

	public void setTitreserie(String titreserie) {
		this.titreserie = titreserie;
	}

	@Column(name = "SOUNDEXTITRESERIE", length = 30)
	public String getSoundextitreserie() {
		return this.soundextitreserie;
	}

	public void setSoundextitreserie(String soundextitreserie) {
		this.soundextitreserie = soundextitreserie;
	}

	@Column(name = "NOTATION")
	public Short getNotation() {
		return this.notation;
	}

	public void setNotation(Short notation) {
		this.notation = notation;
	}

	@Column(name = "SITEWEB")
	public String getSiteweb() {
		return this.siteweb;
	}

	public void setSiteweb(String siteweb) {
		this.siteweb = siteweb;
	}

	@Column(name = "SUJETSERIE", length = 0)
	public String getSujetserie() {
		return this.sujetserie;
	}

	public void setSujetserie(String sujetserie) {
		this.sujetserie = sujetserie;
	}

	@Column(name = "REMARQUESSERIE", length = 0)
	public String getRemarquesserie() {
		return this.remarquesserie;
	}

	public void setRemarquesserie(String remarquesserie) {
		this.remarquesserie = remarquesserie;
	}

	@Column(name = "ETAT", length = 38)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@Column(name = "RELIURE", length = 38)
	public String getReliure() {
		return this.reliure;
	}

	public void setReliure(String reliure) {
		this.reliure = reliure;
	}

	@Column(name = "TYPEEDITION", length = 38)
	public String getTypeedition() {
		return this.typeedition;
	}

	public void setTypeedition(String typeedition) {
		this.typeedition = typeedition;
	}

	@Column(name = "ORIENTATION", length = 38)
	public String getOrientation() {
		return this.orientation;
	}

	public void setOrientation(String orientation) {
		this.orientation = orientation;
	}

	@Column(name = "FORMATEDITION", length = 38)
	public String getFormatedition() {
		return this.formatedition;
	}

	public void setFormatedition(String formatedition) {
		this.formatedition = formatedition;
	}

	@Column(name = "SENSLECTURE", length = 38)
	public String getSenslecture() {
		return this.senslecture;
	}

	public void setSenslecture(String senslecture) {
		this.senslecture = senslecture;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "series")
	public Set<AuteursSeries> getAuteursSerieses() {
		return this.auteursSerieses;
	}

	public void setAuteursSerieses(Set<AuteursSeries> auteursSerieses) {
		this.auteursSerieses = auteursSerieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "series")
	public Set<Genreseries> getGenreserieses() {
		return this.genreserieses;
	}

	public void setGenreserieses(Set<Genreseries> genreserieses) {
		this.genreserieses = genreserieses;
	}

}
