package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Statut generated by hbm2java
 */
@Entity
@Table(name = "STATUT")
public class Statut implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idStatut;
	private Editions editions;
	private Emprunteurs emprunteurs;
	private Date dateemprunt;
	private short pretemprunt;
	private Date dcStatut;
	private Date dmStatut;

	public Statut() {
	}

	public Statut(String idStatut, Editions editions, Emprunteurs emprunteurs,
			Date dateemprunt, short pretemprunt, Date dcStatut, Date dmStatut) {
		this.idStatut = idStatut;
		this.editions = editions;
		this.emprunteurs = emprunteurs;
		this.dateemprunt = dateemprunt;
		this.pretemprunt = pretemprunt;
		this.dcStatut = dcStatut;
		this.dmStatut = dmStatut;
	}

	@Id
	@Column(name = "ID_STATUT", unique = true, nullable = false, length = 38)
	public String getIdStatut() {
		return this.idStatut;
	}

	public void setIdStatut(String idStatut) {
		this.idStatut = idStatut;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EDITION", nullable = false)
	public Editions getEditions() {
		return this.editions;
	}

	public void setEditions(Editions editions) {
		this.editions = editions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMPRUNTEUR", nullable = false)
	public Emprunteurs getEmprunteurs() {
		return this.emprunteurs;
	}

	public void setEmprunteurs(Emprunteurs emprunteurs) {
		this.emprunteurs = emprunteurs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATEEMPRUNT", nullable = false, length = 19)
	public Date getDateemprunt() {
		return this.dateemprunt;
	}

	public void setDateemprunt(Date dateemprunt) {
		this.dateemprunt = dateemprunt;
	}

	@Column(name = "PRETEMPRUNT", nullable = false)
	public short getPretemprunt() {
		return this.pretemprunt;
	}

	public void setPretemprunt(short pretemprunt) {
		this.pretemprunt = pretemprunt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_STATUT", nullable = false, length = 19)
	public Date getDcStatut() {
		return this.dcStatut;
	}

	public void setDcStatut(Date dcStatut) {
		this.dcStatut = dcStatut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_STATUT", nullable = false, length = 19)
	public Date getDmStatut() {
		return this.dmStatut;
	}

	public void setDmStatut(Date dmStatut) {
		this.dmStatut = dmStatut;
	}

}
