package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwDernieresModifs generated by hbm2java
 */
@Entity
@Table(name = "VW_DERNIERES_MODIFS")
public class VwDernieresModifs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VwDernieresModifsId id;

	public VwDernieresModifs() {
	}

	public VwDernieresModifs(VwDernieresModifsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "typedata", column = @Column(name = "TYPEDATA", length = 4)),
			@AttributeOverride(name = "dateCreation", column = @Column(name = "DATE_CREATION", length = 19)),
			@AttributeOverride(name = "dateModif", column = @Column(name = "DATE_MODIF", length = 19)),
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 38)),
			@AttributeOverride(name = "titrealbum", column = @Column(name = "TITREALBUM", length = 600)),
			@AttributeOverride(name = "tome", column = @Column(name = "TOME")),
			@AttributeOverride(name = "tomedebut", column = @Column(name = "TOMEDEBUT")),
			@AttributeOverride(name = "tomefin", column = @Column(name = "TOMEFIN")),
			@AttributeOverride(name = "integrale", column = @Column(name = "INTEGRALE")),
			@AttributeOverride(name = "horsserie", column = @Column(name = "HORSSERIE")),
			@AttributeOverride(name = "titreserie", column = @Column(name = "TITRESERIE", length = 600)),
			@AttributeOverride(name = "nomediteur", column = @Column(name = "NOMEDITEUR", length = 200)),
			@AttributeOverride(name = "nomcollection", column = @Column(name = "NOMCOLLECTION", length = 200)),
			@AttributeOverride(name = "nompersonne", column = @Column(name = "NOMPERSONNE", length = 600)) })
	public VwDernieresModifsId getId() {
		return this.id;
	}

	public void setId(VwDernieresModifsId id) {
		this.id = id;
	}

}
