package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwDernieresModifsId generated by hbm2java
 */
@Embeddable
public class VwDernieresModifsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String typedata;
	private Date dateCreation;
	private Date dateModif;
	private String id;
	private String titrealbum;
	private Short tome;
	private Short tomedebut;
	private Short tomefin;
	private Short integrale;
	private Short horsserie;
	private String titreserie;
	private String nomediteur;
	private String nomcollection;
	private String nompersonne;

	public VwDernieresModifsId() {
	}

	public VwDernieresModifsId(String typedata, Date dateCreation,
			Date dateModif, String id, String titrealbum, Short tome,
			Short tomedebut, Short tomefin, Short integrale, Short horsserie,
			String titreserie, String nomediteur, String nomcollection,
			String nompersonne) {
		this.typedata = typedata;
		this.dateCreation = dateCreation;
		this.dateModif = dateModif;
		this.id = id;
		this.titrealbum = titrealbum;
		this.tome = tome;
		this.tomedebut = tomedebut;
		this.tomefin = tomefin;
		this.integrale = integrale;
		this.horsserie = horsserie;
		this.titreserie = titreserie;
		this.nomediteur = nomediteur;
		this.nomcollection = nomcollection;
		this.nompersonne = nompersonne;
	}

	@Column(name = "TYPEDATA", length = 4)
	public String getTypedata() {
		return this.typedata;
	}

	public void setTypedata(String typedata) {
		this.typedata = typedata;
	}

	@Column(name = "DATE_CREATION", length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "DATE_MODIF", length = 19)
	public Date getDateModif() {
		return this.dateModif;
	}

	public void setDateModif(Date dateModif) {
		this.dateModif = dateModif;
	}

	@Column(name = "ID", length = 38)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "TITREALBUM", length = 600)
	public String getTitrealbum() {
		return this.titrealbum;
	}

	public void setTitrealbum(String titrealbum) {
		this.titrealbum = titrealbum;
	}

	@Column(name = "TOME")
	public Short getTome() {
		return this.tome;
	}

	public void setTome(Short tome) {
		this.tome = tome;
	}

	@Column(name = "TOMEDEBUT")
	public Short getTomedebut() {
		return this.tomedebut;
	}

	public void setTomedebut(Short tomedebut) {
		this.tomedebut = tomedebut;
	}

	@Column(name = "TOMEFIN")
	public Short getTomefin() {
		return this.tomefin;
	}

	public void setTomefin(Short tomefin) {
		this.tomefin = tomefin;
	}

	@Column(name = "INTEGRALE")
	public Short getIntegrale() {
		return this.integrale;
	}

	public void setIntegrale(Short integrale) {
		this.integrale = integrale;
	}

	@Column(name = "HORSSERIE")
	public Short getHorsserie() {
		return this.horsserie;
	}

	public void setHorsserie(Short horsserie) {
		this.horsserie = horsserie;
	}

	@Column(name = "TITRESERIE", length = 600)
	public String getTitreserie() {
		return this.titreserie;
	}

	public void setTitreserie(String titreserie) {
		this.titreserie = titreserie;
	}

	@Column(name = "NOMEDITEUR", length = 200)
	public String getNomediteur() {
		return this.nomediteur;
	}

	public void setNomediteur(String nomediteur) {
		this.nomediteur = nomediteur;
	}

	@Column(name = "NOMCOLLECTION", length = 200)
	public String getNomcollection() {
		return this.nomcollection;
	}

	public void setNomcollection(String nomcollection) {
		this.nomcollection = nomcollection;
	}

	@Column(name = "NOMPERSONNE", length = 600)
	public String getNompersonne() {
		return this.nompersonne;
	}

	public void setNompersonne(String nompersonne) {
		this.nompersonne = nompersonne;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwDernieresModifsId))
			return false;
		VwDernieresModifsId castOther = (VwDernieresModifsId) other;

		return ((this.getTypedata() == castOther.getTypedata()) || (this
				.getTypedata() != null && castOther.getTypedata() != null && this
				.getTypedata().equals(castOther.getTypedata())))
				&& ((this.getDateCreation() == castOther.getDateCreation()) || (this
						.getDateCreation() != null
						&& castOther.getDateCreation() != null && this
						.getDateCreation().equals(castOther.getDateCreation())))
				&& ((this.getDateModif() == castOther.getDateModif()) || (this
						.getDateModif() != null
						&& castOther.getDateModif() != null && this
						.getDateModif().equals(castOther.getDateModif())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null
						&& castOther.getId() != null && this.getId().equals(
						castOther.getId())))
				&& ((this.getTitrealbum() == castOther.getTitrealbum()) || (this
						.getTitrealbum() != null
						&& castOther.getTitrealbum() != null && this
						.getTitrealbum().equals(castOther.getTitrealbum())))
				&& ((this.getTome() == castOther.getTome()) || (this.getTome() != null
						&& castOther.getTome() != null && this.getTome()
						.equals(castOther.getTome())))
				&& ((this.getTomedebut() == castOther.getTomedebut()) || (this
						.getTomedebut() != null
						&& castOther.getTomedebut() != null && this
						.getTomedebut().equals(castOther.getTomedebut())))
				&& ((this.getTomefin() == castOther.getTomefin()) || (this
						.getTomefin() != null && castOther.getTomefin() != null && this
						.getTomefin().equals(castOther.getTomefin())))
				&& ((this.getIntegrale() == castOther.getIntegrale()) || (this
						.getIntegrale() != null
						&& castOther.getIntegrale() != null && this
						.getIntegrale().equals(castOther.getIntegrale())))
				&& ((this.getHorsserie() == castOther.getHorsserie()) || (this
						.getHorsserie() != null
						&& castOther.getHorsserie() != null && this
						.getHorsserie().equals(castOther.getHorsserie())))
				&& ((this.getTitreserie() == castOther.getTitreserie()) || (this
						.getTitreserie() != null
						&& castOther.getTitreserie() != null && this
						.getTitreserie().equals(castOther.getTitreserie())))
				&& ((this.getNomediteur() == castOther.getNomediteur()) || (this
						.getNomediteur() != null
						&& castOther.getNomediteur() != null && this
						.getNomediteur().equals(castOther.getNomediteur())))
				&& ((this.getNomcollection() == castOther.getNomcollection()) || (this
						.getNomcollection() != null
						&& castOther.getNomcollection() != null && this
						.getNomcollection()
						.equals(castOther.getNomcollection())))
				&& ((this.getNompersonne() == castOther.getNompersonne()) || (this
						.getNompersonne() != null
						&& castOther.getNompersonne() != null && this
						.getNompersonne().equals(castOther.getNompersonne())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTypedata() == null ? 0 : this.getTypedata().hashCode());
		result = 37
				* result
				+ (getDateCreation() == null ? 0 : this.getDateCreation()
						.hashCode());
		result = 37 * result
				+ (getDateModif() == null ? 0 : this.getDateModif().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getTitrealbum() == null ? 0 : this.getTitrealbum()
						.hashCode());
		result = 37 * result
				+ (getTome() == null ? 0 : this.getTome().hashCode());
		result = 37 * result
				+ (getTomedebut() == null ? 0 : this.getTomedebut().hashCode());
		result = 37 * result
				+ (getTomefin() == null ? 0 : this.getTomefin().hashCode());
		result = 37 * result
				+ (getIntegrale() == null ? 0 : this.getIntegrale().hashCode());
		result = 37 * result
				+ (getHorsserie() == null ? 0 : this.getHorsserie().hashCode());
		result = 37
				* result
				+ (getTitreserie() == null ? 0 : this.getTitreserie()
						.hashCode());
		result = 37
				* result
				+ (getNomediteur() == null ? 0 : this.getNomediteur()
						.hashCode());
		result = 37
				* result
				+ (getNomcollection() == null ? 0 : this.getNomcollection()
						.hashCode());
		result = 37
				* result
				+ (getNompersonne() == null ? 0 : this.getNompersonne()
						.hashCode());
		return result;
	}

}
