package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwEmprunts generated by hbm2java
 */
@Entity
@Table(name = "VW_EMPRUNTS")
public class VwEmprunts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VwEmpruntsId id;

	public VwEmprunts() {
	}

	public VwEmprunts(VwEmpruntsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idStatut", column = @Column(name = "ID_STATUT", nullable = false, length = 38)),
			@AttributeOverride(name = "idEdition", column = @Column(name = "ID_EDITION", nullable = false, length = 38)),
			@AttributeOverride(name = "idAlbum", column = @Column(name = "ID_ALBUM", nullable = false, length = 38)),
			@AttributeOverride(name = "titrealbum", column = @Column(name = "TITREALBUM", length = 150)),
			@AttributeOverride(name = "idSerie", column = @Column(name = "ID_SERIE", length = 38)),
			@AttributeOverride(name = "tome", column = @Column(name = "TOME")),
			@AttributeOverride(name = "integrale", column = @Column(name = "INTEGRALE")),
			@AttributeOverride(name = "tomedebut", column = @Column(name = "TOMEDEBUT")),
			@AttributeOverride(name = "tomefin", column = @Column(name = "TOMEFIN")),
			@AttributeOverride(name = "horsserie", column = @Column(name = "HORSSERIE")),
			@AttributeOverride(name = "notation", column = @Column(name = "NOTATION")),
			@AttributeOverride(name = "titreserie", column = @Column(name = "TITRESERIE", length = 150)),
			@AttributeOverride(name = "idEditeur", column = @Column(name = "ID_EDITEUR", nullable = false, length = 38)),
			@AttributeOverride(name = "nomediteur", column = @Column(name = "NOMEDITEUR", length = 50)),
			@AttributeOverride(name = "idCollection", column = @Column(name = "ID_COLLECTION", nullable = false, length = 38)),
			@AttributeOverride(name = "nomcollection", column = @Column(name = "NOMCOLLECTION", length = 50)),
			@AttributeOverride(name = "prete", column = @Column(name = "PRETE")),
			@AttributeOverride(name = "anneeedition", column = @Column(name = "ANNEEEDITION")),
			@AttributeOverride(name = "isbn", column = @Column(name = "ISBN", length = 13)),
			@AttributeOverride(name = "idEmprunteur", column = @Column(name = "ID_EMPRUNTEUR", nullable = false, length = 38)),
			@AttributeOverride(name = "nomemprunteur", column = @Column(name = "NOMEMPRUNTEUR", length = 150)),
			@AttributeOverride(name = "pretemprunt", column = @Column(name = "PRETEMPRUNT")),
			@AttributeOverride(name = "dateemprunt", column = @Column(name = "DATEEMPRUNT", length = 19)) })
	public VwEmpruntsId getId() {
		return this.id;
	}

	public void setId(VwEmpruntsId id) {
		this.id = id;
	}

}
