package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwInitialesEmprunteurs generated by hbm2java
 */
@Entity
@Table(name = "VW_INITIALES_EMPRUNTEURS")
public class VwInitialesEmprunteurs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VwInitialesEmprunteursId id;

	public VwInitialesEmprunteurs() {
	}

	public VwInitialesEmprunteurs(VwInitialesEmprunteursId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "initialenomemprunteur", column = @Column(name = "INITIALENOMEMPRUNTEUR", length = 4)),
			@AttributeOverride(name = "countinitiale", column = @Column(name = "COUNTINITIALE")) })
	public VwInitialesEmprunteursId getId() {
		return this.id;
	}

	public void setId(VwInitialesEmprunteursId id) {
		this.id = id;
	}

}
