package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwInitialesEditeursId generated by hbm2java
 */
@Embeddable
public class VwInitialesEditeursId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String initialenomediteur;
	private Integer countinitiale;

	public VwInitialesEditeursId() {
	}

	public VwInitialesEditeursId(String initialenomediteur,
			Integer countinitiale) {
		this.initialenomediteur = initialenomediteur;
		this.countinitiale = countinitiale;
	}

	@Column(name = "INITIALENOMEDITEUR", length = 4)
	public String getInitialenomediteur() {
		return this.initialenomediteur;
	}

	public void setInitialenomediteur(String initialenomediteur) {
		this.initialenomediteur = initialenomediteur;
	}

	@Column(name = "COUNTINITIALE")
	public Integer getCountinitiale() {
		return this.countinitiale;
	}

	public void setCountinitiale(Integer countinitiale) {
		this.countinitiale = countinitiale;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwInitialesEditeursId))
			return false;
		VwInitialesEditeursId castOther = (VwInitialesEditeursId) other;

		return ((this.getInitialenomediteur() == castOther
				.getInitialenomediteur()) || (this.getInitialenomediteur() != null
				&& castOther.getInitialenomediteur() != null && this
				.getInitialenomediteur().equals(
						castOther.getInitialenomediteur())))
				&& ((this.getCountinitiale() == castOther.getCountinitiale()) || (this
						.getCountinitiale() != null
						&& castOther.getCountinitiale() != null && this
						.getCountinitiale()
						.equals(castOther.getCountinitiale())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getInitialenomediteur() == null ? 0 : this
						.getInitialenomediteur().hashCode());
		result = 37
				* result
				+ (getCountinitiale() == null ? 0 : this.getCountinitiale()
						.hashCode());
		return result;
	}

}
