package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwInitialesPersonnesId generated by hbm2java
 */
@Embeddable
public class VwInitialesPersonnesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String initialenompersonne;
	private Integer countinitiale;

	public VwInitialesPersonnesId() {
	}

	public VwInitialesPersonnesId(String initialenompersonne,
			Integer countinitiale) {
		this.initialenompersonne = initialenompersonne;
		this.countinitiale = countinitiale;
	}

	@Column(name = "INITIALENOMPERSONNE", length = 4)
	public String getInitialenompersonne() {
		return this.initialenompersonne;
	}

	public void setInitialenompersonne(String initialenompersonne) {
		this.initialenompersonne = initialenompersonne;
	}

	@Column(name = "COUNTINITIALE")
	public Integer getCountinitiale() {
		return this.countinitiale;
	}

	public void setCountinitiale(Integer countinitiale) {
		this.countinitiale = countinitiale;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwInitialesPersonnesId))
			return false;
		VwInitialesPersonnesId castOther = (VwInitialesPersonnesId) other;

		return ((this.getInitialenompersonne() == castOther
				.getInitialenompersonne()) || (this.getInitialenompersonne() != null
				&& castOther.getInitialenompersonne() != null && this
				.getInitialenompersonne().equals(
						castOther.getInitialenompersonne())))
				&& ((this.getCountinitiale() == castOther.getCountinitiale()) || (this
						.getCountinitiale() != null
						&& castOther.getCountinitiale() != null && this
						.getCountinitiale()
						.equals(castOther.getCountinitiale())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getInitialenompersonne() == null ? 0 : this
						.getInitialenompersonne().hashCode());
		result = 37
				* result
				+ (getCountinitiale() == null ? 0 : this.getCountinitiale()
						.hashCode());
		return result;
	}

}
