package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwInitialesSeriesId generated by hbm2java
 */
@Embeddable
public class VwInitialesSeriesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String initialetitreserie;
	private Integer countinitiale;

	public VwInitialesSeriesId() {
	}

	public VwInitialesSeriesId(String initialetitreserie, Integer countinitiale) {
		this.initialetitreserie = initialetitreserie;
		this.countinitiale = countinitiale;
	}

	@Column(name = "INITIALETITRESERIE", length = 4)
	public String getInitialetitreserie() {
		return this.initialetitreserie;
	}

	public void setInitialetitreserie(String initialetitreserie) {
		this.initialetitreserie = initialetitreserie;
	}

	@Column(name = "COUNTINITIALE")
	public Integer getCountinitiale() {
		return this.countinitiale;
	}

	public void setCountinitiale(Integer countinitiale) {
		this.countinitiale = countinitiale;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwInitialesSeriesId))
			return false;
		VwInitialesSeriesId castOther = (VwInitialesSeriesId) other;

		return ((this.getInitialetitreserie() == castOther
				.getInitialetitreserie()) || (this.getInitialetitreserie() != null
				&& castOther.getInitialetitreserie() != null && this
				.getInitialetitreserie().equals(
						castOther.getInitialetitreserie())))
				&& ((this.getCountinitiale() == castOther.getCountinitiale()) || (this
						.getCountinitiale() != null
						&& castOther.getCountinitiale() != null && this
						.getCountinitiale()
						.equals(castOther.getCountinitiale())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getInitialetitreserie() == null ? 0 : this
						.getInitialetitreserie().hashCode());
		result = 37
				* result
				+ (getCountinitiale() == null ? 0 : this.getCountinitiale()
						.hashCode());
		return result;
	}

}
