package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwInitialesPersonnes generated by hbm2java
 */
@Entity
@Table(name = "VW_INITIALES_PERSONNES")
public class VwInitialesPersonnes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VwInitialesPersonnesId id;

	public VwInitialesPersonnes() {
	}

	public VwInitialesPersonnes(VwInitialesPersonnesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "initialenompersonne", column = @Column(name = "INITIALENOMPERSONNE", length = 4)),
			@AttributeOverride(name = "countinitiale", column = @Column(name = "COUNTINITIALE")) })
	public VwInitialesPersonnesId getId() {
		return this.id;
	}

	public void setId(VwInitialesPersonnesId id) {
		this.id = id;
	}

}
