package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwListeCollections generated by hbm2java
 */
@Entity
@Table(name = "VW_LISTE_COLLECTIONS")
public class VwListeCollections implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VwListeCollectionsId id;

	public VwListeCollections() {
	}

	public VwListeCollections(VwListeCollectionsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idCollection", column = @Column(name = "ID_COLLECTION", nullable = false, length = 38)),
			@AttributeOverride(name = "nomcollection", column = @Column(name = "NOMCOLLECTION", length = 50)),
			@AttributeOverride(name = "initialenomcollection", column = @Column(name = "INITIALENOMCOLLECTION", length = 1)),
			@AttributeOverride(name = "idEditeur", column = @Column(name = "ID_EDITEUR", nullable = false, length = 38)),
			@AttributeOverride(name = "nomediteur", column = @Column(name = "NOMEDITEUR", length = 50)) })
	public VwListeCollectionsId getId() {
		return this.id;
	}

	public void setId(VwListeCollectionsId id) {
		this.id = id;
	}

}
