package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwListeParabdId generated by hbm2java
 */
@Embeddable
public class VwListeParabdId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idParabd;
	private String titreparabd;
	private String idSerie;
	private String titreserie;
	private Short achat;
	private Integer complet;
	private String scategorie;

	public VwListeParabdId() {
	}

	public VwListeParabdId(String idParabd) {
		this.idParabd = idParabd;
	}

	public VwListeParabdId(String idParabd, String titreparabd, String idSerie,
			String titreserie, Short achat, Integer complet, String scategorie) {
		this.idParabd = idParabd;
		this.titreparabd = titreparabd;
		this.idSerie = idSerie;
		this.titreserie = titreserie;
		this.achat = achat;
		this.complet = complet;
		this.scategorie = scategorie;
	}

	@Column(name = "ID_PARABD", nullable = false, length = 38)
	public String getIdParabd() {
		return this.idParabd;
	}

	public void setIdParabd(String idParabd) {
		this.idParabd = idParabd;
	}

	@Column(name = "TITREPARABD", length = 150)
	public String getTitreparabd() {
		return this.titreparabd;
	}

	public void setTitreparabd(String titreparabd) {
		this.titreparabd = titreparabd;
	}

	@Column(name = "ID_SERIE", length = 38)
	public String getIdSerie() {
		return this.idSerie;
	}

	public void setIdSerie(String idSerie) {
		this.idSerie = idSerie;
	}

	@Column(name = "TITRESERIE", length = 150)
	public String getTitreserie() {
		return this.titreserie;
	}

	public void setTitreserie(String titreserie) {
		this.titreserie = titreserie;
	}

	@Column(name = "ACHAT")
	public Short getAchat() {
		return this.achat;
	}

	public void setAchat(Short achat) {
		this.achat = achat;
	}

	@Column(name = "COMPLET")
	public Integer getComplet() {
		return this.complet;
	}

	public void setComplet(Integer complet) {
		this.complet = complet;
	}

	@Column(name = "SCATEGORIE", length = 50)
	public String getScategorie() {
		return this.scategorie;
	}

	public void setScategorie(String scategorie) {
		this.scategorie = scategorie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwListeParabdId))
			return false;
		VwListeParabdId castOther = (VwListeParabdId) other;

		return ((this.getIdParabd() == castOther.getIdParabd()) || (this
				.getIdParabd() != null && castOther.getIdParabd() != null && this
				.getIdParabd().equals(castOther.getIdParabd())))
				&& ((this.getTitreparabd() == castOther.getTitreparabd()) || (this
						.getTitreparabd() != null
						&& castOther.getTitreparabd() != null && this
						.getTitreparabd().equals(castOther.getTitreparabd())))
				&& ((this.getIdSerie() == castOther.getIdSerie()) || (this
						.getIdSerie() != null && castOther.getIdSerie() != null && this
						.getIdSerie().equals(castOther.getIdSerie())))
				&& ((this.getTitreserie() == castOther.getTitreserie()) || (this
						.getTitreserie() != null
						&& castOther.getTitreserie() != null && this
						.getTitreserie().equals(castOther.getTitreserie())))
				&& ((this.getAchat() == castOther.getAchat()) || (this
						.getAchat() != null && castOther.getAchat() != null && this
						.getAchat().equals(castOther.getAchat())))
				&& ((this.getComplet() == castOther.getComplet()) || (this
						.getComplet() != null && castOther.getComplet() != null && this
						.getComplet().equals(castOther.getComplet())))
				&& ((this.getScategorie() == castOther.getScategorie()) || (this
						.getScategorie() != null
						&& castOther.getScategorie() != null && this
						.getScategorie().equals(castOther.getScategorie())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdParabd() == null ? 0 : this.getIdParabd().hashCode());
		result = 37
				* result
				+ (getTitreparabd() == null ? 0 : this.getTitreparabd()
						.hashCode());
		result = 37 * result
				+ (getIdSerie() == null ? 0 : this.getIdSerie().hashCode());
		result = 37
				* result
				+ (getTitreserie() == null ? 0 : this.getTitreserie()
						.hashCode());
		result = 37 * result
				+ (getAchat() == null ? 0 : this.getAchat().hashCode());
		result = 37 * result
				+ (getComplet() == null ? 0 : this.getComplet().hashCode());
		result = 37
				* result
				+ (getScategorie() == null ? 0 : this.getScategorie()
						.hashCode());
		return result;
	}

}
