package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwListeGenresAlbums generated by hbm2java
 */
@Entity
@Table(name = "VW_LISTE_GENRES_ALBUMS")
public class VwListeGenresAlbums implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VwListeGenresAlbumsId id;

	public VwListeGenresAlbums() {
	}

	public VwListeGenresAlbums(VwListeGenresAlbumsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idAlbum", column = @Column(name = "ID_ALBUM", nullable = false, length = 38)),
			@AttributeOverride(name = "titrealbum", column = @Column(name = "TITREALBUM", length = 150)),
			@AttributeOverride(name = "tome", column = @Column(name = "TOME")),
			@AttributeOverride(name = "tomedebut", column = @Column(name = "TOMEDEBUT")),
			@AttributeOverride(name = "tomefin", column = @Column(name = "TOMEFIN")),
			@AttributeOverride(name = "horsserie", column = @Column(name = "HORSSERIE")),
			@AttributeOverride(name = "integrale", column = @Column(name = "INTEGRALE")),
			@AttributeOverride(name = "moisparution", column = @Column(name = "MOISPARUTION")),
			@AttributeOverride(name = "anneeparution", column = @Column(name = "ANNEEPARUTION")),
			@AttributeOverride(name = "notation", column = @Column(name = "NOTATION")),
			@AttributeOverride(name = "idSerie", column = @Column(name = "ID_SERIE", length = 38)),
			@AttributeOverride(name = "titreserie", column = @Column(name = "TITRESERIE", length = 150)),
			@AttributeOverride(name = "idGenre", column = @Column(name = "ID_GENRE", nullable = false, length = 38)),
			@AttributeOverride(name = "genre", column = @Column(name = "GENRE", length = 30)),
			@AttributeOverride(name = "achat", column = @Column(name = "ACHAT")),
			@AttributeOverride(name = "complet", column = @Column(name = "COMPLET")) })
	public VwListeGenresAlbumsId getId() {
		return this.id;
	}

	public void setId(VwListeGenresAlbumsId id) {
		this.id = id;
	}

}
