package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwListeAlbumsId generated by hbm2java
 */
@Embeddable
public class VwListeAlbumsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idAlbum;
	private String titrealbum;
	private Short tome;
	private Short tomedebut;
	private Short tomefin;
	private Short horsserie;
	private Short integrale;
	private Short moisparution;
	private Short anneeparution;
	private String idSerie;
	private String titreserie;
	private Short achat;
	private Integer complet;
	private Short notation;
	private String initialetitrealbum;
	private Character initialetitreserie;

	public VwListeAlbumsId() {
	}

	public VwListeAlbumsId(String idAlbum) {
		this.idAlbum = idAlbum;
	}

	public VwListeAlbumsId(String idAlbum, String titrealbum, Short tome,
			Short tomedebut, Short tomefin, Short horsserie, Short integrale,
			Short moisparution, Short anneeparution, String idSerie,
			String titreserie, Short achat, Integer complet, Short notation,
			String initialetitrealbum, Character initialetitreserie) {
		this.idAlbum = idAlbum;
		this.titrealbum = titrealbum;
		this.tome = tome;
		this.tomedebut = tomedebut;
		this.tomefin = tomefin;
		this.horsserie = horsserie;
		this.integrale = integrale;
		this.moisparution = moisparution;
		this.anneeparution = anneeparution;
		this.idSerie = idSerie;
		this.titreserie = titreserie;
		this.achat = achat;
		this.complet = complet;
		this.notation = notation;
		this.initialetitrealbum = initialetitrealbum;
		this.initialetitreserie = initialetitreserie;
	}

	@Column(name = "ID_ALBUM", nullable = false, length = 38)
	public String getIdAlbum() {
		return this.idAlbum;
	}

	public void setIdAlbum(String idAlbum) {
		this.idAlbum = idAlbum;
	}

	@Column(name = "TITREALBUM", length = 150)
	public String getTitrealbum() {
		return this.titrealbum;
	}

	public void setTitrealbum(String titrealbum) {
		this.titrealbum = titrealbum;
	}

	@Column(name = "TOME")
	public Short getTome() {
		return this.tome;
	}

	public void setTome(Short tome) {
		this.tome = tome;
	}

	@Column(name = "TOMEDEBUT")
	public Short getTomedebut() {
		return this.tomedebut;
	}

	public void setTomedebut(Short tomedebut) {
		this.tomedebut = tomedebut;
	}

	@Column(name = "TOMEFIN")
	public Short getTomefin() {
		return this.tomefin;
	}

	public void setTomefin(Short tomefin) {
		this.tomefin = tomefin;
	}

	@Column(name = "HORSSERIE")
	public Short getHorsserie() {
		return this.horsserie;
	}

	public void setHorsserie(Short horsserie) {
		this.horsserie = horsserie;
	}

	@Column(name = "INTEGRALE")
	public Short getIntegrale() {
		return this.integrale;
	}

	public void setIntegrale(Short integrale) {
		this.integrale = integrale;
	}

	@Column(name = "MOISPARUTION")
	public Short getMoisparution() {
		return this.moisparution;
	}

	public void setMoisparution(Short moisparution) {
		this.moisparution = moisparution;
	}

	@Column(name = "ANNEEPARUTION")
	public Short getAnneeparution() {
		return this.anneeparution;
	}

	public void setAnneeparution(Short anneeparution) {
		this.anneeparution = anneeparution;
	}

	@Column(name = "ID_SERIE", length = 38)
	public String getIdSerie() {
		return this.idSerie;
	}

	public void setIdSerie(String idSerie) {
		this.idSerie = idSerie;
	}

	@Column(name = "TITRESERIE", length = 150)
	public String getTitreserie() {
		return this.titreserie;
	}

	public void setTitreserie(String titreserie) {
		this.titreserie = titreserie;
	}

	@Column(name = "ACHAT")
	public Short getAchat() {
		return this.achat;
	}

	public void setAchat(Short achat) {
		this.achat = achat;
	}

	@Column(name = "COMPLET")
	public Integer getComplet() {
		return this.complet;
	}

	public void setComplet(Integer complet) {
		this.complet = complet;
	}

	@Column(name = "NOTATION")
	public Short getNotation() {
		return this.notation;
	}

	public void setNotation(Short notation) {
		this.notation = notation;
	}

	@Column(name = "INITIALETITREALBUM", length = 4)
	public String getInitialetitrealbum() {
		return this.initialetitrealbum;
	}

	public void setInitialetitrealbum(String initialetitrealbum) {
		this.initialetitrealbum = initialetitrealbum;
	}

	@Column(name = "INITIALETITRESERIE", length = 1)
	public Character getInitialetitreserie() {
		return this.initialetitreserie;
	}

	public void setInitialetitreserie(Character initialetitreserie) {
		this.initialetitreserie = initialetitreserie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwListeAlbumsId))
			return false;
		VwListeAlbumsId castOther = (VwListeAlbumsId) other;

		return ((this.getIdAlbum() == castOther.getIdAlbum()) || (this
				.getIdAlbum() != null && castOther.getIdAlbum() != null && this
				.getIdAlbum().equals(castOther.getIdAlbum())))
				&& ((this.getTitrealbum() == castOther.getTitrealbum()) || (this
						.getTitrealbum() != null
						&& castOther.getTitrealbum() != null && this
						.getTitrealbum().equals(castOther.getTitrealbum())))
				&& ((this.getTome() == castOther.getTome()) || (this.getTome() != null
						&& castOther.getTome() != null && this.getTome()
						.equals(castOther.getTome())))
				&& ((this.getTomedebut() == castOther.getTomedebut()) || (this
						.getTomedebut() != null
						&& castOther.getTomedebut() != null && this
						.getTomedebut().equals(castOther.getTomedebut())))
				&& ((this.getTomefin() == castOther.getTomefin()) || (this
						.getTomefin() != null && castOther.getTomefin() != null && this
						.getTomefin().equals(castOther.getTomefin())))
				&& ((this.getHorsserie() == castOther.getHorsserie()) || (this
						.getHorsserie() != null
						&& castOther.getHorsserie() != null && this
						.getHorsserie().equals(castOther.getHorsserie())))
				&& ((this.getIntegrale() == castOther.getIntegrale()) || (this
						.getIntegrale() != null
						&& castOther.getIntegrale() != null && this
						.getIntegrale().equals(castOther.getIntegrale())))
				&& ((this.getMoisparution() == castOther.getMoisparution()) || (this
						.getMoisparution() != null
						&& castOther.getMoisparution() != null && this
						.getMoisparution().equals(castOther.getMoisparution())))
				&& ((this.getAnneeparution() == castOther.getAnneeparution()) || (this
						.getAnneeparution() != null
						&& castOther.getAnneeparution() != null && this
						.getAnneeparution()
						.equals(castOther.getAnneeparution())))
				&& ((this.getIdSerie() == castOther.getIdSerie()) || (this
						.getIdSerie() != null && castOther.getIdSerie() != null && this
						.getIdSerie().equals(castOther.getIdSerie())))
				&& ((this.getTitreserie() == castOther.getTitreserie()) || (this
						.getTitreserie() != null
						&& castOther.getTitreserie() != null && this
						.getTitreserie().equals(castOther.getTitreserie())))
				&& ((this.getAchat() == castOther.getAchat()) || (this
						.getAchat() != null && castOther.getAchat() != null && this
						.getAchat().equals(castOther.getAchat())))
				&& ((this.getComplet() == castOther.getComplet()) || (this
						.getComplet() != null && castOther.getComplet() != null && this
						.getComplet().equals(castOther.getComplet())))
				&& ((this.getNotation() == castOther.getNotation()) || (this
						.getNotation() != null
						&& castOther.getNotation() != null && this
						.getNotation().equals(castOther.getNotation())))
				&& ((this.getInitialetitrealbum() == castOther
						.getInitialetitrealbum()) || (this
						.getInitialetitrealbum() != null
						&& castOther.getInitialetitrealbum() != null && this
						.getInitialetitrealbum().equals(
								castOther.getInitialetitrealbum())))
				&& ((this.getInitialetitreserie() == castOther
						.getInitialetitreserie()) || (this
						.getInitialetitreserie() != null
						&& castOther.getInitialetitreserie() != null && this
						.getInitialetitreserie().equals(
								castOther.getInitialetitreserie())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdAlbum() == null ? 0 : this.getIdAlbum().hashCode());
		result = 37
				* result
				+ (getTitrealbum() == null ? 0 : this.getTitrealbum()
						.hashCode());
		result = 37 * result
				+ (getTome() == null ? 0 : this.getTome().hashCode());
		result = 37 * result
				+ (getTomedebut() == null ? 0 : this.getTomedebut().hashCode());
		result = 37 * result
				+ (getTomefin() == null ? 0 : this.getTomefin().hashCode());
		result = 37 * result
				+ (getHorsserie() == null ? 0 : this.getHorsserie().hashCode());
		result = 37 * result
				+ (getIntegrale() == null ? 0 : this.getIntegrale().hashCode());
		result = 37
				* result
				+ (getMoisparution() == null ? 0 : this.getMoisparution()
						.hashCode());
		result = 37
				* result
				+ (getAnneeparution() == null ? 0 : this.getAnneeparution()
						.hashCode());
		result = 37 * result
				+ (getIdSerie() == null ? 0 : this.getIdSerie().hashCode());
		result = 37
				* result
				+ (getTitreserie() == null ? 0 : this.getTitreserie()
						.hashCode());
		result = 37 * result
				+ (getAchat() == null ? 0 : this.getAchat().hashCode());
		result = 37 * result
				+ (getComplet() == null ? 0 : this.getComplet().hashCode());
		result = 37 * result
				+ (getNotation() == null ? 0 : this.getNotation().hashCode());
		result = 37
				* result
				+ (getInitialetitrealbum() == null ? 0 : this
						.getInitialetitrealbum().hashCode());
		result = 37
				* result
				+ (getInitialetitreserie() == null ? 0 : this
						.getInitialetitreserie().hashCode());
		return result;
	}

}
