package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwListeCollectionsId generated by hbm2java
 */
@Embeddable
public class VwListeCollectionsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idCollection;
	private String nomcollection;
	private Character initialenomcollection;
	private String idEditeur;
	private String nomediteur;

	public VwListeCollectionsId() {
	}

	public VwListeCollectionsId(String idCollection, String idEditeur) {
		this.idCollection = idCollection;
		this.idEditeur = idEditeur;
	}

	public VwListeCollectionsId(String idCollection, String nomcollection,
			Character initialenomcollection, String idEditeur, String nomediteur) {
		this.idCollection = idCollection;
		this.nomcollection = nomcollection;
		this.initialenomcollection = initialenomcollection;
		this.idEditeur = idEditeur;
		this.nomediteur = nomediteur;
	}

	@Column(name = "ID_COLLECTION", nullable = false, length = 38)
	public String getIdCollection() {
		return this.idCollection;
	}

	public void setIdCollection(String idCollection) {
		this.idCollection = idCollection;
	}

	@Column(name = "NOMCOLLECTION", length = 50)
	public String getNomcollection() {
		return this.nomcollection;
	}

	public void setNomcollection(String nomcollection) {
		this.nomcollection = nomcollection;
	}

	@Column(name = "INITIALENOMCOLLECTION", length = 1)
	public Character getInitialenomcollection() {
		return this.initialenomcollection;
	}

	public void setInitialenomcollection(Character initialenomcollection) {
		this.initialenomcollection = initialenomcollection;
	}

	@Column(name = "ID_EDITEUR", nullable = false, length = 38)
	public String getIdEditeur() {
		return this.idEditeur;
	}

	public void setIdEditeur(String idEditeur) {
		this.idEditeur = idEditeur;
	}

	@Column(name = "NOMEDITEUR", length = 50)
	public String getNomediteur() {
		return this.nomediteur;
	}

	public void setNomediteur(String nomediteur) {
		this.nomediteur = nomediteur;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwListeCollectionsId))
			return false;
		VwListeCollectionsId castOther = (VwListeCollectionsId) other;

		return ((this.getIdCollection() == castOther.getIdCollection()) || (this
				.getIdCollection() != null
				&& castOther.getIdCollection() != null && this
				.getIdCollection().equals(castOther.getIdCollection())))
				&& ((this.getNomcollection() == castOther.getNomcollection()) || (this
						.getNomcollection() != null
						&& castOther.getNomcollection() != null && this
						.getNomcollection()
						.equals(castOther.getNomcollection())))
				&& ((this.getInitialenomcollection() == castOther
						.getInitialenomcollection()) || (this
						.getInitialenomcollection() != null
						&& castOther.getInitialenomcollection() != null && this
						.getInitialenomcollection().equals(
								castOther.getInitialenomcollection())))
				&& ((this.getIdEditeur() == castOther.getIdEditeur()) || (this
						.getIdEditeur() != null
						&& castOther.getIdEditeur() != null && this
						.getIdEditeur().equals(castOther.getIdEditeur())))
				&& ((this.getNomediteur() == castOther.getNomediteur()) || (this
						.getNomediteur() != null
						&& castOther.getNomediteur() != null && this
						.getNomediteur().equals(castOther.getNomediteur())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdCollection() == null ? 0 : this.getIdCollection()
						.hashCode());
		result = 37
				* result
				+ (getNomcollection() == null ? 0 : this.getNomcollection()
						.hashCode());
		result = 37
				* result
				+ (getInitialenomcollection() == null ? 0 : this
						.getInitialenomcollection().hashCode());
		result = 37 * result
				+ (getIdEditeur() == null ? 0 : this.getIdEditeur().hashCode());
		result = 37
				* result
				+ (getNomediteur() == null ? 0 : this.getNomediteur()
						.hashCode());
		return result;
	}

}
