package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwPrixalbumsId generated by hbm2java
 */
@Embeddable
public class VwPrixalbumsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idAlbum;
	private Short horsserie;
	private Short tome;
	private Short integrale;
	private Short tomedebut;
	private Short tomefin;
	private Long nbalbums;
	private String idSerie;
	private String idEdition;
	private String idEditeur;
	private BigDecimal prix;

	public VwPrixalbumsId() {
	}

	public VwPrixalbumsId(String idAlbum, String idEdition, String idEditeur) {
		this.idAlbum = idAlbum;
		this.idEdition = idEdition;
		this.idEditeur = idEditeur;
	}

	public VwPrixalbumsId(String idAlbum, Short horsserie, Short tome,
			Short integrale, Short tomedebut, Short tomefin, Long nbalbums,
			String idSerie, String idEdition, String idEditeur, BigDecimal prix) {
		this.idAlbum = idAlbum;
		this.horsserie = horsserie;
		this.tome = tome;
		this.integrale = integrale;
		this.tomedebut = tomedebut;
		this.tomefin = tomefin;
		this.nbalbums = nbalbums;
		this.idSerie = idSerie;
		this.idEdition = idEdition;
		this.idEditeur = idEditeur;
		this.prix = prix;
	}

	@Column(name = "ID_ALBUM", nullable = false, length = 38)
	public String getIdAlbum() {
		return this.idAlbum;
	}

	public void setIdAlbum(String idAlbum) {
		this.idAlbum = idAlbum;
	}

	@Column(name = "HORSSERIE")
	public Short getHorsserie() {
		return this.horsserie;
	}

	public void setHorsserie(Short horsserie) {
		this.horsserie = horsserie;
	}

	@Column(name = "TOME")
	public Short getTome() {
		return this.tome;
	}

	public void setTome(Short tome) {
		this.tome = tome;
	}

	@Column(name = "INTEGRALE")
	public Short getIntegrale() {
		return this.integrale;
	}

	public void setIntegrale(Short integrale) {
		this.integrale = integrale;
	}

	@Column(name = "TOMEDEBUT")
	public Short getTomedebut() {
		return this.tomedebut;
	}

	public void setTomedebut(Short tomedebut) {
		this.tomedebut = tomedebut;
	}

	@Column(name = "TOMEFIN")
	public Short getTomefin() {
		return this.tomefin;
	}

	public void setTomefin(Short tomefin) {
		this.tomefin = tomefin;
	}

	@Column(name = "NBALBUMS")
	public Long getNbalbums() {
		return this.nbalbums;
	}

	public void setNbalbums(Long nbalbums) {
		this.nbalbums = nbalbums;
	}

	@Column(name = "ID_SERIE", length = 38)
	public String getIdSerie() {
		return this.idSerie;
	}

	public void setIdSerie(String idSerie) {
		this.idSerie = idSerie;
	}

	@Column(name = "ID_EDITION", nullable = false, length = 38)
	public String getIdEdition() {
		return this.idEdition;
	}

	public void setIdEdition(String idEdition) {
		this.idEdition = idEdition;
	}

	@Column(name = "ID_EDITEUR", nullable = false, length = 38)
	public String getIdEditeur() {
		return this.idEditeur;
	}

	public void setIdEditeur(String idEditeur) {
		this.idEditeur = idEditeur;
	}

	@Column(name = "PRIX", precision = 15)
	public BigDecimal getPrix() {
		return this.prix;
	}

	public void setPrix(BigDecimal prix) {
		this.prix = prix;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwPrixalbumsId))
			return false;
		VwPrixalbumsId castOther = (VwPrixalbumsId) other;

		return ((this.getIdAlbum() == castOther.getIdAlbum()) || (this
				.getIdAlbum() != null && castOther.getIdAlbum() != null && this
				.getIdAlbum().equals(castOther.getIdAlbum())))
				&& ((this.getHorsserie() == castOther.getHorsserie()) || (this
						.getHorsserie() != null
						&& castOther.getHorsserie() != null && this
						.getHorsserie().equals(castOther.getHorsserie())))
				&& ((this.getTome() == castOther.getTome()) || (this.getTome() != null
						&& castOther.getTome() != null && this.getTome()
						.equals(castOther.getTome())))
				&& ((this.getIntegrale() == castOther.getIntegrale()) || (this
						.getIntegrale() != null
						&& castOther.getIntegrale() != null && this
						.getIntegrale().equals(castOther.getIntegrale())))
				&& ((this.getTomedebut() == castOther.getTomedebut()) || (this
						.getTomedebut() != null
						&& castOther.getTomedebut() != null && this
						.getTomedebut().equals(castOther.getTomedebut())))
				&& ((this.getTomefin() == castOther.getTomefin()) || (this
						.getTomefin() != null && castOther.getTomefin() != null && this
						.getTomefin().equals(castOther.getTomefin())))
				&& ((this.getNbalbums() == castOther.getNbalbums()) || (this
						.getNbalbums() != null
						&& castOther.getNbalbums() != null && this
						.getNbalbums().equals(castOther.getNbalbums())))
				&& ((this.getIdSerie() == castOther.getIdSerie()) || (this
						.getIdSerie() != null && castOther.getIdSerie() != null && this
						.getIdSerie().equals(castOther.getIdSerie())))
				&& ((this.getIdEdition() == castOther.getIdEdition()) || (this
						.getIdEdition() != null
						&& castOther.getIdEdition() != null && this
						.getIdEdition().equals(castOther.getIdEdition())))
				&& ((this.getIdEditeur() == castOther.getIdEditeur()) || (this
						.getIdEditeur() != null
						&& castOther.getIdEditeur() != null && this
						.getIdEditeur().equals(castOther.getIdEditeur())))
				&& ((this.getPrix() == castOther.getPrix()) || (this.getPrix() != null
						&& castOther.getPrix() != null && this.getPrix()
						.equals(castOther.getPrix())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdAlbum() == null ? 0 : this.getIdAlbum().hashCode());
		result = 37 * result
				+ (getHorsserie() == null ? 0 : this.getHorsserie().hashCode());
		result = 37 * result
				+ (getTome() == null ? 0 : this.getTome().hashCode());
		result = 37 * result
				+ (getIntegrale() == null ? 0 : this.getIntegrale().hashCode());
		result = 37 * result
				+ (getTomedebut() == null ? 0 : this.getTomedebut().hashCode());
		result = 37 * result
				+ (getTomefin() == null ? 0 : this.getTomefin().hashCode());
		result = 37 * result
				+ (getNbalbums() == null ? 0 : this.getNbalbums().hashCode());
		result = 37 * result
				+ (getIdSerie() == null ? 0 : this.getIdSerie().hashCode());
		result = 37 * result
				+ (getIdEdition() == null ? 0 : this.getIdEdition().hashCode());
		result = 37 * result
				+ (getIdEditeur() == null ? 0 : this.getIdEditeur().hashCode());
		result = 37 * result
				+ (getPrix() == null ? 0 : this.getPrix().hashCode());
		return result;
	}

}
