package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwPrixunitaires generated by hbm2java
 */
@Entity
@Table(name = "VW_PRIXUNITAIRES")
public class VwPrixunitaires implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VwPrixunitairesId id;

	public VwPrixunitaires() {
	}

	public VwPrixunitaires(VwPrixunitairesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "horsserie", column = @Column(name = "HORSSERIE")),
			@AttributeOverride(name = "idSerie", column = @Column(name = "ID_SERIE", length = 38)),
			@AttributeOverride(name = "idEditeur", column = @Column(name = "ID_EDITEUR", length = 38)),
			@AttributeOverride(name = "prixunitaire", column = @Column(name = "PRIXUNITAIRE", precision = 0)) })
	public VwPrixunitairesId getId() {
		return this.id;
	}

	public void setId(VwPrixunitairesId id) {
		this.id = id;
	}

}
