package org.tetram.bdtheque.data.model;

// Generated 10 nov. 2012 15:28:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwPrixunitairesId generated by hbm2java
 */
@Embeddable
public class VwPrixunitairesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Short horsserie;
	private String idSerie;
	private String idEditeur;
	private BigDecimal prixunitaire;

	public VwPrixunitairesId() {
	}

	public VwPrixunitairesId(Short horsserie, String idSerie, String idEditeur,
			BigDecimal prixunitaire) {
		this.horsserie = horsserie;
		this.idSerie = idSerie;
		this.idEditeur = idEditeur;
		this.prixunitaire = prixunitaire;
	}

	@Column(name = "HORSSERIE")
	public Short getHorsserie() {
		return this.horsserie;
	}

	public void setHorsserie(Short horsserie) {
		this.horsserie = horsserie;
	}

	@Column(name = "ID_SERIE", length = 38)
	public String getIdSerie() {
		return this.idSerie;
	}

	public void setIdSerie(String idSerie) {
		this.idSerie = idSerie;
	}

	@Column(name = "ID_EDITEUR", length = 38)
	public String getIdEditeur() {
		return this.idEditeur;
	}

	public void setIdEditeur(String idEditeur) {
		this.idEditeur = idEditeur;
	}

	@Column(name = "PRIXUNITAIRE", precision = 0)
	public BigDecimal getPrixunitaire() {
		return this.prixunitaire;
	}

	public void setPrixunitaire(BigDecimal prixunitaire) {
		this.prixunitaire = prixunitaire;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwPrixunitairesId))
			return false;
		VwPrixunitairesId castOther = (VwPrixunitairesId) other;

		return ((this.getHorsserie() == castOther.getHorsserie()) || (this
				.getHorsserie() != null && castOther.getHorsserie() != null && this
				.getHorsserie().equals(castOther.getHorsserie())))
				&& ((this.getIdSerie() == castOther.getIdSerie()) || (this
						.getIdSerie() != null && castOther.getIdSerie() != null && this
						.getIdSerie().equals(castOther.getIdSerie())))
				&& ((this.getIdEditeur() == castOther.getIdEditeur()) || (this
						.getIdEditeur() != null
						&& castOther.getIdEditeur() != null && this
						.getIdEditeur().equals(castOther.getIdEditeur())))
				&& ((this.getPrixunitaire() == castOther.getPrixunitaire()) || (this
						.getPrixunitaire() != null
						&& castOther.getPrixunitaire() != null && this
						.getPrixunitaire().equals(castOther.getPrixunitaire())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getHorsserie() == null ? 0 : this.getHorsserie().hashCode());
		result = 37 * result
				+ (getIdSerie() == null ? 0 : this.getIdSerie().hashCode());
		result = 37 * result
				+ (getIdEditeur() == null ? 0 : this.getIdEditeur().hashCode());
		result = 37
				* result
				+ (getPrixunitaire() == null ? 0 : this.getPrixunitaire()
						.hashCode());
		return result;
	}

}
