package org.tetram.reveng;

// Generated 1 mai 2012 09:51:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Albums generated by hbm2java
 */
@Entity
@Table(name = "ALBUMS")
public class Albums implements java.io.Serializable {

	private String idAlbum;
	private Series series;
	private Short moisparution;
	private Short anneeparution;
	private Short tome;
	private Short tomedebut;
	private Short tomefin;
	private Short horsserie;
	private Short integrale;
	private Short achat;
	private Integer nbeditions;
	private Integer complet;
	private Character initialetitrealbum;
	private Date dcAlbums;
	private Date dmAlbums;
	private String titrealbum;
	private String sujetalbum;
	private String remarquesalbum;
	private String soundextitrealbum;
	private Short notation;
	private Set couvertureses = new HashSet(0);
	private Set editionses = new HashSet(0);
	private Set couvertureses_1 = new HashSet(0);
	private Set auteurses = new HashSet(0);
	private Set editionses_1 = new HashSet(0);
	private Set auteurses_1 = new HashSet(0);

	public Albums() {
	}

	public Albums(String idAlbum, Date dcAlbums, Date dmAlbums) {
		this.idAlbum = idAlbum;
		this.dcAlbums = dcAlbums;
		this.dmAlbums = dmAlbums;
	}

	public Albums(String idAlbum, Series series, Short moisparution,
			Short anneeparution, Short tome, Short tomedebut, Short tomefin,
			Short horsserie, Short integrale, Short achat, Integer nbeditions,
			Integer complet, Character initialetitrealbum, Date dcAlbums,
			Date dmAlbums, String titrealbum, String sujetalbum,
			String remarquesalbum, String soundextitrealbum, Short notation,
			Set couvertureses, Set editionses, Set couvertureses_1,
			Set auteurses, Set editionses_1, Set auteurses_1) {
		this.idAlbum = idAlbum;
		this.series = series;
		this.moisparution = moisparution;
		this.anneeparution = anneeparution;
		this.tome = tome;
		this.tomedebut = tomedebut;
		this.tomefin = tomefin;
		this.horsserie = horsserie;
		this.integrale = integrale;
		this.achat = achat;
		this.nbeditions = nbeditions;
		this.complet = complet;
		this.initialetitrealbum = initialetitrealbum;
		this.dcAlbums = dcAlbums;
		this.dmAlbums = dmAlbums;
		this.titrealbum = titrealbum;
		this.sujetalbum = sujetalbum;
		this.remarquesalbum = remarquesalbum;
		this.soundextitrealbum = soundextitrealbum;
		this.notation = notation;
		this.couvertureses = couvertureses;
		this.editionses = editionses;
		this.couvertureses_1 = couvertureses_1;
		this.auteurses = auteurses;
		this.editionses_1 = editionses_1;
		this.auteurses_1 = auteurses_1;
	}

	@Id
	@Column(name = "ID_ALBUM", unique = true, nullable = false, length = 38)
	public String getIdAlbum() {
		return this.idAlbum;
	}

	public void setIdAlbum(String idAlbum) {
		this.idAlbum = idAlbum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SERIE")
	public Series getSeries() {
		return this.series;
	}

	public void setSeries(Series series) {
		this.series = series;
	}

	@Column(name = "MOISPARUTION")
	public Short getMoisparution() {
		return this.moisparution;
	}

	public void setMoisparution(Short moisparution) {
		this.moisparution = moisparution;
	}

	@Column(name = "ANNEEPARUTION")
	public Short getAnneeparution() {
		return this.anneeparution;
	}

	public void setAnneeparution(Short anneeparution) {
		this.anneeparution = anneeparution;
	}

	@Column(name = "TOME")
	public Short getTome() {
		return this.tome;
	}

	public void setTome(Short tome) {
		this.tome = tome;
	}

	@Column(name = "TOMEDEBUT")
	public Short getTomedebut() {
		return this.tomedebut;
	}

	public void setTomedebut(Short tomedebut) {
		this.tomedebut = tomedebut;
	}

	@Column(name = "TOMEFIN")
	public Short getTomefin() {
		return this.tomefin;
	}

	public void setTomefin(Short tomefin) {
		this.tomefin = tomefin;
	}

	@Column(name = "HORSSERIE")
	public Short getHorsserie() {
		return this.horsserie;
	}

	public void setHorsserie(Short horsserie) {
		this.horsserie = horsserie;
	}

	@Column(name = "INTEGRALE")
	public Short getIntegrale() {
		return this.integrale;
	}

	public void setIntegrale(Short integrale) {
		this.integrale = integrale;
	}

	@Column(name = "ACHAT")
	public Short getAchat() {
		return this.achat;
	}

	public void setAchat(Short achat) {
		this.achat = achat;
	}

	@Column(name = "NBEDITIONS")
	public Integer getNbeditions() {
		return this.nbeditions;
	}

	public void setNbeditions(Integer nbeditions) {
		this.nbeditions = nbeditions;
	}

	@Column(name = "COMPLET")
	public Integer getComplet() {
		return this.complet;
	}

	public void setComplet(Integer complet) {
		this.complet = complet;
	}

	@Column(name = "INITIALETITREALBUM", length = 1)
	public Character getInitialetitrealbum() {
		return this.initialetitrealbum;
	}

	public void setInitialetitrealbum(Character initialetitrealbum) {
		this.initialetitrealbum = initialetitrealbum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_ALBUMS", nullable = false, length = 19)
	public Date getDcAlbums() {
		return this.dcAlbums;
	}

	public void setDcAlbums(Date dcAlbums) {
		this.dcAlbums = dcAlbums;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_ALBUMS", nullable = false, length = 19)
	public Date getDmAlbums() {
		return this.dmAlbums;
	}

	public void setDmAlbums(Date dmAlbums) {
		this.dmAlbums = dmAlbums;
	}

	@Column(name = "TITREALBUM", length = 150)
	public String getTitrealbum() {
		return this.titrealbum;
	}

	public void setTitrealbum(String titrealbum) {
		this.titrealbum = titrealbum;
	}

	@Column(name = "SUJETALBUM", length = 0)
	public String getSujetalbum() {
		return this.sujetalbum;
	}

	public void setSujetalbum(String sujetalbum) {
		this.sujetalbum = sujetalbum;
	}

	@Column(name = "REMARQUESALBUM", length = 0)
	public String getRemarquesalbum() {
		return this.remarquesalbum;
	}

	public void setRemarquesalbum(String remarquesalbum) {
		this.remarquesalbum = remarquesalbum;
	}

	@Column(name = "SOUNDEXTITREALBUM", length = 30)
	public String getSoundextitrealbum() {
		return this.soundextitrealbum;
	}

	public void setSoundextitrealbum(String soundextitrealbum) {
		this.soundextitrealbum = soundextitrealbum;
	}

	@Column(name = "NOTATION")
	public Short getNotation() {
		return this.notation;
	}

	public void setNotation(Short notation) {
		this.notation = notation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "albums")
	public Set getCouvertureses() {
		return this.couvertureses;
	}

	public void setCouvertureses(Set couvertureses) {
		this.couvertureses = couvertureses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "albums")
	public Set getEditionses() {
		return this.editionses;
	}

	public void setEditionses(Set editionses) {
		this.editionses = editionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "albums")
	public Set getCouvertureses_1() {
		return this.couvertureses_1;
	}

	public void setCouvertureses_1(Set couvertureses_1) {
		this.couvertureses_1 = couvertureses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "albums")
	public Set getAuteurses() {
		return this.auteurses;
	}

	public void setAuteurses(Set auteurses) {
		this.auteurses = auteurses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "albums")
	public Set getEditionses_1() {
		return this.editionses_1;
	}

	public void setEditionses_1(Set editionses_1) {
		this.editionses_1 = editionses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "albums")
	public Set getAuteurses_1() {
		return this.auteurses_1;
	}

	public void setAuteurses_1(Set auteurses_1) {
		this.auteurses_1 = auteurses_1;
	}

}
