package org.tetram.reveng;

// Generated 1 mai 2012 09:51:32 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuteursParabdId generated by hbm2java
 */
@Embeddable
public class AuteursParabdId implements java.io.Serializable {

	private String idParabd;
	private String idPersonne;

	public AuteursParabdId() {
	}

	public AuteursParabdId(String idParabd, String idPersonne) {
		this.idParabd = idParabd;
		this.idPersonne = idPersonne;
	}

	@Column(name = "ID_PARABD", nullable = false, length = 38)
	public String getIdParabd() {
		return this.idParabd;
	}

	public void setIdParabd(String idParabd) {
		this.idParabd = idParabd;
	}

	@Column(name = "ID_PERSONNE", nullable = false, length = 38)
	public String getIdPersonne() {
		return this.idPersonne;
	}

	public void setIdPersonne(String idPersonne) {
		this.idPersonne = idPersonne;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuteursParabdId))
			return false;
		AuteursParabdId castOther = (AuteursParabdId) other;

		return ((this.getIdParabd() == castOther.getIdParabd()) || (this
				.getIdParabd() != null && castOther.getIdParabd() != null && this
				.getIdParabd().equals(castOther.getIdParabd())))
				&& ((this.getIdPersonne() == castOther.getIdPersonne()) || (this
						.getIdPersonne() != null
						&& castOther.getIdPersonne() != null && this
						.getIdPersonne().equals(castOther.getIdPersonne())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdParabd() == null ? 0 : this.getIdParabd().hashCode());
		result = 37
				* result
				+ (getIdPersonne() == null ? 0 : this.getIdPersonne()
						.hashCode());
		return result;
	}

}
