package org.tetram.reveng;

// Generated 1 mai 2012 09:51:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Collections generated by hbm2java
 */
@Entity
@Table(name = "COLLECTIONS")
public class Collections implements java.io.Serializable {

	private String idCollection;
	private Editeurs editeurs;
	private char initialenomcollection;
	private Date dcCollections;
	private Date dmCollections;
	private String nomcollection;
	private Set serieses = new HashSet(0);
	private Set editionses = new HashSet(0);

	public Collections() {
	}

	public Collections(String idCollection, Editeurs editeurs,
			char initialenomcollection, Date dcCollections, Date dmCollections) {
		this.idCollection = idCollection;
		this.editeurs = editeurs;
		this.initialenomcollection = initialenomcollection;
		this.dcCollections = dcCollections;
		this.dmCollections = dmCollections;
	}

	public Collections(String idCollection, Editeurs editeurs,
			char initialenomcollection, Date dcCollections, Date dmCollections,
			String nomcollection, Set serieses, Set editionses) {
		this.idCollection = idCollection;
		this.editeurs = editeurs;
		this.initialenomcollection = initialenomcollection;
		this.dcCollections = dcCollections;
		this.dmCollections = dmCollections;
		this.nomcollection = nomcollection;
		this.serieses = serieses;
		this.editionses = editionses;
	}

	@Id
	@Column(name = "ID_COLLECTION", unique = true, nullable = false, length = 38)
	public String getIdCollection() {
		return this.idCollection;
	}

	public void setIdCollection(String idCollection) {
		this.idCollection = idCollection;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EDITEUR", nullable = false)
	public Editeurs getEditeurs() {
		return this.editeurs;
	}

	public void setEditeurs(Editeurs editeurs) {
		this.editeurs = editeurs;
	}

	@Column(name = "INITIALENOMCOLLECTION", nullable = false, length = 1)
	public char getInitialenomcollection() {
		return this.initialenomcollection;
	}

	public void setInitialenomcollection(char initialenomcollection) {
		this.initialenomcollection = initialenomcollection;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_COLLECTIONS", nullable = false, length = 19)
	public Date getDcCollections() {
		return this.dcCollections;
	}

	public void setDcCollections(Date dcCollections) {
		this.dcCollections = dcCollections;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_COLLECTIONS", nullable = false, length = 19)
	public Date getDmCollections() {
		return this.dmCollections;
	}

	public void setDmCollections(Date dmCollections) {
		this.dmCollections = dmCollections;
	}

	@Column(name = "NOMCOLLECTION", length = 50)
	public String getNomcollection() {
		return this.nomcollection;
	}

	public void setNomcollection(String nomcollection) {
		this.nomcollection = nomcollection;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "collections")
	public Set getSerieses() {
		return this.serieses;
	}

	public void setSerieses(Set serieses) {
		this.serieses = serieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "collections")
	public Set getEditionses() {
		return this.editionses;
	}

	public void setEditionses(Set editionses) {
		this.editionses = editionses;
	}

}
