package org.tetram.reveng;

// Generated 1 mai 2012 09:51:32 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CotesParabdId generated by hbm2java
 */
@Embeddable
public class CotesParabdId implements java.io.Serializable {

	private short anneecote;
	private String idParabd;

	public CotesParabdId() {
	}

	public CotesParabdId(short anneecote, String idParabd) {
		this.anneecote = anneecote;
		this.idParabd = idParabd;
	}

	@Column(name = "ANNEECOTE", nullable = false)
	public short getAnneecote() {
		return this.anneecote;
	}

	public void setAnneecote(short anneecote) {
		this.anneecote = anneecote;
	}

	@Column(name = "ID_PARABD", nullable = false, length = 38)
	public String getIdParabd() {
		return this.idParabd;
	}

	public void setIdParabd(String idParabd) {
		this.idParabd = idParabd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CotesParabdId))
			return false;
		CotesParabdId castOther = (CotesParabdId) other;

		return (this.getAnneecote() == castOther.getAnneecote())
				&& ((this.getIdParabd() == castOther.getIdParabd()) || (this
						.getIdParabd() != null
						&& castOther.getIdParabd() != null && this
						.getIdParabd().equals(castOther.getIdParabd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAnneecote();
		result = 37 * result
				+ (getIdParabd() == null ? 0 : this.getIdParabd().hashCode());
		return result;
	}

}
