package org.tetram.reveng;

// Generated 1 mai 2012 09:51:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Cotes generated by hbm2java
 */
@Entity
@Table(name = "COTES", uniqueConstraints = @UniqueConstraint(columnNames = "ID_COTE"))
public class Cotes implements java.io.Serializable {

	private CotesId id;
	private Editions editions;
	private String idCote;
	private BigDecimal prixcote;
	private Date dcCotes;
	private Date dmCotes;

	public Cotes() {
	}

	public Cotes(CotesId id, Editions editions, String idCote,
			BigDecimal prixcote, Date dcCotes, Date dmCotes) {
		this.id = id;
		this.editions = editions;
		this.idCote = idCote;
		this.prixcote = prixcote;
		this.dcCotes = dcCotes;
		this.dmCotes = dmCotes;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "anneecote", column = @Column(name = "ANNEECOTE", nullable = false)),
			@AttributeOverride(name = "idEdition", column = @Column(name = "ID_EDITION", nullable = false, length = 38)) })
	public CotesId getId() {
		return this.id;
	}

	public void setId(CotesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EDITION", nullable = false, insertable = false, updatable = false)
	public Editions getEditions() {
		return this.editions;
	}

	public void setEditions(Editions editions) {
		this.editions = editions;
	}

	@Column(name = "ID_COTE", unique = true, nullable = false, length = 38)
	public String getIdCote() {
		return this.idCote;
	}

	public void setIdCote(String idCote) {
		this.idCote = idCote;
	}

	@Column(name = "PRIXCOTE", nullable = false, precision = 15)
	public BigDecimal getPrixcote() {
		return this.prixcote;
	}

	public void setPrixcote(BigDecimal prixcote) {
		this.prixcote = prixcote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_COTES", nullable = false, length = 19)
	public Date getDcCotes() {
		return this.dcCotes;
	}

	public void setDcCotes(Date dcCotes) {
		this.dcCotes = dcCotes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_COTES", nullable = false, length = 19)
	public Date getDmCotes() {
		return this.dmCotes;
	}

	public void setDmCotes(Date dmCotes) {
		this.dmCotes = dmCotes;
	}

}
