package org.tetram.reveng;

// Generated 1 mai 2012 09:51:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Genres generated by hbm2java
 */
@Entity
@Table(name = "GENRES")
public class Genres implements java.io.Serializable {

	private String idGenre;
	private Character initialegenre;
	private Date dcGenres;
	private Date dmGenres;
	private String genre;
	private Set genreserieses = new HashSet(0);
	private Set genreserieses_1 = new HashSet(0);

	public Genres() {
	}

	public Genres(String idGenre, Date dcGenres, Date dmGenres) {
		this.idGenre = idGenre;
		this.dcGenres = dcGenres;
		this.dmGenres = dmGenres;
	}

	public Genres(String idGenre, Character initialegenre, Date dcGenres,
			Date dmGenres, String genre, Set genreserieses, Set genreserieses_1) {
		this.idGenre = idGenre;
		this.initialegenre = initialegenre;
		this.dcGenres = dcGenres;
		this.dmGenres = dmGenres;
		this.genre = genre;
		this.genreserieses = genreserieses;
		this.genreserieses_1 = genreserieses_1;
	}

	@Id
	@Column(name = "ID_GENRE", unique = true, nullable = false, length = 38)
	public String getIdGenre() {
		return this.idGenre;
	}

	public void setIdGenre(String idGenre) {
		this.idGenre = idGenre;
	}

	@Column(name = "INITIALEGENRE", length = 1)
	public Character getInitialegenre() {
		return this.initialegenre;
	}

	public void setInitialegenre(Character initialegenre) {
		this.initialegenre = initialegenre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_GENRES", nullable = false, length = 19)
	public Date getDcGenres() {
		return this.dcGenres;
	}

	public void setDcGenres(Date dcGenres) {
		this.dcGenres = dcGenres;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_GENRES", nullable = false, length = 19)
	public Date getDmGenres() {
		return this.dmGenres;
	}

	public void setDmGenres(Date dmGenres) {
		this.dmGenres = dmGenres;
	}

	@Column(name = "GENRE", length = 30)
	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genres")
	public Set getGenreserieses() {
		return this.genreserieses;
	}

	public void setGenreserieses(Set genreserieses) {
		this.genreserieses = genreserieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genres")
	public Set getGenreserieses_1() {
		return this.genreserieses_1;
	}

	public void setGenreserieses_1(Set genreserieses_1) {
		this.genreserieses_1 = genreserieses_1;
	}

}
