package org.tetram.reveng;

// Generated 1 mai 2012 09:51:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personnes generated by hbm2java
 */
@Entity
@Table(name = "PERSONNES")
public class Personnes implements java.io.Serializable {

	private String idPersonne;
	private Character initialenompersonne;
	private String siteweb;
	private Date dcPersonnes;
	private Date dmPersonnes;
	private String nompersonne;
	private String biographie;
	private Set auteursParabds = new HashSet(0);
	private Set auteurses = new HashSet(0);
	private Set auteursSerieses = new HashSet(0);
	private Set auteurses_1 = new HashSet(0);
	private Set auteursParabds_1 = new HashSet(0);
	private Set auteursSerieses_1 = new HashSet(0);

	public Personnes() {
	}

	public Personnes(String idPersonne, Date dcPersonnes, Date dmPersonnes) {
		this.idPersonne = idPersonne;
		this.dcPersonnes = dcPersonnes;
		this.dmPersonnes = dmPersonnes;
	}

	public Personnes(String idPersonne, Character initialenompersonne,
			String siteweb, Date dcPersonnes, Date dmPersonnes,
			String nompersonne, String biographie, Set auteursParabds,
			Set auteurses, Set auteursSerieses, Set auteurses_1,
			Set auteursParabds_1, Set auteursSerieses_1) {
		this.idPersonne = idPersonne;
		this.initialenompersonne = initialenompersonne;
		this.siteweb = siteweb;
		this.dcPersonnes = dcPersonnes;
		this.dmPersonnes = dmPersonnes;
		this.nompersonne = nompersonne;
		this.biographie = biographie;
		this.auteursParabds = auteursParabds;
		this.auteurses = auteurses;
		this.auteursSerieses = auteursSerieses;
		this.auteurses_1 = auteurses_1;
		this.auteursParabds_1 = auteursParabds_1;
		this.auteursSerieses_1 = auteursSerieses_1;
	}

	@Id
	@Column(name = "ID_PERSONNE", unique = true, nullable = false, length = 38)
	public String getIdPersonne() {
		return this.idPersonne;
	}

	public void setIdPersonne(String idPersonne) {
		this.idPersonne = idPersonne;
	}

	@Column(name = "INITIALENOMPERSONNE", length = 1)
	public Character getInitialenompersonne() {
		return this.initialenompersonne;
	}

	public void setInitialenompersonne(Character initialenompersonne) {
		this.initialenompersonne = initialenompersonne;
	}

	@Column(name = "SITEWEB")
	public String getSiteweb() {
		return this.siteweb;
	}

	public void setSiteweb(String siteweb) {
		this.siteweb = siteweb;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_PERSONNES", nullable = false, length = 19)
	public Date getDcPersonnes() {
		return this.dcPersonnes;
	}

	public void setDcPersonnes(Date dcPersonnes) {
		this.dcPersonnes = dcPersonnes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_PERSONNES", nullable = false, length = 19)
	public Date getDmPersonnes() {
		return this.dmPersonnes;
	}

	public void setDmPersonnes(Date dmPersonnes) {
		this.dmPersonnes = dmPersonnes;
	}

	@Column(name = "NOMPERSONNE", length = 150)
	public String getNompersonne() {
		return this.nompersonne;
	}

	public void setNompersonne(String nompersonne) {
		this.nompersonne = nompersonne;
	}

	@Column(name = "BIOGRAPHIE", length = 0)
	public String getBiographie() {
		return this.biographie;
	}

	public void setBiographie(String biographie) {
		this.biographie = biographie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnes")
	public Set getAuteursParabds() {
		return this.auteursParabds;
	}

	public void setAuteursParabds(Set auteursParabds) {
		this.auteursParabds = auteursParabds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnes")
	public Set getAuteurses() {
		return this.auteurses;
	}

	public void setAuteurses(Set auteurses) {
		this.auteurses = auteurses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnes")
	public Set getAuteursSerieses() {
		return this.auteursSerieses;
	}

	public void setAuteursSerieses(Set auteursSerieses) {
		this.auteursSerieses = auteursSerieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnes")
	public Set getAuteurses_1() {
		return this.auteurses_1;
	}

	public void setAuteurses_1(Set auteurses_1) {
		this.auteurses_1 = auteurses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnes")
	public Set getAuteursParabds_1() {
		return this.auteursParabds_1;
	}

	public void setAuteursParabds_1(Set auteursParabds_1) {
		this.auteursParabds_1 = auteursParabds_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personnes")
	public Set getAuteursSerieses_1() {
		return this.auteursSerieses_1;
	}

	public void setAuteursSerieses_1(Set auteursSerieses_1) {
		this.auteursSerieses_1 = auteursSerieses_1;
	}

}
