package org.tetram.reveng;

// Generated 1 mai 2012 09:51:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Series generated by hbm2java
 */
@Entity
@Table(name = "SERIES")
public class Series implements java.io.Serializable {

	private String idSerie;
	private Collections collections;
	private Editeurs editeurs;
	private Short terminee;
	private Short complete;
	private String siteweb;
	private Short suivremanquants;
	private Short suivresorties;
	private char initialetitreserie;
	private Date dcSeries;
	private Date dmSeries;
	private Integer nbAlbums;
	private Integer etat;
	private Integer reliure;
	private Integer typeedition;
	private Integer orientation;
	private Integer formatedition;
	private Integer senslecture;
	private Short vo;
	private Short couleur;
	private String titreserie;
	private String sujetserie;
	private String remarquesserie;
	private String soundextitreserie;
	private Short notation;
	private Set parabds = new HashSet(0);
	private Set genreserieses = new HashSet(0);
	private Set auteursSerieses = new HashSet(0);
	private Set auteursSerieses_1 = new HashSet(0);
	private Set albumses = new HashSet(0);
	private Set genreserieses_1 = new HashSet(0);

	public Series() {
	}

	public Series(String idSerie, Editeurs editeurs, char initialetitreserie,
			Date dcSeries, Date dmSeries) {
		this.idSerie = idSerie;
		this.editeurs = editeurs;
		this.initialetitreserie = initialetitreserie;
		this.dcSeries = dcSeries;
		this.dmSeries = dmSeries;
	}

	public Series(String idSerie, Collections collections, Editeurs editeurs,
			Short terminee, Short complete, String siteweb,
			Short suivremanquants, Short suivresorties,
			char initialetitreserie, Date dcSeries, Date dmSeries,
			Integer nbAlbums, Integer etat, Integer reliure,
			Integer typeedition, Integer orientation, Integer formatedition,
			Integer senslecture, Short vo, Short couleur, String titreserie,
			String sujetserie, String remarquesserie, String soundextitreserie,
			Short notation, Set parabds, Set genreserieses,
			Set auteursSerieses, Set auteursSerieses_1, Set albumses,
			Set genreserieses_1) {
		this.idSerie = idSerie;
		this.collections = collections;
		this.editeurs = editeurs;
		this.terminee = terminee;
		this.complete = complete;
		this.siteweb = siteweb;
		this.suivremanquants = suivremanquants;
		this.suivresorties = suivresorties;
		this.initialetitreserie = initialetitreserie;
		this.dcSeries = dcSeries;
		this.dmSeries = dmSeries;
		this.nbAlbums = nbAlbums;
		this.etat = etat;
		this.reliure = reliure;
		this.typeedition = typeedition;
		this.orientation = orientation;
		this.formatedition = formatedition;
		this.senslecture = senslecture;
		this.vo = vo;
		this.couleur = couleur;
		this.titreserie = titreserie;
		this.sujetserie = sujetserie;
		this.remarquesserie = remarquesserie;
		this.soundextitreserie = soundextitreserie;
		this.notation = notation;
		this.parabds = parabds;
		this.genreserieses = genreserieses;
		this.auteursSerieses = auteursSerieses;
		this.auteursSerieses_1 = auteursSerieses_1;
		this.albumses = albumses;
		this.genreserieses_1 = genreserieses_1;
	}

	@Id
	@Column(name = "ID_SERIE", unique = true, nullable = false, length = 38)
	public String getIdSerie() {
		return this.idSerie;
	}

	public void setIdSerie(String idSerie) {
		this.idSerie = idSerie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_COLLECTION")
	public Collections getCollections() {
		return this.collections;
	}

	public void setCollections(Collections collections) {
		this.collections = collections;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EDITEUR", nullable = false)
	public Editeurs getEditeurs() {
		return this.editeurs;
	}

	public void setEditeurs(Editeurs editeurs) {
		this.editeurs = editeurs;
	}

	@Column(name = "TERMINEE")
	public Short getTerminee() {
		return this.terminee;
	}

	public void setTerminee(Short terminee) {
		this.terminee = terminee;
	}

	@Column(name = "COMPLETE")
	public Short getComplete() {
		return this.complete;
	}

	public void setComplete(Short complete) {
		this.complete = complete;
	}

	@Column(name = "SITEWEB")
	public String getSiteweb() {
		return this.siteweb;
	}

	public void setSiteweb(String siteweb) {
		this.siteweb = siteweb;
	}

	@Column(name = "SUIVREMANQUANTS")
	public Short getSuivremanquants() {
		return this.suivremanquants;
	}

	public void setSuivremanquants(Short suivremanquants) {
		this.suivremanquants = suivremanquants;
	}

	@Column(name = "SUIVRESORTIES")
	public Short getSuivresorties() {
		return this.suivresorties;
	}

	public void setSuivresorties(Short suivresorties) {
		this.suivresorties = suivresorties;
	}

	@Column(name = "INITIALETITRESERIE", nullable = false, length = 1)
	public char getInitialetitreserie() {
		return this.initialetitreserie;
	}

	public void setInitialetitreserie(char initialetitreserie) {
		this.initialetitreserie = initialetitreserie;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DC_SERIES", nullable = false, length = 19)
	public Date getDcSeries() {
		return this.dcSeries;
	}

	public void setDcSeries(Date dcSeries) {
		this.dcSeries = dcSeries;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DM_SERIES", nullable = false, length = 19)
	public Date getDmSeries() {
		return this.dmSeries;
	}

	public void setDmSeries(Date dmSeries) {
		this.dmSeries = dmSeries;
	}

	@Column(name = "NB_ALBUMS")
	public Integer getNbAlbums() {
		return this.nbAlbums;
	}

	public void setNbAlbums(Integer nbAlbums) {
		this.nbAlbums = nbAlbums;
	}

	@Column(name = "ETAT")
	public Integer getEtat() {
		return this.etat;
	}

	public void setEtat(Integer etat) {
		this.etat = etat;
	}

	@Column(name = "RELIURE")
	public Integer getReliure() {
		return this.reliure;
	}

	public void setReliure(Integer reliure) {
		this.reliure = reliure;
	}

	@Column(name = "TYPEEDITION")
	public Integer getTypeedition() {
		return this.typeedition;
	}

	public void setTypeedition(Integer typeedition) {
		this.typeedition = typeedition;
	}

	@Column(name = "ORIENTATION")
	public Integer getOrientation() {
		return this.orientation;
	}

	public void setOrientation(Integer orientation) {
		this.orientation = orientation;
	}

	@Column(name = "FORMATEDITION")
	public Integer getFormatedition() {
		return this.formatedition;
	}

	public void setFormatedition(Integer formatedition) {
		this.formatedition = formatedition;
	}

	@Column(name = "SENSLECTURE")
	public Integer getSenslecture() {
		return this.senslecture;
	}

	public void setSenslecture(Integer senslecture) {
		this.senslecture = senslecture;
	}

	@Column(name = "VO")
	public Short getVo() {
		return this.vo;
	}

	public void setVo(Short vo) {
		this.vo = vo;
	}

	@Column(name = "COULEUR")
	public Short getCouleur() {
		return this.couleur;
	}

	public void setCouleur(Short couleur) {
		this.couleur = couleur;
	}

	@Column(name = "TITRESERIE", length = 150)
	public String getTitreserie() {
		return this.titreserie;
	}

	public void setTitreserie(String titreserie) {
		this.titreserie = titreserie;
	}

	@Column(name = "SUJETSERIE", length = 0)
	public String getSujetserie() {
		return this.sujetserie;
	}

	public void setSujetserie(String sujetserie) {
		this.sujetserie = sujetserie;
	}

	@Column(name = "REMARQUESSERIE", length = 0)
	public String getRemarquesserie() {
		return this.remarquesserie;
	}

	public void setRemarquesserie(String remarquesserie) {
		this.remarquesserie = remarquesserie;
	}

	@Column(name = "SOUNDEXTITRESERIE", length = 30)
	public String getSoundextitreserie() {
		return this.soundextitreserie;
	}

	public void setSoundextitreserie(String soundextitreserie) {
		this.soundextitreserie = soundextitreserie;
	}

	@Column(name = "NOTATION")
	public Short getNotation() {
		return this.notation;
	}

	public void setNotation(Short notation) {
		this.notation = notation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "series")
	public Set getParabds() {
		return this.parabds;
	}

	public void setParabds(Set parabds) {
		this.parabds = parabds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "series")
	public Set getGenreserieses() {
		return this.genreserieses;
	}

	public void setGenreserieses(Set genreserieses) {
		this.genreserieses = genreserieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "series")
	public Set getAuteursSerieses() {
		return this.auteursSerieses;
	}

	public void setAuteursSerieses(Set auteursSerieses) {
		this.auteursSerieses = auteursSerieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "series")
	public Set getAuteursSerieses_1() {
		return this.auteursSerieses_1;
	}

	public void setAuteursSerieses_1(Set auteursSerieses_1) {
		this.auteursSerieses_1 = auteursSerieses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "series")
	public Set getAlbumses() {
		return this.albumses;
	}

	public void setAlbumses(Set albumses) {
		this.albumses = albumses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "series")
	public Set getGenreserieses_1() {
		return this.genreserieses_1;
	}

	public void setGenreserieses_1(Set genreserieses_1) {
		this.genreserieses_1 = genreserieses_1;
	}

}
