unit uPSC_BdtkRegEx;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
Uses uPSCompiler;

procedure SIRegister_TBdtkRegEx(CL: TPSPascalCompiler);
procedure SIRegister_BdtkRegEx(CL: TPSPascalCompiler);
implementation
Uses BdtkRegEx
;
procedure SIRegister_TBdtkRegEx(CL: TPSPascalCompiler);
begin
  with CL.AddClass(CL.FindClass('TOBJECT'),TBdtkRegEx) do
  begin
    RegisterPublishedProperties;
    RegisterMethod('Constructor Create');
  end;
end;

procedure SIRegister_BdtkRegEx(CL: TPSPascalCompiler);
begin
  SIRegister_TBdtkRegEx(CL);
 CL.AddDelphiFunction('Function ExtractRegEx( const Chaine, aRegEx : AnsiString) : AnsiString');
 CL.AddDelphiFunction('Function ExtractRegExGroup( const Chaine, aRegEx, Group : AnsiString) : AnsiString');
end;

end.
