unit BDTK.Web.Browser.Utils;

interface

uses
  Winapi.Messages, uCEFConstants;

const
  // les threads de CEF empêchent d'utiliser Synchronize
  // et puisque certains events CEF ne sont pas déclenchés dans le thread principal... il ne reste que la solution des messages
  BDTKBROWSER = WM_APP + $100;
  BDTKBROWSER_CLOSE = BDTKBROWSER + $00;
  BDTKBROWSER_MODALRESULT = BDTKBROWSER + $01;
  BDTKBROWSER_DESTROYWNDPARENT = BDTKBROWSER + $02;
  BDTKBROWSER_DESTROYTAB = BDTKBROWSER + $03;

  BDTKBROWSER_RUN_ACTION = WM_APP + $03;
  BDTKBROWSER_SHOWDEVTOOLS = WM_APP + $04;
  BDTKBROWSER_HIDEDEVTOOLS = WM_APP + $05;

  BDTKBROWSER_CONTEXTMENU_TOOLS = MENU_ID_USER_FIRST;
  BDTKBROWSER_CONTEXTMENU_IMPORT = MENU_ID_USER_FIRST + $100;

  BDTKBROWSER_CONTEXTMENU_TOGGLEDEVTOOLS = BDTKBROWSER_CONTEXTMENU_TOOLS + $01;
  BDTKBROWSER_CONTEXTMENU_TOGGLEAUDIO = BDTKBROWSER_CONTEXTMENU_TOOLS + $02;
  BDTKBROWSER_CONTEXTMENU_LINK_TO_NEW_TAB = BDTKBROWSER_CONTEXTMENU_TOOLS + $03;
  BDTKBROWSER_CONTEXTMENU_COPY_LINK = BDTKBROWSER_CONTEXTMENU_TOOLS + $04;
  BDTKBROWSER_CONTEXTMENU_EMPTY_CACHE_AND_RELOAD = BDTKBROWSER_CONTEXTMENU_TOOLS + $05;

implementation

end.
