parameters:
    bdtheque_datamodel.album_manager.class: BDTheque\DataModelBundle\Manager\AlbumManager
    bdtheque_datamodel.collection_manager.class: BDTheque\DataModelBundle\Manager\CollectionManager
    bdtheque_datamodel.editeur_manager.class: BDTheque\DataModelBundle\Manager\EditeurManager
    bdtheque_datamodel.edition_manager.class: BDTheque\DataModelBundle\Manager\EditionManager
    bdtheque_datamodel.genre_manager.class: BDTheque\DataModelBundle\Manager\GenreManager
    bdtheque_datamodel.image_manager.class: BDTheque\DataModelBundle\Manager\ImageManager
    bdtheque_datamodel.personne_manager.class: BDTheque\DataModelBundle\Manager\PersonneManager
    bdtheque_datamodel.serie_manager.class: BDTheque\DataModelBundle\Manager\SerieManager
    bdtheque_datamodel.album_selector.class: BDTheque\DataModelBundle\Form\Selector\AlbumSelectorType
    bdtheque_datamodel.collection_selector.class: BDTheque\DataModelBundle\Form\Selector\CollectionSelectorType
    bdtheque_datamodel.editeur_selector.class: BDTheque\DataModelBundle\Form\Selector\EditeurSelectorType
    bdtheque_datamodel.edition_selector.class: BDTheque\DataModelBundle\Form\Selector\EditionSelectorType
    bdtheque_datamodel.genre_selector.class: BDTheque\DataModelBundle\Form\Selector\GenreSelectorType
    bdtheque_datamodel.personne_selector.class: BDTheque\DataModelBundle\Form\Selector\PersonneSelectorType
    bdtheque_datamodel.serie_selector.class: BDTheque\DataModelBundle\Form\Selector\SerieSelectorType

services:
    bdtheque_datamodel.type.album_selector:
        class: %bdtheque_datamodel.album_selector.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: album_selector }
    bdtheque_datamodel.type.collection_selector:
        class: %bdtheque_datamodel.collection_selector.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: collection_selector }
    bdtheque_datamodel.type.editeur_selector:
        class: %bdtheque_datamodel.editeur_selector.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: editeur_selector }
    bdtheque_datamodel.type.edition_selector:
        class: %bdtheque_datamodel.edition_selector.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: edition_selector }
    bdtheque_datamodel.type.genre_selector:
        class: %bdtheque_datamodel.genre_selector.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: genre_selector }
    bdtheque_datamodel.type.personne_selector:
        class: %bdtheque_datamodel.personne_selector.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: personne_selector }
    bdtheque_datamodel.type.serie_selector:
        class: %bdtheque_datamodel.serie_selector.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: serie_selector }
    bdtheque_datamodel.album_manager:
        class: %bdtheque_datamodel.album_manager.class%
        arguments: ["@doctrine.orm.entity_manager"]
    bdtheque_datamodel.collection_manager:
        class: %bdtheque_datamodel.collection_manager.class%
        arguments: ["@doctrine.orm.entity_manager"]
    bdtheque_datamodel.editeur_manager:
        class: %bdtheque_datamodel.editeur_manager.class%
        arguments: ["@doctrine.orm.entity_manager"]
    bdtheque_datamodel.edition_manager:
        class: %bdtheque_datamodel.edition_manager.class%
        arguments: ["@doctrine.orm.entity_manager"]
    bdtheque_datamodel.genre_manager:
        class: %bdtheque_datamodel.genre_manager.class%
        arguments: ["@doctrine.orm.entity_manager"]
    bdtheque_datamodel.image_manager:
        class: %bdtheque_datamodel.image_manager.class%
        arguments: ["@doctrine.orm.entity_manager"]
    bdtheque_datamodel.personne_manager:
        class: %bdtheque_datamodel.personne_manager.class%
        arguments: ["@doctrine.orm.entity_manager"]
    bdtheque_datamodel.serie_manager:
        class: %bdtheque_datamodel.serie_manager.class%
        arguments: ["@doctrine.orm.entity_manager"]
