<?php

namespace BDTheque\DataModelBundle\DataFixtures\ORM;

use \Doctrine\Common\DataFixtures\AbstractFixture;
use \Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use \Doctrine\Common\Persistence\ObjectManager;

/**
 * Description of LoadPersonneData
 *
 * @author Thierry
 */
class LoadAuteurData extends AbstractFixture implements OrderedFixtureInterface {

    public function getOrder() {
        return FixtureOrder::AUTEUR;
    }

    public function load(ObjectManager $manager) {
        $serie = $this->getReference("SERIE-naufragés d'Ythaq [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-feux d'Askell [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lanfeust de Troy");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lanfeust des étoiles");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Trolls de Troy");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-forêts d'Opale [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Gnomes de Troy");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-chant d'excalibur [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Moréa");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Elixirs");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lanfeust Odyssey");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Conquérants de Troy [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Léo Loden");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-maîtres cartographes [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Cixi de Troy");
        $serie->addScenariste($this->getReference("PERSONNE-Arleston [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sillage");
        $serie->addDessinateur($this->getReference("PERSONNE-Buchet [Philippe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sillage");
        $serie->addColoriste($this->getReference("PERSONNE-Buchet [Philippe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-quête des réponses [La]");
        $serie->addDessinateur($this->getReference("PERSONNE-Buchet [Philippe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-HK - 1er cycle");
        $serie->addScenariste($this->getReference("PERSONNE-Morvan [Jean-David]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sillage");
        $serie->addScenariste($this->getReference("PERSONNE-Morvan [Jean-David]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sir Pyle S. Culape");
        $serie->addScenariste($this->getReference("PERSONNE-Morvan [Jean-David]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Spirou et Fantasio");
        $serie->addScenariste($this->getReference("PERSONNE-Morvan [Jean-David]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Reality show");
        $serie->addScenariste($this->getReference("PERSONNE-Morvan [Jean-David]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-HK - 2ème cycle");
        $serie->addScenariste($this->getReference("PERSONNE-Morvan [Jean-David]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-quête des réponses [La]");
        $serie->addScenariste($this->getReference("PERSONNE-Morvan [Jean-David]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Iznogoud");
        $serie->addScenariste($this->getReference("PERSONNE-Goscinny [René]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Astérix");
        $serie->addScenariste($this->getReference("PERSONNE-Goscinny [René]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Astérix");
        $serie->addDessinateur($this->getReference("PERSONNE-Uderzo [Albert]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-polar savoyard de Fanfoué [Un]");
        $serie->addScenariste($this->getReference("PERSONNE-Meynet [Félix]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-polar savoyard de Fanfoué [Un]");
        $serie->addDessinateur($this->getReference("PERSONNE-Meynet [Félix]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-polar savoyard de Fanfoué [Un]");
        $serie->addColoriste($this->getReference("PERSONNE-Meynet [Félix]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Eternels [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Meynet [Félix]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Eternels [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Meynet [Félix]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Gags de Fanfoué des Pnottas [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Meynet [Félix]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Gags de Fanfoué des Pnottas [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Meynet [Félix]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Gags de Fanfoué des Pnottas [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Meynet [Félix]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Scorpion [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Marini [Enrico]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Scorpion [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-Marini [Enrico]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Asphodèle");
        $serie->addScenariste($this->getReference("PERSONNE-Corbeyran [Eric]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-chant des Stryges [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Corbeyran [Eric]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-loi des 12 tables [La]");
        $serie->addScenariste($this->getReference("PERSONNE-Corbeyran [Eric]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Conjuration d'opale [La]");
        $serie->addScenariste($this->getReference("PERSONNE-Corbeyran [Eric]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Scorpion [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Desberg [Stephen]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-dernier Livre de la Jungle [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Desberg [Stephen]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-immortels [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Desberg [Stephen]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Mayam");
        $serie->addScenariste($this->getReference("PERSONNE-Desberg [Stephen]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Quête de l'Oiseau du Temps [La]");
        $serie->addScenariste($this->getReference("PERSONNE-Le Tendre [Serge]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Quête de l'Oiseau du temps - Avant la Quête [La]");
        $serie->addScenariste($this->getReference("PERSONNE-Le Tendre [Serge]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Peter Pan");
        $serie->addScenariste($this->getReference("PERSONNE-Loisel [Régis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Peter Pan");
        $serie->addDessinateur($this->getReference("PERSONNE-Loisel [Régis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Peter Pan");
        $serie->addColoriste($this->getReference("PERSONNE-Loisel [Régis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Magasin général");
        $serie->addScenariste($this->getReference("PERSONNE-Loisel [Régis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Magasin général");
        $serie->addDessinateur($this->getReference("PERSONNE-Loisel [Régis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Quête de l'Oiseau du Temps [La]");
        $serie->addDessinateur($this->getReference("PERSONNE-Loisel [Régis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Quête de l'Oiseau du temps - Avant la Quête [La]");
        $serie->addScenariste($this->getReference("PERSONNE-Loisel [Régis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Quête de l'Oiseau du temps - Avant la Quête [La]");
        $serie->addDessinateur($this->getReference("PERSONNE-Loisel [Régis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Quête de l'Oiseau du temps - Avant la Quête [La]");
        $serie->addDessinateur($this->getReference("PERSONNE-Lidwine [Dominique]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Eternels [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Yann"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Double masque");
        $serie->addScenariste($this->getReference("PERSONNE-Dufaux [Jean]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Asphodèle");
        $serie->addDessinateur($this->getReference("PERSONNE-Defali [Djillali]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-loi des 12 tables [La]");
        $serie->addDessinateur($this->getReference("PERSONNE-Defali [Djillali]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-On achève bien les cons!");
        $serie->addDessinateur($this->getReference("PERSONNE-Castaza [Phil]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Golden Cup");
        $serie->addScenariste($this->getReference("PERSONNE-Pecqueur [Daniel]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Golden City");
        $serie->addScenariste($this->getReference("PERSONNE-Pecqueur [Daniel]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Golden City");
        $serie->addDessinateur($this->getReference("PERSONNE-Malfin [Nicolas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Volunteer");
        $serie->addScenariste($this->getReference("PERSONNE-Sevestre [Muriel]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Volunteer");
        $serie->addDessinateur($this->getReference("PERSONNE-Springer [Benoît]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Volunteer");
        $serie->addColoriste($this->getReference("PERSONNE-Springer [Benoît]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-XIII");
        $serie->addScenariste($this->getReference("PERSONNE-Van Hamme [Jean]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Largo Winch");
        $serie->addScenariste($this->getReference("PERSONNE-Van Hamme [Jean]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Largo Winch");
        $serie->addDessinateur($this->getReference("PERSONNE-Francq [Philippe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-petit Spirou [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Tome"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-petit Spirou [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Janry"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Nemesis");
        $serie->addScenariste($this->getReference("PERSONNE-Ange"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Paradis perdu");
        $serie->addScenariste($this->getReference("PERSONNE-Ange"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-geste des Chevaliers Dragons [La]");
        $serie->addScenariste($this->getReference("PERSONNE-Ange"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Belladone");
        $serie->addScenariste($this->getReference("PERSONNE-Ange"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-collège invisible [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Ange"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Babel");
        $serie->addScenariste($this->getReference("PERSONNE-Ange"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-cicatrice du souvenir [La]");
        $serie->addScenariste($this->getReference("PERSONNE-Ange"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Paradis Perdu Psaume II");
        $serie->addScenariste($this->getReference("PERSONNE-Ange"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Elixirs");
        $serie->addDessinateur($this->getReference("PERSONNE-Varanda [Alberto]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-poussières de l'infini [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Plongeon [Isabelle]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Seigneurs d'Agartha [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Plongeon [Isabelle]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-poussières de l'infini [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Zerriouh"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-brûmes d'Asceltis [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Istin [Jean-Luc]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Merlin");
        $serie->addScenariste($this->getReference("PERSONNE-Istin [Jean-Luc]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Merlin - La quête de l'épée");
        $serie->addScenariste($this->getReference("PERSONNE-Istin [Jean-Luc]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-contes du Korrigan [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Istin [Jean-Luc]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Tuniques Bleues [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Lambert [Eric]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Merlin");
        $serie->addDessinateur($this->getReference("PERSONNE-Lambert [Eric]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Terra incognita");
        $serie->addScenariste($this->getReference("PERSONNE-Perrotin [Serge]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Marshall");
        $serie->addDessinateur($this->getReference("PERSONNE-Filippi [Denis-Pierre]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Morgana");
        $serie->addScenariste($this->getReference("PERSONNE-Alberti [Mario]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Morgana");
        $serie->addDessinateur($this->getReference("PERSONNE-Alberti [Mario]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Morgana");
        $serie->addScenariste($this->getReference("PERSONNE-Enoch [Luca]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sanctuaire");
        $serie->addScenariste($this->getReference("PERSONNE-Dorison [Xavier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-troisième testament [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Dorison [Xavier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sanctuaire");
        $serie->addDessinateur($this->getReference("PERSONNE-Bec [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sur les traces de Dracula");
        $serie->addScenariste($this->getReference("PERSONNE-Huppen [Yves]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Halloween blues");
        $serie->addDessinateur($this->getReference("PERSONNE-Kas"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Halloween blues");
        $serie->addScenariste($this->getReference("PERSONNE-Mythic"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-feux d'Askell [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Mourier [Jean-Louis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-feux d'Askell [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Mourier [Jean-Louis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Trolls de Troy");
        $serie->addDessinateur($this->getReference("PERSONNE-Mourier [Jean-Louis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Slhoka");
        $serie->addScenariste($this->getReference("PERSONNE-Godderidge"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-naufragés d'Ythaq [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Floch [Adrien]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Slhoka");
        $serie->addDessinateur($this->getReference("PERSONNE-Floch [Adrien]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Krashmonsters [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Floch [Adrien]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Monster Allergy");
        $serie->addDessinateur($this->getReference("PERSONNE-Barbucci [Alessandro]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sky Doll");
        $serie->addScenariste($this->getReference("PERSONNE-Barbucci [Alessandro]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sky Doll");
        $serie->addDessinateur($this->getReference("PERSONNE-Barbucci [Alessandro]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sky Doll");
        $serie->addScenariste($this->getReference("PERSONNE-Canepa [Barbara]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sky Doll");
        $serie->addColoriste($this->getReference("PERSONNE-Canepa [Barbara]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Spirou et Fantasio");
        $serie->addDessinateur($this->getReference("PERSONNE-Munuera [José Luis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Private Ghost");
        $serie->addScenariste($this->getReference("PERSONNE-Crisse [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Perdita Queen");
        $serie->addScenariste($this->getReference("PERSONNE-Crisse [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Perdita Queen");
        $serie->addDessinateur($this->getReference("PERSONNE-Crisse [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Atalante");
        $serie->addScenariste($this->getReference("PERSONNE-Crisse [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Atalante");
        $serie->addDessinateur($this->getReference("PERSONNE-Crisse [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Epée de cristal [L']");
        $serie->addDessinateur($this->getReference("PERSONNE-Crisse [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Kookaburra K");
        $serie->addScenariste($this->getReference("PERSONNE-Crisse [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Kookaburra");
        $serie->addScenariste($this->getReference("PERSONNE-Crisse [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Luuna");
        $serie->addScenariste($this->getReference("PERSONNE-Crisse [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Griffin Dark");
        $serie->addDessinateur($this->getReference("PERSONNE-Crisse [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Kookaburra Universe");
        $serie->addScenariste($this->getReference("PERSONNE-Crisse [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Private Ghost");
        $serie->addDessinateur($this->getReference("PERSONNE-Carrère"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Léo Loden");
        $serie->addDessinateur($this->getReference("PERSONNE-Carrère"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Nocturnes Rouges");
        $serie->addScenariste($this->getReference("PERSONNE-Nhieu [Emmanuel]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Moréa");
        $serie->addDessinateur($this->getReference("PERSONNE-Labrosse [Thierry]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Marlysa");
        $serie->addScenariste($this->getReference("PERSONNE-Gaudin [Jean-Charles]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Marlysa");
        $serie->addDessinateur($this->getReference("PERSONNE-Danard [Jean-Pierre]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Luuna");
        $serie->addDessinateur($this->getReference("PERSONNE-Kéramidas [Nicolas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Seigneurs d'Agartha [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Briones [Philippe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-gardiens du Maser [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Frezzato [Massimiliano]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-troisième testament [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Alice [Alex]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-troisième testament [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Alice [Alex]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-troisième testament [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-Alice [Alex]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Titeuf");
        $serie->addScenariste($this->getReference("PERSONNE-Zep"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Titeuf");
        $serie->addDessinateur($this->getReference("PERSONNE-Zep"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Titeuf");
        $serie->addColoriste($this->getReference("PERSONNE-Zep"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Double masque");
        $serie->addDessinateur($this->getReference("PERSONNE-Jamar [Martin]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Double masque");
        $serie->addColoriste($this->getReference("PERSONNE-Jamar [Martin]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lanfeust de Troy");
        $serie->addDessinateur($this->getReference("PERSONNE-Tarquin [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lanfeust des étoiles");
        $serie->addDessinateur($this->getReference("PERSONNE-Tarquin [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Gnomes de Troy");
        $serie->addDessinateur($this->getReference("PERSONNE-Tarquin [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Krashmonsters [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Tarquin [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lanfeust Odyssey");
        $serie->addDessinateur($this->getReference("PERSONNE-Tarquin [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Kookaburra K");
        $serie->addScenariste($this->getReference("PERSONNE-Mitric [Nicolas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Tessa agent intergalactique");
        $serie->addScenariste($this->getReference("PERSONNE-Mitric [Nicolas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Kookaburra");
        $serie->addScenariste($this->getReference("PERSONNE-Mitric [Nicolas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Kookaburra");
        $serie->addDessinateur($this->getReference("PERSONNE-Mitric [Nicolas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-arche [L']");
        $serie->addScenariste($this->getReference("PERSONNE-Félix [Jérôme]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-arche [L']");
        $serie->addDessinateur($this->getReference("PERSONNE-Mallié [Vincent]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-aquanautes [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Mallié [Vincent]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-chant d'excalibur [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Hübsch [Eric]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-collège invisible [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Donsimoni"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-forêts d'Opale [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Pellet [Philippe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Monster Allergy");
        $serie->addScenariste($this->getReference("PERSONNE-Centomo [Katja]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Terra incognita");
        $serie->addDessinateur($this->getReference("PERSONNE-Chami"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Terra incognita");
        $serie->addColoriste($this->getReference("PERSONNE-Verney [Jean]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Atalante");
        $serie->addColoriste($this->getReference("PERSONNE-Besson [Frédéric]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-cicatrice du souvenir [La]");
        $serie->addColoriste($this->getReference("PERSONNE-Besson [Frédéric]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lanfeust Odyssey");
        $serie->addColoriste($this->getReference("PERSONNE-Besson [Frédéric]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Golden Cup");
        $serie->addColoriste($this->getReference("PERSONNE-Schelle [Pierre]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Asphodèle");
        $serie->addColoriste($this->getReference("PERSONNE-Schelle [Pierre]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Golden Cup");
        $serie->addDessinateur($this->getReference("PERSONNE-Henriet [Alain]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Merlin");
        $serie->addColoriste($this->getReference("PERSONNE-Stambecco [Bruno]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-quête du Graal [La]");
        $serie->addColoriste($this->getReference("PERSONNE-Stambecco [Bruno]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-quête des réponses [La]");
        $serie->addColoriste($this->getReference("PERSONNE-Color Twins"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-HK - 1er cycle");
        $serie->addColoriste($this->getReference("PERSONNE-Color Twins"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sir Pyle S. Culape");
        $serie->addDessinateur($this->getReference("PERSONNE-Ruben"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sir Pyle S. Culape");
        $serie->addColoriste($this->getReference("PERSONNE-Lerolle"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Spirou et Fantasio");
        $serie->addColoriste($this->getReference("PERSONNE-Lerolle"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Tuniques Bleues [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Leonardo"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Pierre Tombal");
        $serie->addColoriste($this->getReference("PERSONNE-Leonardo"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Léo Loden");
        $serie->addColoriste($this->getReference("PERSONNE-Cerise"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Slhoka");
        $serie->addColoriste($this->getReference("PERSONNE-Lyse"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Gnomes de Troy");
        $serie->addColoriste($this->getReference("PERSONNE-Lyse"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Krashmonsters [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Lyse"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Krashmonsters [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Dutto [Olivier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Krashmonsters [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Bianco [Guillaume]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Krashmonsters [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Bianco [Guillaume]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Negima!");
        $serie->addScenariste($this->getReference("PERSONNE-Akamatsu [Ken]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Negima!");
        $serie->addDessinateur($this->getReference("PERSONNE-Akamatsu [Ken]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Ai non-stop !");
        $serie->addScenariste($this->getReference("PERSONNE-Akamatsu [Ken]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Ai non-stop !");
        $serie->addDessinateur($this->getReference("PERSONNE-Akamatsu [Ken]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Eternels [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Meynet [Dominique]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-mirroir des Alices [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Kara"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-mirroir des Alices [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Kara"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-mirroir des Alices [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-Kara"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Gabrielle");
        $serie->addScenariste($this->getReference("PERSONNE-Kara"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Gabrielle");
        $serie->addDessinateur($this->getReference("PERSONNE-Kara"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Gabrielle");
        $serie->addColoriste($this->getReference("PERSONNE-Kara"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-chant d'excalibur [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-Lebreton [Nolwenn]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Elixirs");
        $serie->addColoriste($this->getReference("PERSONNE-Lebreton [Nolwenn]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Private Ghost");
        $serie->addColoriste($this->getReference("PERSONNE-Rieu [Delphine]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-arche [L']");
        $serie->addColoriste($this->getReference("PERSONNE-Rieu [Delphine]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-aquanautes [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Rieu [Delphine]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-petit Spirou [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-Becker [Stephane de]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Trolls de Troy");
        $serie->addColoriste($this->getReference("PERSONNE-Guth [Claude]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-naufragés d'Ythaq [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Guth [Claude]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lanfeust des étoiles");
        $serie->addColoriste($this->getReference("PERSONNE-Guth [Claude]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Où le regard ne porte pas...");
        $serie->addColoriste($this->getReference("PERSONNE-Chagnaud [Jean-Jacques]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Perdita Queen");
        $serie->addColoriste($this->getReference("PERSONNE-Anyk"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Belladone");
        $serie->addColoriste($this->getReference("PERSONNE-Noël [Patrick]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Babel");
        $serie->addColoriste($this->getReference("PERSONNE-Noël [Patrick]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-cicatrice du souvenir [La]");
        $serie->addDessinateur($this->getReference("PERSONNE-Paty [Christian]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Nausicaä");
        $serie->addScenariste($this->getReference("PERSONNE-Miyasaki [Hayao]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Nausicaä");
        $serie->addDessinateur($this->getReference("PERSONNE-Miyasaki [Hayao]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-maîtres cartographes [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Glaudel [Paul]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-retour à la terre [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-Findakly [Brigitte]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Babel");
        $serie->addDessinateur($this->getReference("PERSONNE-Janolle [Alain]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Nemesis");
        $serie->addColoriste($this->getReference("PERSONNE-Paitreau [Stéphane]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Seigneurs d'Agartha [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Paitreau [Stéphane]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-forêts d'Opale [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Goussale"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Moréa");
        $serie->addColoriste($this->getReference("PERSONNE-Arpin [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lillian Browne");
        $serie->addColoriste($this->getReference("PERSONNE-Césano [Angélique]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Quête de l'Oiseau du temps - Avant la Quête [La]");
        $serie->addDessinateur($this->getReference("PERSONNE-Aouamri"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Asphodèle");
        $serie->addScenariste($this->getReference("PERSONNE-Guérineau [Richard]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-chant des Stryges [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Guérineau [Richard]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Cixi de Troy");
        $serie->addDessinateur($this->getReference("PERSONNE-Vatine [Olivier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Cixi de Troy");
        $serie->addColoriste($this->getReference("PERSONNE-Vatine [Olivier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Salem la Noire");
        $serie->addScenariste($this->getReference("PERSONNE-Cordurié [Sylvain]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Salem la Noire");
        $serie->addDessinateur($this->getReference("PERSONNE-Créty [Stéphane]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Salem la Noire");
        $serie->addColoriste($this->getReference("PERSONNE-Cordurié [Sandrine]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Merlin - La quête de l'épée");
        $serie->addColoriste($this->getReference("PERSONNE-Cordurié [Sandrine]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Arcane majeur");
        $serie->addScenariste($this->getReference("PERSONNE-Pécau [Jean-Pierre]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Arcanes");
        $serie->addScenariste($this->getReference("PERSONNE-Pécau [Jean-Pierre]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Arcane majeur");
        $serie->addDessinateur($this->getReference("PERSONNE-Damien"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Carmen Mc Callum");
        $serie->addColoriste($this->getReference("PERSONNE-Rabarot [Isabelle]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Baker Street");
        $serie->addScenariste($this->getReference("PERSONNE-Veys [Pierre]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Baker Street");
        $serie->addDessinateur($this->getReference("PERSONNE-Barral [Nicolas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Baker Street");
        $serie->addColoriste($this->getReference("PERSONNE-Barral [Nicolas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Mayam");
        $serie->addColoriste($this->getReference("PERSONNE-Smulkowski [Scarlett]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-femmes en blanc [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Cauvin [Raoul]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Tuniques Bleues [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Cauvin [Raoul]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Pierre Tombal");
        $serie->addScenariste($this->getReference("PERSONNE-Cauvin [Raoul]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Travis");
        $serie->addScenariste($this->getReference("PERSONNE-Duval [Fred]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Carmen Mc Callum");
        $serie->addScenariste($this->getReference("PERSONNE-Duval [Fred]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Hauteville House");
        $serie->addScenariste($this->getReference("PERSONNE-Duval [Fred]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Carmen Mc Callum");
        $serie->addDessinateur($this->getReference("PERSONNE-Gess"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-poussières de l'infini [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Studio 2HB"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-aquanautes [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Parnotte [J.]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Maxime Murène");
        $serie->addScenariste($this->getReference("PERSONNE-Jarry [Nicolas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-brûmes d'Asceltis [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Jarry [Nicolas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-brûmes d'Asceltis [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Brants [Elsa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-quête du Graal [La]");
        $serie->addScenariste($this->getReference("PERSONNE-Debois [François]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Blacksad");
        $serie->addScenariste($this->getReference("PERSONNE-Díaz Canales [Juan]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Blacksad");
        $serie->addDessinateur($this->getReference("PERSONNE-Guarnido [Juanjo]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Blacksad");
        $serie->addColoriste($this->getReference("PERSONNE-Guarnido [Juanjo]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Reality show");
        $serie->addDessinateur($this->getReference("PERSONNE-Porcel [Francis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Reality show");
        $serie->addColoriste($this->getReference("PERSONNE-Hubert"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Mayam");
        $serie->addDessinateur($this->getReference("PERSONNE-Koller [Daniel]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Ghost in the Shell");
        $serie->addScenariste($this->getReference("PERSONNE-Masamune [Shirow]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Ghost in the Shell");
        $serie->addDessinateur($this->getReference("PERSONNE-Masamune [Shirow]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Ghost in the Shell");
        $serie->addColoriste($this->getReference("PERSONNE-Masamune [Shirow]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-dernier Livre de la Jungle [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Reculé [Henri]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-immortels [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Reculé [Henri]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Incantations");
        $serie->addScenariste($this->getReference("PERSONNE-Derrien [Jean-Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Incantations");
        $serie->addDessinateur($this->getReference("PERSONNE-Van Liemt [Simon]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-TransGénèse - 2029 2034, Fides");
        $serie->addScenariste($this->getReference("PERSONNE-Ploy [Anne]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-TransGénèse - 2029 2034, Fides");
        $serie->addDessinateur($this->getReference("PERSONNE-Pagot [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-femmes en blanc [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Bercovici"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Moréa");
        $serie->addScenariste($this->getReference("PERSONNE-Latil [Dominique]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-On achève bien les cons!");
        $serie->addScenariste($this->getReference("PERSONNE-Chanoinat [Philippe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lola Bogota");
        $serie->addScenariste($this->getReference("PERSONNE-Chanoinat [Philippe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Thomas Silane");
        $serie->addScenariste($this->getReference("PERSONNE-Chanoinat [Philippe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-On achève bien les cons!");
        $serie->addScenariste($this->getReference("PERSONNE-Lautner [Georges]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-On achève bien les cons!");
        $serie->addColoriste($this->getReference("PERSONNE-Thomas [Nadine]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sanctuaire");
        $serie->addColoriste($this->getReference("PERSONNE-Reyes [Homer]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Hauteville House");
        $serie->addDessinateur($this->getReference("PERSONNE-Gioux [Thierry]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Hauteville House");
        $serie->addColoriste($this->getReference("PERSONNE-Beau [Carole]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-TransGénèse - 2029 2034, Fides");
        $serie->addColoriste($this->getReference("PERSONNE-Araldi [Christophe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Thomas Silane");
        $serie->addScenariste($this->getReference("PERSONNE-Buendia [Patrice]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-dernier Livre de la Jungle [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-De Moor [Johan]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-collège invisible [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-Bouet"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Akameshi");
        $serie->addScenariste($this->getReference("PERSONNE-Gualdoni [Giovanni]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Akameshi");
        $serie->addDessinateur($this->getReference("PERSONNE-Turconi [Stefano]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Akameshi");
        $serie->addColoriste($this->getReference("PERSONNE-Turconi [Stefano]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-insurgés d'Edaleth [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Tackian [Nicolas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-insurgés d'Edaleth [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Miquel [Stéphane]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-insurgés d'Edaleth [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Brion [Alain]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-insurgés d'Edaleth [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Brion [Alain]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-quête du Graal [La]");
        $serie->addDessinateur($this->getReference("PERSONNE-Bileau [Stéphane]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-HK - 1er cycle");
        $serie->addDessinateur($this->getReference("PERSONNE-Hérault [Kevin]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-HK - 2ème cycle");
        $serie->addDessinateur($this->getReference("PERSONNE-Hérault [Kevin]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-HK - 2ème cycle");
        $serie->addColoriste($this->getReference("PERSONNE-Hérault [Kevin]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Tsukasa Hojo recueil");
        $serie->addScenariste($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Tsukasa Hojo recueil");
        $serie->addDessinateur($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Angel Heart");
        $serie->addScenariste($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Angel Heart");
        $serie->addDessinateur($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-City Hunter");
        $serie->addScenariste($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sous un rayon de soleil");
        $serie->addScenariste($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sous un rayon de soleil");
        $serie->addDessinateur($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Family Compo");
        $serie->addScenariste($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Family Compo");
        $serie->addDessinateur($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Rash");
        $serie->addScenariste($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Rash");
        $serie->addDessinateur($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-City Hunter");
        $serie->addDessinateur($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Cat's eye");
        $serie->addScenariste($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Cat's eye");
        $serie->addDessinateur($this->getReference("PERSONNE-Hojo [Tsukasa]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Epée de cristal [L']");
        $serie->addScenariste($this->getReference("PERSONNE-Goupil [Jacky]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-chroniques de Centrum [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Andrevon"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-chroniques de Centrum [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Khaled [Afif]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-chroniques de Centrum [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Khaled [Afif]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Epée de cristal [L']");
        $serie->addScenariste($this->getReference("PERSONNE-Kainzow"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Epée de cristal [L']");
        $serie->addDessinateur($this->getReference("PERSONNE-Boube [Christian]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Epée de cristal [L']");
        $serie->addColoriste($this->getReference("PERSONNE-Lamirand [Sébastien]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Conquérants de Troy [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Lamirand [Sébastien]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Tessa agent intergalactique");
        $serie->addColoriste($this->getReference("PERSONNE-Lamirand [Sébastien]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Kookaburra");
        $serie->addColoriste($this->getReference("PERSONNE-Lamirand [Sébastien]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Phenomenum");
        $serie->addColoriste($this->getReference("PERSONNE-Champion [Claire]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Phenomenum");
        $serie->addDessinateur($this->getReference("PERSONNE-Vedrines"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Phenomenum");
        $serie->addScenariste($this->getReference("PERSONNE-Kaminka"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Où le regard ne porte pas...");
        $serie->addScenariste($this->getReference("PERSONNE-Pont [Olivier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Où le regard ne porte pas...");
        $serie->addDessinateur($this->getReference("PERSONNE-Pont [Olivier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Où le regard ne porte pas...");
        $serie->addScenariste($this->getReference("PERSONNE-Abolin [Georges]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Paradis perdu");
        $serie->addDessinateur($this->getReference("PERSONNE-Xavier"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Paradis perdu");
        $serie->addColoriste($this->getReference("PERSONNE-Alexe"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Monster Allergy");
        $serie->addColoriste($this->getReference("PERSONNE-Giumento [Cecilia]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Cross fire");
        $serie->addScenariste($this->getReference("PERSONNE-Sala [Jean-Luc]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Cross fire");
        $serie->addDessinateur($this->getReference("PERSONNE-Chan [Pierre-Mony]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Cross fire");
        $serie->addColoriste($this->getReference("PERSONNE-Chan [Pierre-Mony]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Tessa agent intergalactique");
        $serie->addDessinateur($this->getReference("PERSONNE-Louis [Stéphane]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-XIII");
        $serie->addDessinateur($this->getReference("PERSONNE-Vance [W.]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Achille Talon");
        $serie->addScenariste($this->getReference("PERSONNE-Greg"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Achille Talon");
        $serie->addDessinateur($this->getReference("PERSONNE-Greg"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Stellaire");
        $serie->addScenariste($this->getReference("PERSONNE-Corgiat [Sylviane]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Stellaire");
        $serie->addScenariste($this->getReference("PERSONNE-Galliano [Patrick]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Stellaire");
        $serie->addDessinateur($this->getReference("PERSONNE-Ponticelli [Alberto]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Stellaire");
        $serie->addDessinateur($this->getReference("PERSONNE-Pécout [Christelle]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Iznogoud");
        $serie->addDessinateur($this->getReference("PERSONNE-Tabary [Jean]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Pixie");
        $serie->addDessinateur($this->getReference("PERSONNE-Aurore"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Pixie");
        $serie->addColoriste($this->getReference("PERSONNE-Aurore"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Pixie");
        $serie->addScenariste($this->getReference("PERSONNE-Mariolle [Mathieu]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-GetBackers");
        $serie->addDessinateur($this->getReference("PERSONNE-Ayamine [Rando]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-GetBackers");
        $serie->addScenariste($this->getReference("PERSONNE-Aoki [Yûya]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Belladone");
        $serie->addDessinateur($this->getReference("PERSONNE-Alary [Pierre]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-aventures de Lucky Luke [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Gerra [Laurent]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-aventures de Lucky Luke [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Achde"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Conquérants de Troy [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Tota"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Patlabor");
        $serie->addScenariste($this->getReference("PERSONNE-Masami [Yuuki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Patlabor");
        $serie->addDessinateur($this->getReference("PERSONNE-Masami [Yuuki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-D.N. Angel");
        $serie->addScenariste($this->getReference("PERSONNE-Sugizaki [Yukiru]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-D.N. Angel");
        $serie->addDessinateur($this->getReference("PERSONNE-Sugizaki [Yukiru]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Anges");
        $serie->addDessinateur($this->getReference("PERSONNE-Boiscommun [O.G.]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-cité de l'Arche [La]");
        $serie->addScenariste($this->getReference("PERSONNE-Boiscommun [O.G.]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-cité de l'Arche [La]");
        $serie->addDessinateur($this->getReference("PERSONNE-Boiscommun [O.G.]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-cité de l'Arche [La]");
        $serie->addColoriste($this->getReference("PERSONNE-Boiscommun [O.G.]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Anges");
        $serie->addScenariste($this->getReference("PERSONNE-Dieter"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Anachron");
        $serie->addDessinateur($this->getReference("PERSONNE-Jurion [Joël]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Anachron");
        $serie->addScenariste($this->getReference("PERSONNE-Cailleteau [Thierry]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Anachron");
        $serie->addColoriste($this->getReference("PERSONNE-St Jore [Sandrine]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Maxime Murène");
        $serie->addDessinateur($this->getReference("PERSONNE-David Nouhaud"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Maxime Murène");
        $serie->addColoriste($this->getReference("PERSONNE-David Nouhaud"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Nemesis");
        $serie->addDessinateur($this->getReference("PERSONNE-Cifuentes [Vicente]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Merlin - La quête de l'épée");
        $serie->addDessinateur($this->getReference("PERSONNE-Demare [Nicolas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-dernier Troyen [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Démarez [Thierry]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-dernier Troyen [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-Démarez [Thierry]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-flEAU dES DiEUX [lE]");
        $serie->addDessinateur($this->getReference("PERSONNE-Gajic [Aleska]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-flEAU dES DiEUX [lE]");
        $serie->addColoriste($this->getReference("PERSONNE-Gajic [Aleska]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Marlysa");
        $serie->addColoriste($this->getReference("PERSONNE-Guillo [Yoann]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Enfer & Paradis");
        $serie->addScenariste($this->getReference("PERSONNE-Oh! Great (Ito Ohgure)"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Enfer & Paradis");
        $serie->addDessinateur($this->getReference("PERSONNE-Oh! Great (Ito Ohgure)"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Phenomenum");
        $serie->addColoriste($this->getReference("PERSONNE-Vidal [Amélie]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Halloween blues");
        $serie->addColoriste($this->getReference("PERSONNE-Graza"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lola Bogota");
        $serie->addDessinateur($this->getReference("PERSONNE-Reynès [Mathieu]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lola Bogota");
        $serie->addScenariste($this->getReference("PERSONNE-Brremaud [Frédéric]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lola Bogota");
        $serie->addColoriste($this->getReference("PERSONNE-Romanet [Caroline]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Marshall");
        $serie->addScenariste($this->getReference("PERSONNE-Ruiz Velasco [Francisco]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Pandora box");
        $serie->addScenariste($this->getReference("PERSONNE-Alcante"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Pandora box");
        $serie->addColoriste($this->getReference("PERSONNE-Usagi"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Kaamelott");
        $serie->addDessinateur($this->getReference("PERSONNE-Dupré [Steven]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Zone mortelle");
        $serie->addScenariste($this->getReference("PERSONNE-Mosdi [Thomas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Zone mortelle");
        $serie->addDessinateur($this->getReference("PERSONNE-Vogel [David]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Zone mortelle");
        $serie->addColoriste($this->getReference("PERSONNE-Gonzalbo [Axel]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Quête de l'Oiseau du temps - Avant la Quête [La]");
        $serie->addDessinateur($this->getReference("PERSONNE-Maillé [Vincent]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Kookaburra K");
        $serie->addDessinateur($this->getReference("PERSONNE-Ramos [Umberto]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Tigresse Blanche");
        $serie->addColoriste($this->getReference("PERSONNE-Loïs [Julien]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Kookaburra K");
        $serie->addColoriste($this->getReference("PERSONNE-Olea [Léonardo]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Conjuration d'opale [La]");
        $serie->addDessinateur($this->getReference("PERSONNE-Grun"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Conjuration d'opale [La]");
        $serie->addColoriste($this->getReference("PERSONNE-Grun"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-rose éclarlate [La]");
        $serie->addScenariste($this->getReference("PERSONNE-Lyfoung [Patricia]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-rose éclarlate [La]");
        $serie->addDessinateur($this->getReference("PERSONNE-Lyfoung [Patricia]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-rose éclarlate [La]");
        $serie->addColoriste($this->getReference("PERSONNE-Lyfoung [Patricia]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-rose éclarlate [La]");
        $serie->addColoriste($this->getReference("PERSONNE-Ogaki [Philippe]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Tigresse Blanche");
        $serie->addScenariste($this->getReference("PERSONNE-Conrad [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Tigresse Blanche");
        $serie->addDessinateur($this->getReference("PERSONNE-Conrad [Didier]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Paradis Perdu Psaume II");
        $serie->addColoriste($this->getReference("PERSONNE-Crazytoons"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Fruits basket");
        $serie->addScenariste($this->getReference("PERSONNE-Takaya [Natsuki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Fruits basket");
        $serie->addDessinateur($this->getReference("PERSONNE-Takaya [Natsuki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Black cat");
        $serie->addScenariste($this->getReference("PERSONNE-Kentaro [Y.]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Black cat");
        $serie->addDessinateur($this->getReference("PERSONNE-Kentaro [Y.]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Bleach");
        $serie->addScenariste($this->getReference("PERSONNE-Kubo [Tite]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Bleach");
        $serie->addDessinateur($this->getReference("PERSONNE-Kubo [Tite]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Aqua Knight");
        $serie->addScenariste($this->getReference("PERSONNE-Kishiro [Yukito]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Aqua Knight");
        $serie->addDessinateur($this->getReference("PERSONNE-Kishiro [Yukito]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Gunnm Last Order");
        $serie->addScenariste($this->getReference("PERSONNE-Kishiro [Yukito]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Gunnm Last Order");
        $serie->addDessinateur($this->getReference("PERSONNE-Kishiro [Yukito]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Gunnm");
        $serie->addScenariste($this->getReference("PERSONNE-Kishiro [Yukito]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Gunnm");
        $serie->addDessinateur($this->getReference("PERSONNE-Kishiro [Yukito]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-21st century boys");
        $serie->addScenariste($this->getReference("PERSONNE-Urasawa [Naoki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-21st century boys");
        $serie->addDessinateur($this->getReference("PERSONNE-Urasawa [Naoki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-20th century boys");
        $serie->addScenariste($this->getReference("PERSONNE-Urasawa [Naoki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-20th century boys");
        $serie->addDessinateur($this->getReference("PERSONNE-Urasawa [Naoki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Monster");
        $serie->addScenariste($this->getReference("PERSONNE-Urasawa [Naoki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Monster");
        $serie->addDessinateur($this->getReference("PERSONNE-Urasawa [Naoki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Pluto");
        $serie->addScenariste($this->getReference("PERSONNE-Urasawa [Naoki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Pluto");
        $serie->addDessinateur($this->getReference("PERSONNE-Urasawa [Naoki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Happy");
        $serie->addScenariste($this->getReference("PERSONNE-Urasawa [Naoki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Happy");
        $serie->addDessinateur($this->getReference("PERSONNE-Urasawa [Naoki]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-loi des 12 tables [La]");
        $serie->addColoriste($this->getReference("PERSONNE-Pérubros"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Conjuration d'opale [La]");
        $serie->addScenariste($this->getReference("PERSONNE-Hamm [Nicolas]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Magasin général");
        $serie->addScenariste($this->getReference("PERSONNE-Tripp [Jean-Louis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Magasin général");
        $serie->addDessinateur($this->getReference("PERSONNE-Tripp [Jean-Louis]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Magasin général");
        $serie->addColoriste($this->getReference("PERSONNE-Lapierre [François]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-combat ordinaire [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Larcenet [Manu]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-combat ordinaire [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Larcenet [Manu]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-retour à la terre [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Larcenet [Manu]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-combat ordinaire [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-Larcenet [Patrice]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Chrno Crusade");
        $serie->addScenariste($this->getReference("PERSONNE-Moriyama [Daisuke]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Chrno Crusade");
        $serie->addDessinateur($this->getReference("PERSONNE-Moriyama [Daisuke]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Nocturnes Rouges");
        $serie->addColoriste($this->getReference("PERSONNE-Torta [Florence]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-retour à la terre [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Ferri [Jean-Yves]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sanctuary");
        $serie->addDessinateur($this->getReference("PERSONNE-Ikegami [Ryoichi]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sanctuary");
        $serie->addScenariste($this->getReference("PERSONNE-Fumimura [Sho]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Heads");
        $serie->addScenariste($this->getReference("PERSONNE-Higasino [Keigo]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Heads");
        $serie->addDessinateur($this->getReference("PERSONNE-Mase [Motorou]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lillian Browne");
        $serie->addScenariste($this->getReference("PERSONNE-Vinci [Vanna]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Lillian Browne");
        $serie->addDessinateur($this->getReference("PERSONNE-Vinci [Vanna]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Fullmetal Alchemist");
        $serie->addScenariste($this->getReference("PERSONNE-Arakawa [Hiromu]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Fullmetal Alchemist");
        $serie->addDessinateur($this->getReference("PERSONNE-Arakawa [Hiromu]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Léo Loden");
        $serie->addScenariste($this->getReference("PERSONNE-Nicoloff [Loïc]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Corto Maltese");
        $serie->addScenariste($this->getReference("PERSONNE-Pratt [Hugo]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Corto Maltese");
        $serie->addDessinateur($this->getReference("PERSONNE-Pratt [Hugo]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Jack Palmer");
        $serie->addScenariste($this->getReference("PERSONNE-Pétillon"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Jack Palmer");
        $serie->addDessinateur($this->getReference("PERSONNE-Pétillon"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Jack Palmer");
        $serie->addColoriste($this->getReference("PERSONNE-Pétillon"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Pierre Tombal");
        $serie->addDessinateur($this->getReference("PERSONNE-Hardy"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-dernier Troyen [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Mangin [Valérie]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Guerre des Dieux [La]");
        $serie->addScenariste($this->getReference("PERSONNE-Mangin [Valérie]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-flEAU dES DiEUX [lE]");
        $serie->addScenariste($this->getReference("PERSONNE-Mangin [Valérie]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Luuna");
        $serie->addColoriste($this->getReference("PERSONNE-Vincent [Cyril]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Nocturnes Rouges");
        $serie->addDessinateur($this->getReference("PERSONNE-Looky"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Maliki");
        $serie->addScenariste($this->getReference("PERSONNE-Maliki"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Maliki");
        $serie->addDessinateur($this->getReference("PERSONNE-Maliki"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Maliki");
        $serie->addColoriste($this->getReference("PERSONNE-Maliki"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Tigresse Blanche");
        $serie->addScenariste($this->getReference("PERSONNE-Wilbur"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-donjon de Naheulbeuk [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Lang [John]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-arcanes de Naheulbeuk [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Lang [John]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-donjon de Naheulbeuk [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Poinsot [Marion]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-arcanes de Naheulbeuk [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Poinsot [Marion]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-donjon de Naheulbeuk [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-Sabater [Sylvie]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-arcanes de Naheulbeuk [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Sabater [Sylvie]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Kookaburra K");
        $serie->addScenariste($this->getReference("PERSONNE-Hicks"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-chant des Stryges [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-Hedon"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Baker Street");
        $serie->addColoriste($this->getReference("PERSONNE-Scarlett"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Arcanes");
        $serie->addDessinateur($this->getReference("PERSONNE-Nenadov [Dejan]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Arcanes");
        $serie->addColoriste($this->getReference("PERSONNE-Fernandez [Jean-Paul]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Kaamelott");
        $serie->addScenariste($this->getReference("PERSONNE-Astier [Alexandre]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Kaamelott");
        $serie->addColoriste($this->getReference("PERSONNE-Bekaert [Benoît]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Arcane majeur");
        $serie->addColoriste($this->getReference("PERSONNE-Tenderini [Emanuele]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-voisins du 109 [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Coyote"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-voisins du 109 [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Coyote"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Litteul Kévin");
        $serie->addScenariste($this->getReference("PERSONNE-Coyote"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Litteul Kévin");
        $serie->addDessinateur($this->getReference("PERSONNE-Coyote"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-voisins du 109 [Les]");
        $serie->addColoriste($this->getReference("PERSONNE-Coyote"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-voisins du 109 [Les]");
        $serie->addScenariste($this->getReference("PERSONNE-Bombardier [Nini]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Paradis Perdu Psaume II");
        $serie->addDessinateur($this->getReference("PERSONNE-Cossu"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Thomas Silane");
        $serie->addDessinateur($this->getReference("PERSONNE-Zaghi [Roberto]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Thomas Silane");
        $serie->addColoriste($this->getReference("PERSONNE-Saint Blancat [Cyril]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Joe Bar Team");
        $serie->addScenariste($this->getReference("PERSONNE-Bar2"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Joe Bar Team");
        $serie->addDessinateur($this->getReference("PERSONNE-Bar2"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Joe Bar Team");
        $serie->addColoriste($this->getReference("PERSONNE-Bar2"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Péchés mignons");
        $serie->addScenariste($this->getReference("PERSONNE-de Pins [Arthur]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Péchés mignons");
        $serie->addDessinateur($this->getReference("PERSONNE-de Pins [Arthur]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Péchés mignons");
        $serie->addColoriste($this->getReference("PERSONNE-de Pins [Arthur]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Luuna");
        $serie->addColoriste($this->getReference("PERSONNE-Bassini [Matteo]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-déclic [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Manara [Milo]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-déclic [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Manara [Milo]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Parfum de l'invisible [Le]");
        $serie->addScenariste($this->getReference("PERSONNE-Manara [Milo]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Parfum de l'invisible [Le]");
        $serie->addDessinateur($this->getReference("PERSONNE-Manara [Milo]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Parfum de l'invisible [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-Manara [Milo]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-déclic [Le]");
        $serie->addColoriste($this->getReference("PERSONNE-Studio 9"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Guerre des Dieux [La]");
        $serie->addDessinateur($this->getReference("PERSONNE-Yazghi [Dean]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Guerre des Dieux [La]");
        $serie->addColoriste($this->getReference("PERSONNE-Kathelyn [Dina]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sorcières");
        $serie->addScenariste($this->getReference("PERSONNE-Alexine"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sorcières");
        $serie->addDessinateur($this->getReference("PERSONNE-You"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Sorcières");
        $serie->addColoriste($this->getReference("PERSONNE-de Cock [Elvire]"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-Griffin Dark");
        $serie->addScenariste($this->getReference("PERSONNE-Stanley"));
        $manager->persist($serie);
        $serie = $this->getReference("SERIE-gardiens du Maser [Les]");
        $serie->addDessinateur($this->getReference("PERSONNE-Ruotolo [Fabio]"));
        $manager->persist($serie);

        $manager->flush();
    }

}

?>
