unit BDTK.Web.Updates.v1_0_0_0;

interface

uses
  System.Classes, BDTK.Updates;

implementation

procedure MAJ1_0_0_0(Script: TStrings);
begin
  Script.Clear;
  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/options (');
  Script.Add('  cle varchar(20) NOT NULL,');
  Script.Add('  valeur varchar(100) default NULL,');
  Script.Add('  PRIMARY KEY  (cle)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/albums (');
  Script.Add('  id_album char(38) NOT NULL,');
  Script.Add('  titrealbum varchar(150) default NULL,');
  Script.Add('  moisparution smallint(6) default NULL,');
  Script.Add('  anneeparution smallint(6) default NULL,');
  Script.Add('  id_serie char(38) default NULL,');
  Script.Add('  tome smallint(6) default NULL,');
  Script.Add('  tomedebut smallint(6) default NULL,');
  Script.Add('  tomefin smallint(6) default NULL,');
  Script.Add('  horsserie smallint(6) default 0,');
  Script.Add('  integrale smallint(6) default 0,');
  Script.Add('  sujetalbum longtext,');
  Script.Add('  remarquesalbum longtext,');
  Script.Add('  achat smallint(6) default 0,');
  Script.Add('  nbeditions int(11) default 0,');
  Script.Add('  complet tinyint(4) default NULL,');
  Script.Add('  uppertitrealbum varchar(150) default NULL,');
  Script.Add('  uppersujetalbum longtext,');
  Script.Add('  upperremarquesalbum longtext,');
  Script.Add('  soundextitrealbum varchar(30) default NULL,');
  Script.Add('  initialetitrealbum char(1) default NULL,');
  Script.Add('  dc_albums timestamp,');
  Script.Add('  dm_albums timestamp,');
  Script.Add('  PRIMARY KEY (id_album),');
  Script.Add('  KEY id_serie (id_serie),');
  Script.Add('  FULLTEXT KEY uppertitrealbum (uppertitrealbum),');
  Script.Add('  FULLTEXT KEY uppersujetalbum (uppersujetalbum),');
  Script.Add('  FULLTEXT KEY upperremarquesalbum (upperremarquesalbum)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/series (');
  Script.Add('  id_serie char(38) NOT NULL,');
  Script.Add('  titreserie varchar(150) NOT NULL,');
  Script.Add('  id_editeur char(38) default NULL,');
  Script.Add('  id_collection char(38) default NULL,');
  Script.Add('  sujetserie longtext,');
  Script.Add('  remarquesserie longtext,');
  Script.Add('  terminee smallint(6) default 0,');
  Script.Add('  complete smallint(6) default 0,');
  Script.Add('  siteweb varchar(255) default NULL,');
  Script.Add('  suivremanquants smallint(6) default 1,');
  Script.Add('  suivresorties smallint(6) default 1,');
  Script.Add('  uppertitreserie varchar(150) default NULL,');
  Script.Add('  initialetitreserie char(1) NOT NULL,');
  Script.Add('  soundextitreserie varchar(30) default NULL,');
  Script.Add('  uppersujetserie longtext,');
  Script.Add('  upperremarquesserie longtext,');
  Script.Add('  dc_series timestamp,');
  Script.Add('  dm_series timestamp,');
  Script.Add('  nb_albums int(11) default NULL,');
  Script.Add('  PRIMARY KEY  (id_serie),');
  Script.Add('  KEY id_editeur (id_editeur),');
  Script.Add('  KEY id_collection (id_collection),');
  Script.Add('  FULLTEXT KEY uppertitreserie (uppertitreserie)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/personnes (');
  Script.Add('  id_personne char(38) NOT NULL,');
  Script.Add('  nompersonne varchar(150) default NULL,');
  Script.Add('  uppernompersonne varchar(150) default NULL,');
  Script.Add('  initialenompersonne char(1) default NULL,');
  Script.Add('  biographie longtext,');
  Script.Add('  siteweb varchar(255) default NULL,');
  Script.Add('  dc_personnes timestamp,');
  Script.Add('  dm_personnes timestamp,');
  Script.Add('  PRIMARY KEY  (id_personne),');
  Script.Add('  FULLTEXT KEY uppernompersonne (uppernompersonne)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/editions (');
  Script.Add('  id_edition char(38) NOT NULL,');
  Script.Add('  id_album char(38) NOT NULL,');
  Script.Add('  id_editeur char(38) NOT NULL,');
  Script.Add('  id_collection char(38) default NULL,');
  Script.Add('  anneeedition smallint(6) default NULL,');
  Script.Add('  prix decimal(15,2) default NULL,');
  Script.Add('  vo smallint(6) default 0,');
  Script.Add('  couleur smallint(6) default 1,');
  Script.Add('  isbn char(13) default NULL,');
  Script.Add('  prete smallint(6) default 0,');
  Script.Add('  stock smallint(6) default 1,');
  Script.Add('  dedicace smallint(6) default 0,');
  Script.Add('  etat int(11) default NULL,');
  Script.Add('  reliure int(11) default NULL,');
  Script.Add('  typeedition int(11) default NULL,');
  Script.Add('  notes longtext,');
  Script.Add('  dateachat date default NULL,');
  Script.Add('  gratuit smallint(6) default 0,');
  Script.Add('  offert smallint(6) default 0,');
  Script.Add('  nombredepages int(11) default NULL,');
  Script.Add('  orientation smallint(6) default NULL,');
  Script.Add('  formatedition smallint(6) default NULL,');
  Script.Add('  anneecote smallint(6) default NULL,');
  Script.Add('  prixcote decimal(15,2) default NULL,');
  Script.Add('  dc_editions timestamp,');
  Script.Add('  dm_editions timestamp,');
  Script.Add('  numeroperso varchar(25) default NULL,');
  Script.Add('  senslecture smallint(6) default NULL,');
  Script.Add('  PRIMARY KEY (id_edition),');
  Script.Add('  KEY id_album (id_album),');
  Script.Add('  KEY id_editeur (id_editeur),');
  Script.Add('  KEY id_collection (id_collection)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/editeurs (');
  Script.Add('  id_editeur char(38) NOT NULL,');
  Script.Add('  nomediteur varchar(50) NOT NULL,');
  Script.Add('  uppernomediteur varchar(50) NOT NULL,');
  Script.Add('  initialenomediteur char(1) NOT NULL,');
  Script.Add('  siteweb varchar(255) default NULL,');
  Script.Add('  dc_editeurs timestamp,');
  Script.Add('  dm_editeurs timestamp,');
  Script.Add('  PRIMARY KEY (id_editeur)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/collections (');
  Script.Add('  id_collection char(38) NOT NULL,');
  Script.Add('  nomcollection varchar(50) NOT NULL,');
  Script.Add('  id_editeur char(38) NOT NULL,');
  Script.Add('  uppernomcollection varchar(50) NOT NULL,');
  Script.Add('  initialenomcollection char(1) NOT NULL,');
  Script.Add('  dc_collections timestamp,');
  Script.Add('  dm_collections timestamp,');
  Script.Add('  PRIMARY KEY (id_collection),');
  Script.Add('  KEY id_editeur (id_editeur)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/genres (');
  Script.Add('  id_genre char(38) NOT NULL,');
  Script.Add('  genre varchar(30) default NULL,');
  Script.Add('  uppergenre varchar(30) default NULL,');
  Script.Add('  initialegenre char(1) default NULL,');
  Script.Add('  dc_genres timestamp,');
  Script.Add('  dm_genres timestamp,');
  Script.Add('  PRIMARY KEY (id_genre)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/genreseries (');
  Script.Add('  id_genreseries char(38) NOT NULL,');
  Script.Add('  id_serie char(38) NOT NULL,');
  Script.Add('  id_genre char(38) NOT NULL,');
  Script.Add('  dc_genreseries timestamp,');
  Script.Add('  dm_genreseries timestamp,');
  Script.Add('  PRIMARY KEY (id_genreseries),');
  Script.Add('  KEY id_serie (id_serie),');
  Script.Add('  KEY id_genre (id_genre)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/auteurs (');
  Script.Add('  id_auteur char(38) NOT NULL,');
  Script.Add('  id_album char(38) NOT NULL,');
  Script.Add('  id_personne char(38) NOT NULL,');
  Script.Add('  metier smallint(6) NOT NULL,');
  Script.Add('  dc_auteurs timestamp,');
  Script.Add('  dm_auteurs timestamp,');
  Script.Add('  PRIMARY KEY (id_auteur),');
  Script.Add('  KEY id_album (id_album),');
  Script.Add('  KEY id_personne (id_personne),');
  Script.Add('  KEY metier (metier)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/listes (');
  Script.Add('  id_liste char(38) NOT NULL,');
  Script.Add('  ref int(11) NOT NULL,');
  Script.Add('  categorie int(11) NOT NULL,');
  Script.Add('  libelle varchar(50) default NULL,');
  Script.Add('  ordre int(11) default NULL,');
  Script.Add('  defaut smallint(6) default 0,');
  Script.Add('  dc_listes timestamp,');
  Script.Add('  dm_listes timestamp,');
  Script.Add('  PRIMARY KEY  (id_liste),');
  Script.Add('  KEY ref (ref)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/couvertures (');
  Script.Add('  id_couverture char(38) NOT NULL,');
  Script.Add('  id_album char(38) default NULL,');
  Script.Add('  id_edition char(38) default NULL,');
  Script.Add('  ordre int(11) default NULL,');
  Script.Add('  categorieimage smallint(6) default NULL,');
  Script.Add('  dc_couvertures timestamp,');
  Script.Add('  dm_couvertures timestamp,');
  Script.Add('  PRIMARY KEY  (id_couverture),');
  Script.Add('  KEY id_album (id_album),');
  Script.Add('  KEY id_edition (id_edition)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/albums_manquants (');
  Script.Add('  id_serie char(38) default NULL,');
  Script.Add('  countserie int(11) default NULL,');
  Script.Add('  titreserie varchar(150) default NULL,');
  Script.Add('  uppertitreserie varchar(150) default NULL,');
  Script.Add('  tome int(11) default NULL,');
  Script.Add('  id_editeur char(38) default NULL,');
  Script.Add('  nomediteur varchar(50) default NULL,');
  Script.Add('  id_collection char(38) default NULL,');
  Script.Add('  nomcollection varchar(50) default NULL,');
  Script.Add('  achat smallint(6) default NULL,');
  Script.Add('  KEY id_serie (id_serie),');
  Script.Add('  KEY id_editeur (id_editeur),');
  Script.Add('  KEY id_collection (id_collection),');
  Script.Add('  KEY uppertitreserie (uppertitreserie),');
  Script.Add('  KEY tome (tome),');
  Script.Add('  KEY achat (achat)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('CREATE TABLE IF NOT EXISTS /*DB_PREFIX*/previsions_sorties (');
  Script.Add('  id_serie char(38) default NULL,');
  Script.Add('  titreserie varchar(150) default NULL,');
  Script.Add('  uppertitreserie varchar(150) default NULL,');
  Script.Add('  tome int(11) default NULL,');
  Script.Add('  anneeparution int(11) default NULL,');
  Script.Add('  moisparution int(11) default NULL,');
  Script.Add('  id_editeur char(38) default NULL,');
  Script.Add('  nomediteur varchar(50) default NULL,');
  Script.Add('  id_collection char(38) default NULL,');
  Script.Add('  nomcollection varchar(50) default NULL,');
  Script.Add('  KEY id_serie (id_serie),');
  Script.Add('  KEY uppertitreserie (uppertitreserie),');
  Script.Add('  KEY tome (tome),');
  Script.Add('  KEY parution (anneeparution,moisparution),');
  Script.Add('  KEY id_editeur (id_editeur),');
  Script.Add('  KEY id_collection (id_collection)');
  Script.Add(') DEFAULT CHARSET=utf8;');
  Script.Add('@@');

  Script.Add('create view /*DB_PREFIX*/vw_liste_albums(');
  Script.Add('    id_album,');
  Script.Add('    titrealbum,');
  Script.Add('    tome,');
  Script.Add('    tomedebut,');
  Script.Add('    tomefin,');
  Script.Add('    horsserie,');
  Script.Add('    integrale,');
  Script.Add('    moisparution,');
  Script.Add('    anneeparution,');
  Script.Add('    id_serie,');
  Script.Add('    titreserie,');
  Script.Add('    uppertitrealbum,');
  Script.Add('    uppertitreserie,');
  Script.Add('    achat,');
  Script.Add('    complet,');
  Script.Add('    initialetitrealbum,');
  Script.Add('    initialetitreserie)');
  Script.Add('as');
  Script.Add('select a.id_album,');
  Script.Add('       a.titrealbum,');
  Script.Add('       a.tome,');
  Script.Add('       a.tomedebut,');
  Script.Add('       a.tomefin,');
  Script.Add('       a.horsserie,');
  Script.Add('       a.integrale,');
  Script.Add('       a.moisparution,');
  Script.Add('       a.anneeparution,');
  Script.Add('       a.id_serie,');
  Script.Add('       s.titreserie,');
  Script.Add('       a.uppertitrealbum,');
  Script.Add('       s.uppertitreserie,');
  Script.Add('       a.achat,');
  Script.Add('       a.complet,');
  Script.Add('       coalesce(a.initialetitrealbum, s.initialetitreserie),');
  Script.Add('       s.initialetitreserie');
  Script.Add('from /*DB_PREFIX*/albums a left join /*DB_PREFIX*/series s on s.id_serie = a.id_serie');
  Script.Add(';');
  Script.Add('@@');

  Script.Add('create view /*DB_PREFIX*/vw_liste_editeurs_albums(');
  Script.Add('    id_album,');
  Script.Add('    titrealbum,');
  Script.Add('    tome,');
  Script.Add('    tomedebut,');
  Script.Add('    tomefin,');
  Script.Add('    horsserie,');
  Script.Add('    integrale,');
  Script.Add('    moisparution,');
  Script.Add('    anneeparution,');
  Script.Add('    id_serie,');
  Script.Add('    titreserie,');
  Script.Add('    uppertitrealbum,');
  Script.Add('    id_editeur,');
  Script.Add('    nomediteur,');
  Script.Add('    uppernomediteur,');
  Script.Add('    uppertitreserie,');
  Script.Add('    achat,');
  Script.Add('    complet)');
  Script.Add('as');
  Script.Add('select a.id_album,');
  Script.Add('       a.titrealbum,');
  Script.Add('       a.tome,');
  Script.Add('       a.tomedebut,');
  Script.Add('       a.tomefin,');
  Script.Add('       a.horsserie,');
  Script.Add('       a.integrale,');
  Script.Add('       a.moisparution,');
  Script.Add('       a.anneeparution,');
  Script.Add('       a.id_serie,');
  Script.Add('       a.titreserie,');
  Script.Add('       a.uppertitrealbum,');
  Script.Add('       e.id_editeur,');
  Script.Add('       e.nomediteur,');
  Script.Add('       e.uppernomediteur,');
  Script.Add('       a.uppertitreserie,');
  Script.Add('       a.achat,');
  Script.Add('       a.complet');
  Script.Add('from /*DB_PREFIX*/vw_liste_albums a left join /*DB_PREFIX*/editions ed on ed.id_album = a.id_album');
  Script.Add('                       left join /*DB_PREFIX*/editeurs e on e.id_editeur = ed.id_editeur');
  Script.Add(';');
  Script.Add('@@');

  Script.Add('create view /*DB_PREFIX*/vw_liste_collections_albums(');
  Script.Add('    id_album,');
  Script.Add('    titrealbum,');
  Script.Add('    tome,');
  Script.Add('    tomedebut,');
  Script.Add('    tomefin,');
  Script.Add('    horsserie,');
  Script.Add('    integrale,');
  Script.Add('    moisparution,');
  Script.Add('    anneeparution,');
  Script.Add('    id_serie,');
  Script.Add('    titreserie,');
  Script.Add('    uppertitrealbum,');
  Script.Add('    id_collection,');
  Script.Add('    nomcollection,');
  Script.Add('    uppernomcollection,');
  Script.Add('    uppertitreserie,');
  Script.Add('    achat,');
  Script.Add('    complet)');
  Script.Add('as');
  Script.Add('select a.id_album,');
  Script.Add('       a.titrealbum,');
  Script.Add('       a.tome,');
  Script.Add('       a.tomedebut,');
  Script.Add('       a.tomefin,');
  Script.Add('       a.horsserie,');
  Script.Add('       a.integrale,');
  Script.Add('       a.moisparution,');
  Script.Add('       a.anneeparution,');
  Script.Add('       a.id_serie,');
  Script.Add('       a.titreserie,');
  Script.Add('       a.uppertitrealbum,');
  Script.Add('       c.id_collection,');
  Script.Add('       c.nomcollection,');
  Script.Add('       c.uppernomcollection,');
  Script.Add('       a.uppertitreserie,');
  Script.Add('       a.achat,');
  Script.Add('       a.complet');
  Script.Add('from /*DB_PREFIX*/vw_liste_albums a left join /*DB_PREFIX*/editions e on e.id_album = a.id_album');
  Script.Add('                       left join /*DB_PREFIX*/collections c on e.id_collection = c.id_collection');
  Script.Add(';');
  Script.Add('@@');

  Script.Add('create view /*DB_PREFIX*/vw_liste_genres_albums(');
  Script.Add('    id_album,');
  Script.Add('    titrealbum,');
  Script.Add('    tome,');
  Script.Add('    tomedebut,');
  Script.Add('    tomefin,');
  Script.Add('    horsserie,');
  Script.Add('    integrale,');
  Script.Add('    moisparution,');
  Script.Add('    anneeparution,');
  Script.Add('    id_serie,');
  Script.Add('    titreserie,');
  Script.Add('    uppertitrealbum,');
  Script.Add('    id_genre,');
  Script.Add('    genre,');
  Script.Add('    uppergenre,');
  Script.Add('    uppertitreserie,');
  Script.Add('    achat,');
  Script.Add('    complet)');
  Script.Add('as');
  Script.Add('select a.id_album,');
  Script.Add('       a.titrealbum,');
  Script.Add('       a.tome,');
  Script.Add('       a.tomedebut,');
  Script.Add('       a.tomefin,');
  Script.Add('       a.horsserie,');
  Script.Add('       a.integrale,');
  Script.Add('       a.moisparution,');
  Script.Add('       a.anneeparution,');
  Script.Add('       a.id_serie,');
  Script.Add('       a.titreserie,');
  Script.Add('       a.uppertitrealbum,');
  Script.Add('       g.id_genre,');
  Script.Add('       g.genre,');
  Script.Add('       g.uppergenre,');
  Script.Add('       a.uppertitreserie,');
  Script.Add('       a.achat,');
  Script.Add('       a.complet');
  Script.Add('from /*DB_PREFIX*/vw_liste_albums a left join /*DB_PREFIX*/genreseries gs on gs.id_serie = a.id_serie');
  Script.Add('                       left join /*DB_PREFIX*/genres g on gs.id_genre = g.id_genre');
  Script.Add(';');
  Script.Add('@@');
end;

initialization

RegisterMySQLUpdate('1.0.0.0', @MAJ1_0_0_0);

end.
